/** Player-facing projections only. Does not advance clocks or write world state. */
import {BUILDING_GRID,buildingGridEnabled,buildingCellLabel} from './ea-building-grid.mjs?v=ea-160-courtyard-20261008-r11';
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=v=>Array.isArray(v)?v:[];
const names={wood:'灵木',stone:'青石',herb:'灵草',food:'口粮',jade:'灵石',crystal:'灵晶',insight:'道韵',weapon:'兵器',armor:'衣甲',artifact:'法器',accessory:'饰物','pill:heal':'回春散','pill:qi':'聚气丹','pill:spirit':'灵息丹','pill:foundation':'筑基丹'};
const cost=v=>Object.entries(v||{}).filter(([,n])=>n).map(([k,n])=>`${names[k]||k} ${Math.ceil(n)}`).join(' · ')||'无额外材料';
const B=(label,command,args=[],reason='')=>`<button type="button" class="secondary" data-ui-action="${E(command)}" data-ui-args="${E(JSON.stringify(args))}"${reason?` disabled title="${E(reason)}"`:''}>${E(label)}</button>`;
const C=(title,body,key)=>`<article class="sr-card" data-key="${E(key||title)}"><h4>${E(title)}</h4>${body}</article>`;
const phases={moving:'实际行走',working:'正在劳动',paused:'条件未满足，保留进度',home:'已实际抵院',market:'坊市装运',channeling:'现场接引',descending:'实际跨界',present:'来客在场',aiding:'现场护界',stranded:'有限界门已关闭','to-anchor':'实际赶往接引台','to-client':'前往客商',repairing:'实际修箱','awaiting-payment':'等待客商实际送款','not-present':'尚未实际抵院',finished:'本约完成',settled:'已结清',unmet:'尚未接洽',geography:'查验地方旧约','transport-capability':'办理实际行旅契约',boarded:'已登乘',used:'已到达',waiting:'候班',reserved:'已预留',executing:'实际执行',blocked:'等待条件',completed:'已完成',cancelled:'已取消',available:'可商议',accepted:'已接下',declined:'已拒绝',delivered:'已交付',carrying:'携带途中','to-source':'前往取料',foundation:'打地基',structure:'立结构',finishing:'收尾',windup:'起手',execute:'执行',recovery:'收势',active:'已生效',unverified:'尚未核实',corroborated:'有事实互证',uncertain:'尚不确定',interrupted:'已中止',paid:'已兑付',corrected:'已纠正',retained:'保护留存',dissipated:'已消散',returning:'正在收回',returned:'已收回',destroyed:'已损毁',production:'生产',transport:'搬运',replenish:'恢复来源',trade:'交易',teach:'授业','pill-craft':'实际炼丹','soul-retain':'魂魄保护','avatar-form':'形成化身','lifespan-extend':'炼化延寿灵剂','high-chapter':'研取高阶续篇','high-material':'取得突破灵材','high-study':'共享续篇研习','high-material-gift':'实际交接灵材',overdue:'已逾期',fulfilled:'已履行',released:'已协商解除',breached:'违约后果持续',proposed:'待签成',unasked:'尚未商议',cooperating:'共同合作',rest:'休息',study:'研习',retrain:'转修',breakthrough:'突破','foundation-source':'准备筑基',sign:'签署',deliver:'交付',release:'解除',outbound:'实际赶路',walking:'现场行走',observing:'现场查验',recalled:'已收束观察','counter-divination':'现场消解息纹',content:'现场文书与交付',divine:'有锚卜算',investigate:'现场查证',walk:'实际行走',interact:'现场交互',guard:'护卫',focus:'协同压制',rally:'集结',retreat:'撤离'};const phase=v=>phases[v]||String(v??'等待');
const P=t=>`<p>${E(t)}</p>`;
const S=t=>`<p class="sr-state" role="status">${E(t)}</p>`;
const options=(values,selected)=>values.map(v=>typeof v==='string'?{id:v,name:v}:v).map(v=>`<option value="${E(v.id)}"${v.id===selected?' selected':''}>${E(v.name||v.label||v.id)}</option>`).join('');
const F=(command,fields,extra='',button='确认')=>`<form class="sr-form" data-ui-form="sr" data-command="${E(command)}">${fields}${extra}<button type="submit" class="primary">${E(button)}</button></form>`;
const input=(name,label,{value='',type='text',min,max,step}={})=>`<label>${E(label)}<input data-ui-draft name="${E(name)}" type="${type}" value="${E(value)}"${min!==undefined?` min="${min}"`:''}${max!==undefined?` max="${max}"`:''}${step!==undefined?` step="${step}"`:''}${name==='key'?'':' required'}></label>`;
const select=(name,label,values,selected)=>`<label>${E(label)}<select data-ui-draft name="${E(name)}">${options(values,selected)}</select></label>`;
const call=(sim,name,s)=>typeof sim[name]==='function'?sim[name](s):null;
function equipment(s,sim){
 const v=call(sim,'viewEquipment',s);if(!v)return '';const cards=[],members=list(s.homeMemberIds).map(id=>({id,name:s.personsById?.[id]?.name||'门人'}));
 for(const slot of v.slots){const owned=list(v.items).filter(i=>i.ownerId==='person:master'&&i.definition?.slot===slot);cards.push(C(names[slot],owned.map(i=>{
 const holder=i.location?.kind==='person'&&i.location.id!=='person:master'?s.personsById?.[i.location.id]?.name:null;
 return P(`${i.definition.name} · 完好${Math.round(i.condition*100)}%${i.location?.slot?' · 已装备':''}${holder?' · '+holder+'实际保管':''}`)+`<div class="button-row">${B('装备','equipItem',[i.id,slot])}${B('收入行囊','storeItem',[i.id])}${B('修复','repairEquipment',[i.id],i.condition>=1?'当前完好':'')}${i.loan?B('提出到场归还','returnEquipment',[i.id]):''}${!i.loan&&members.length?F('lendEquipment',`<input type="hidden" name="id" value="${E(i.id)}">`+select('borrowerId','愿意接借的门人',members)+input('durationTicks','借期（每10刻为1游戏秒）',{type:'number',value:600,min:100,max:2400,step:10}),P('双方实际会面且物品可交付；门人可以拒绝。'),'商议借出'):''}${!i.loan&&!i.binding&&members.length?F('giftEquipment',`<input type="hidden" name="id" value="${E(i.id)}">`+select('recipientId','实际会面赠予的门人',members),P('赠予后所有权属于对方；需要到场交付，不自动强制装备。'),'确认赠予'):''}${i.loan?B('请保管者考虑换装','offerEquipItem',[i.id,i.loan.borrowerId]):''}${v.bindingEnabled?B(i.binding?'解除本命':'缔结本命','srDanger',[i.binding?'解除需灵草10、灵石20与实际仪式时间；当前实物保留。':'缔结需筑基、完整私有实物、灵晶3、灵草12、灵石35与20秒仪式；本命反馈按规则产生。',i.binding?'unbindEquipment':'bindEquipment',[i.id]]):''}</div>`;
 }).join('')||P('尚无此槽装备；可通过匠作或已知事件获取。'),'sr-slot-'+slot));}
 const visibleNPCItems=list(v.visibleNpcItems);
 if(visibleNPCItems.length)cards.push(C('门人公开携装',visibleNPCItems.map(i=>P(`${s.personsById?.[i.ownerId]?.name||'门人'} · ${i.definition.name} · 完好${Math.round(i.condition*100)}%`)+B('当面商议换装','offerEquipItem',[i.id,i.holderId||i.location?.id||i.ownerId])).join('')));
 const defs=Object.entries(sim.EQUIPMENT_DEFINITIONS||sim.EQUIPMENT||{}).filter(([,d])=>d.slot);if(defs.length)cards.push(C('匠作与来源',defs.map(([id,d])=>P(`${d.name} · ${cost(d.cost)} · 制作${d.ticks/10}游戏秒`)+B('制作','craftEquipment',[id])).join('')));
 if(v.benefits)cards.push(C('装备的实际作用',P(`承伤减免${Math.round(v.benefits.guard*100)}% · 疗养倍率${v.benefits.healMultiplier.toFixed(2)} · 伤害倍率${v.benefits.damageMultiplier.toFixed(2)}`)+P(v.benefits.bindingActive?'本命实物当前有效；损坏或离身失去加持。':'本命加持当前未生效。')));
 if(v.bindingEnabled)cards.push(C('本命的条件与反馈',P(v.bindingRule)));
 cards.push(C('雨后伤匠',S(phase(v.artisan?.phase))+B('提出共同制器','artisanCooperate',[true])+B('暂缓合作','artisanCooperate',[false])+['robe','seal','pendant'].map(role=>B('获取'+({robe:'护脉衣图谱',seal:'阵印部件',pendant:'遗坠拓录'}[role]),'artisanAcquirePart',[role])).join('')+B('请教制器','artisanLearn')));
 cards.push(...list(v.orders).map(o=>C('匠作进度',S(`${phase(o.phase)} · ${Math.ceil(o.progressTicks/10)}/${Math.ceil(o.durationTicks/10)}游戏秒 · ${o.reason||'按世界时间推进'}`)+B('取消并保留已发生消耗','cancelEquipmentOrder',[o.id]),'equip-order-'+o.id)));return cards.join('');
}
function economy(s,sim){
 const v=call(sim,'viewEconomy',s);if(!v?.enabled)return '';const stockpiles=list(v.stockpiles),usable=stockpiles.filter(p=>p.access!=='merchant'&&p.position?.sceneId==='scene:yunxiu-courtyard'),pillOptions=piles=>Object.entries(sim.RECIPES||{}).filter(([id])=>piles.some(p=>(p.pills?.[id]||0)>0)).map(([id,r])=>({id:'pill:'+id,name:r.name+'（实际成丹）'})),stocks=usable.map(p=>({id:p.id,name:p.label.startsWith('stockpile:')?({'stockpile:yunxiu':'院中公库','stockpile:sr-party':'随行物资'})[p.id]||'暂存物资':p.label}));
 let inventory=stockpiles.map(p=>C(p.label.startsWith('stockpile:')?({'stockpile:yunxiu':'院中公库','stockpile:qingxi':'青溪商人现货','stockpile:sr-party':'随行物资'})[p.id]||'暂存物资':p.label,P(`${cost(p.resources)} · 容量${p.capacity??'按资源限制'}`)+P('此处成丹：'+(Object.entries(p.pills||{}).filter(([,n])=>n>0).map(([id,n])=>`${sim.RECIPES?.[id]?.name||'已知成丹'} ${n}枚`).join(' · ')||'暂无'))+P(p.access==='merchant'?'商人私有现货；须到场买卖，不能直接搬走。':'公私所有权分别记录；取用与搬运需要实际许可和到场。'),'stock-'+p.id)).join('');
 if(stocks.length>=2)inventory+=C('实际搬运与自愿协作',F('startTransport',select('sourceId','从哪处实际取料',stocks)+select('targetId','向哪处实际交付',stocks,'stockpile:yunxiu')+select('carrierId','邀请搬运者',[{id:'person:master',name:'掌门亲自搬运'},...list(s.homeMemberIds).map(id=>({id,name:s.personsById?.[id]?.name||'门人'}))])+select('resource','搬运物资',[...Object.entries(sim.RESOURCES||names).filter(([id])=>id!=='insight'&&usable.some(p=>p.resources?.[id]>0)).map(([id,name])=>({id,name:names[id]||name})),...pillOptions(usable)])+input('amount','数量（每批最多40份）',{type:'number',value:10,min:1,max:40,step:1}),P('取料与投放需同院；门人会自主回应，已有承诺/伤势/拒绝须先处理。'),'提出搬运计划'));
 inventory+=list(v.transports).filter(t=>!['completed','delivered','cancelled'].includes(t.phase)).map(t=>C('在途搬运',S(`${phase(t.phase)} · ${t.reason||'前往实际交付位置'} · ${cost(t.cargo)}`)+B('取消并保留已搬物资','cancelTransport',[t.id]),'transport-'+t.id)).join('');
 const replenishing=s.activitiesById?.[s.master.activityId];if(replenishing?.kind==='sr-replenish')inventory+=C('正在恢复来源',S(`${phase(replenishing.phase)} · ${replenishing.reason} · ${Math.ceil(replenishing.progressTicks/10)}/${Math.ceil(replenishing.durationTicks/10)}游戏秒`)+B('取消，退回未施工材料','cancelReplenish'));
 if(list(v.giftRecipients).length){const sources=stockpiles.filter(p=>p.access!=='merchant'&&p.position?.sceneId===s.master.location?.sceneId).map(p=>({id:p.id,name:p.id==='stockpile:yunxiu'?'院中公库':p.id==='stockpile:sr-party'?'随行物资':p.label}));if(sources.length)inventory+=C('实际当面赠予',F('transferProperty',select('sourceId','有权交付的来源',sources)+select('targetId','身边可见的受赠人',v.giftRecipients.map(p=>({id:p.stockpileId,name:p.name})))+select('resource','物资',[...Object.entries(sim.RESOURCES||names).map(([id,name])=>({id,name:names[id]||name})),...pillOptions(stockpiles.filter(p=>p.access!=='merchant'&&p.position?.sceneId===s.master.location?.sceneId))])+input('quantity','份数',{type:'number',value:1,min:1,max:40,step:1}),P('双方与实物须同地近旁，需先携带所需物资。只显示受赠对象，不展示其私人余额。'),'确认实物赠予'));}
 inventory+=C('有限来源与恢复',Object.entries(v.patches||{}).map(([id,p])=>P(`${names[id]||sim.RESOURCES?.[id]||id} · 剩余${Math.floor(p.remaining)}/${p.max}`)+(id!=='stone'?B('补种或恢复'+(names[id]||sim.RESOURCES?.[id]||id),'replenishPatch',[id],p.remaining>p.max*.25?'尚有超过四分之一来源，无须恢复':''):P('矿脉不可凭空再生，可采购或寻新矿源。'))).join(''));
 inventory+=C('实际出入账',list(v.ledger).map(f=>P(`${phase(f.operation)} · ${cost(f.quantities||f.cost||f.reward)} · 世界刻${f.atTick??f.createdTick??'已记录'}`)).join('')||P('尚无物资交易记录。'));
 const merchant=stockpiles.find(p=>p.id==='stockpile:qingxi'),tradeLock=v.market?.merchantPresent?'':'需到坊市，或等待商队真实抵院并走近';let market=C('青溪现货交易',P('每组10份，买卖以实际现货与本金结算。补货受道路与有限来源限制，反复开菜单不补货。')+Object.entries(v.market?.goods||{}).map(([id,g])=>P(`${g.name} · 现货${merchant?.resources[id]??0}份 · 买${g.buy}/卖${g.sell}灵石每组`)+`<div class="button-row">${B('买入一组','marketTrade',[id,'buy',1],tradeLock)}${B('卖出一组','marketTrade',[id,'sell',1],tradeLock)}</div>`).join(''));
 market+=list(v.market?.orders).map(o=>C(o.name,P(`交付 ${cost(o.cost)}；酬谢 ${cost(o.reward)}`)+S(phase(o.state?.phase||o.state))+`<div class="button-row">${B('接下委托','marketOrder',[o.id,'accept'])}${B('当面交付','marketOrder',[o.id,'deliver'])}${B('拒绝/取消','marketOrder',[o.id,'decline'])}</div>`,'market-order-'+o.id)).join('');
 return `<div data-sr-production="inventory">${inventory}</div><div data-sr-production="market" id="sr-market-section">${market}</div>`;
}
function travelCargoFields(s){if(s.master.location?.sceneId!=='scene:yunxiu-courtyard')return '';const defaults={jade:30,herb:12,food:12,wood:10,stone:10,crystal:2};return '<details class="sr-travel-cargo"><summary>随行物资：从公库实际装入行囊</summary><p>总量不超过400份；先支付行程费用，再装入你确认的份额。已有行囊物资保留，院外无法使用远方公库。</p>'+Object.entries(defaults).map(([id,n])=>input('cargo_'+id,names[id]||id,{type:'number',value:Math.min(n,Math.floor(s.resources[id]||0)),min:0,max:400,step:1})).join('')+'</details>';}
function worldContent(s,sim,v){
 if(!v)return '';let html=v.director?C('当下负担与现场机会',S(v.director.reason)+P(`当前负担${v.director.pressure} · 已接触待处理机会${v.director.activeCount}`)+P('当面接洽才会提供实际机会；先养伤、调息或处理已发生争议，菜单不会刷新邀约或改变原单。')):'';
 html+=list(v.cards).map(c=>C(c.title,P(`${c.personName||'已知接洽人'} · ${sim.WORLD_SCENES?.[c.sceneId]?.name||'已知接洽地点'} · 来讯世界刻${c.offeredTick}`)+(c.publicRequest?P(c.publicRequest):'')+S(`${phase(c.status)} · ${c.verified?'原单已现场核对':'口信尚未核对原单'}${c.corrected?' · 已按凭证纠正':''}`)+P(`口信主单：交付 ${cost(c.cost)}；约定所得 ${cost(c.reward)}。`)+P(c.terms===null?'完整附条尚未实查；可先核对原单，再决定是否按主单交货。':`已查原单附条：${cost(c.terms)}。`)+(Object.values(c.paidTerms||{}).some(n=>n>0)?P('已实际付出的附费：'+cost(c.paidTerms)):'')+(c.position?B('走近实际接洽人','srWorldCommand',[{action:'move',x:c.position.x,y:c.position.y+2}]):B('亲赴已知接洽地点','srWorldCommand',[{action:'travel',destination:c.sceneId}],s.srWorld.knownScenes.includes(c.sceneId)?s.master.location?.sceneId===c.sceneId?'当事人已离场，不能隔空交货':'':'须先实际获知此路'))+`<div class="button-row">${list(c.actions).map(a=>B(a.label,'srWorldCommand',[{action:'content',cardId:c.id,choice:a.choice}],a.disabled?'须先同地近旁会面，核对所需原单；已完成的本批不重复交货':'')).join('')}</div>`+P('交付期间双方须持续在场；当前世界行动可中止，按已发生工序退未耗成本，实物、文书与历史保留。'),'world-content-'+c.id)).join('');return html+localIndustry(v.industry);
}
function industryActions(actions){return `<div class="button-row">${list(actions).map(a=>B(a.label,'srWorldCommand',[a.payload],a.disabled?'须本人携物并在实际接洽者或来源近旁，满足材料与驱动条件':'')).join('')}</div>`;}
function localIndustry(v){
 if(!v)return '';let html=C('地方寄售与鬼市',P(v.scope));
 html+=list(v.organizations).map(o=>C(o.name,P(o.personName+' · '+phase(o.status))+(o.terms?P(o.terms)+P(o.authority):P('完整约定须在当事人近旁会谈后获知。'))+(o.position?B('走近接洽人','srWorldCommand',[{action:'move',x:o.position.x,y:o.position.y+2}]):'')+industryActions(o.actions),'industry-org-'+o.id)).join('');
 html+=list(v.offers).map(o=>C(o.title,P(`本批剩余${o.remaining}件 · ${cost(o.cost)} · 实际交付${o.durationTicks/10}游戏秒`)+P('原材记录：'+cost(o.materials))+P(o.control)+P(o.rule)+industryActions(o.actions),'industry-offer-'+o.id)).join('');
 html+=list(v.items).map(i=>C(i.name,P(`完好${Math.round(i.condition*100)}%${i.type==='ghost-tool'?' · 剩余驱动'+i.charges+'次':''}`)+(i.power?S(`有限晶芯：${phase(i.power.status)} · 剩余${Math.ceil(i.power.remaining)}点；截止世界刻${i.power.expiresTick}`):'')+P(i.control)+P(i.rule)+P(i.source)+industryActions(i.actions),'industry-item-'+i.id)).join('');return html;
}
function aftermath(s,sim){
 const v=call(sim,'viewAftermath',s);if(!v)return '';let html='';
 html+=list(v.deaths).map(d=>C(d.name+' · 已获知身后事项',P(`可靠死亡消息：世界刻${d.observedDeathTick} · ${sim.WORLD_SCENES?.[d.lastKnownSceneId]?.name||'已知死亡地点'}`)+P(d.rule)+(!d.obligationsKnown?P('亲属与借契尚未查明；须到遗体和原遗物2.6米内，再选择到场搜索核对原有旧信。'):'')+(s.srWorld.knownScenes.includes(d.lastKnownSceneId)&&s.master.location?.sceneId!==d.lastKnownSceneId?B('亲赴已知现场','srWorldCommand',[{action:'travel',destination:d.lastKnownSceneId}]):'')+list(d.kin).map(k=>P(k.name+' · '+(k.notified?'已实际告知':'尚未告知'))+B('当面告知死亡事实','aftermathAction',[{choice:'notify',personId:d.personId,counterpartyId:k.personId}],k.nearby&&!k.notified?'':'须走近已知关系人')+B('当面商议遗物托管','srDanger',['只托管原遗物，保留原所有者；亲属可以拒绝。','aftermathAction',[{choice:'permission',personId:d.personId,counterpartyId:k.personId,informed:true}]],k.nearby?'':'须走近关系人')).join('')+list(d.creditors).map(c=>P(`${c.creditorName} · ${names[c.resource]||c.resource}${c.quantity-c.paid}未结 · ${phase(c.status)}`)+B('当面告知债权人','aftermathAction',[{choice:'notify',personId:d.personId,counterpartyId:c.creditorId}],c.nearby&&!c.notified?'':'须走近已知债权人')+B('知情自愿代偿本笔债务','srDanger',['从自己可取用的实际物资代偿本笔有限债务，不继承其他债务；债权人须在场接受。','aftermathAction',[{choice:'payDebt',personId:d.personId,counterpartyId:c.creditorId,debtId:c.id,informed:true}]],c.nearby&&c.status!=='settled'?'':'须债权人本人在场且尚有未结债务')).join('')+B('知情到场收殓托管','srDanger',['到场收殓会实际占用身体和时间；须关系人许可，遗物留在实际托管包裹中。','aftermathAction',[{choice:'collect',personId:d.personId,informed:true}]],d.canCollect?'':'先取得许可并亲临可收殓的现场')+list(d.kin).map(k=>B('当面交还遗物给'+k.name,'srDanger',['按原托付交还同一件原遗物，只改变实际保管位置。','aftermathAction',[{choice:'handover',personId:d.personId,counterpartyId:k.personId,informed:true}]],k.nearby&&d.collected&&!d.delivered?'':'须已收殓、携带遗物并走近许可关系人')).join(''),'after-death-'+d.personId)).join('');
 html+=list(v.orders).filter(o=>!['completed','cancelled'].includes(o.phase)).map(o=>C('身后事务进度',S(`${phase(o.phase)} · ${o.progressTicks/10}/${o.durationTicks/10}游戏秒 · ${o.reason||'按实际位置推进'}`)+B('中止当前事务','aftermathAction',[{choice:'cancel',orderId:o.id}]),'aftermath-order-'+o.id)).join('');
 if(list(v.reactions).length)html+=C('已获知的关系与评价',list(v.reactions).slice(-8).map(r=>P(r.text)).join(''));return html;
}
function descent(s,sim){
 const v=call(sim,'viewDescentSR',s);if(!v?.enabled||!s.story.completed)return '';let html=C('仙使接引与现场护界',P(v.boundary)+(s.master.location?.sceneId===v.siteSceneId?B('走近接引台','srWorldCommand',[{action:'move',x:v.anchor.x,y:v.anchor.y+4}]):B('亲赴已知接引台','srWorldCommand',[{action:'travel',destination:v.siteSceneId}],s.srWorld.knownScenes.includes(v.siteSceneId)?'':'须先到坊市亲查洲图和道路')));
 html+=list(v.modes).map(m=>C(m.name||({avatar:'化身接引',original:'本尊下凡'})[m.id],P(`本人接引材料 ${cost(m.cost)}；返程另预留 ${cost(m.returnCost)}。上界使者自行支付 ${cost(m.upperCost)}。`)+P(`最低境界${m.minRealm}、阵法理解${m.arrayUnderstanding}；接引${m.channelTicks/10}秒，跨界${m.transitTicks/10}秒，有限驻留${m.stayTicks/10}秒；现场有效境界${m.effectiveRealm}。`)+S(m.reason)+B('知情提交接引请求','srDanger',['确认实际接引与返程费用、有限驻留窗口；来客自主决定，化身损毁反馈本体，本尊死亡不复活。','requestDescent',[m.id,true]],m.available?'':m.reason),'descent-mode-'+m.id)).join('');
 html+=[...list(v.active),...list(v.history).slice(-3)].map(r=>C(r.actorName||'仙使来客',S(`${phase(r.phase)} · ${r.reason||'以最后实地观察为准'} · 观察世界刻${r.observedTick??'尚未到场'}`)+(r.durationTicks?P(`实际进度 ${Math.ceil(r.progressTicks/10)}/${Math.ceil(r.durationTicks/10)}游戏秒`):'')+(r.position?.kind==='scene'&&r.position.sceneId===s.master.location?.sceneId?B('走近最后观察脚点','srWorldCommand',[{action:'move',x:r.position.x,y:r.position.y+2}]):'')+B('当面观察当前情况','descentCommand',[{action:'observe',descentId:r.id}])+B('知情邀请现场护界','srDanger',['稳定现场界隙耗实际灵晶、时间和来客力量；来客可因伤势或返程窗口拒绝。','descentCommand',[{action:'aid',descentId:r.id,informed:true}]],r.canAid?'':'先走近在场且愿意维护的来客')+B('知情请求实际返程','srDanger',['消耗已经托管的返程媒介；来客先走回接引台，再承担实际跨界时间。','returnDescent',[r.id,true]],r.canReturn?'':'先走近可返程的来客')+(r.phase==='channeling'?B('取消未完成接引','descentCommand',[{action:'cancel',descentId:r.id}]):'')+(r.canRepair?B('知情修复一次界门','srDanger',['现场付费施工120刻，重开一次有限返程窗口。','descentCommand',[{action:'repair',descentId:r.id,informed:true}]]):'')+(r.canRecover?B('到场取回剩余媒介','descentCommand',[{action:'recover',descentId:r.id}]):''),'descent-'+r.id)).join('');return html;
}
function lateEconomy(s,sim){
 const v=call(sim,'viewLateEconomy',s);if(!v?.enabled)return '';const vault=s.stockpilesById['stockpile:yunxiu'];let html=C('结局后的商会营缮',P(v.rule)+S(`${v.client.name} · ${phase(v.client.phase)} · 本约尚有${v.remainingOrders}箱；已实付${v.paidTotal}灵石`)+(vault?.position?.sceneId===s.master.location?.sceneId?B('走近实际取材公库','moveScenicMaster',[vault.position.x,vault.position.y]):'')+list(v.availableCrates).map(c=>P(`${c.name} · 修材${cost(c.cost)} · 实修${c.durationTicks/10}秒 · 工资${c.wage}灵石`)+B('取材并亲自修箱',c.command,[c.itemId,c.sourceStockpileId])).join(''));
 if(v.activeOrder){const o=v.activeOrder;html+=C('实际修箱与付款',S(`${phase(o.phase)} · ${o.progressTicks/10}/${o.durationTicks/10}秒 · ${o.reason||'双方按实际路径推进'}`)+B('取消尚未完工委托','cancelLateService',[o.id],o.phase==='awaiting-payment'?'已完成劳动，客商保留应付工资并实际送款':''));}return html;
}
const continentNames={'continent:qingheng':'青衡洲','continent:zhongtian':'中天洲','continent:yanhuang':'炎荒洲','continent:xuanshuo':'玄朔洲','continent:cangliu':'沧流洲'};
function worldSiteActions(v,actions,command){return list(actions).map(a=>{const o=list(v.scene?.objects).find(o=>o.id===a.sourceId);return P(a.label||({acquireMount:'签订云蹄兽代步契约',learnFlight:'实际学习御物沿路飞行',attune:'登记本港传送锚点'})[a.choice]||'现场接洽')+(a.cost?P(`${cost(a.cost)} · ${a.durationTicks/10}游戏秒`):'')+(o?B('走近'+(o.name||'实际来源'),'srWorldCommand',[{action:'move',x:o.x,y:o.y+o.height/2+1}]):'')+B('确认现场办理','srWorldCommand',[{action:command,...(a.regionId?{regionId:a.regionId}:{}),choice:a.choice}],o?'':'须先抵达实际来源');}).join('');}
function geography(s,sim,v){const g=v.geography;if(!g)return '';let html=C('已获洲图与地方查验',P('洲图保留已有方位关系；地方名称与旧约采用作者补全。只有已获位置列在此处，边界、族群、来源与准入须本人现场查证。')+list(g.continents).map(c=>P(`${continentNames[c.id]||'已知洲域'} · 已获地点${list(c.regionIds).length}处`)).join(''));
 html+=list(g.regions).map(r=>{const admitted=list(g.admissions).find(a=>a.sceneId===r.sceneId),people=list(r.peoples).map(id=>list(g.peoples).find(p=>p.id===id)?.name).filter(Boolean),authority=s.factionsById?.[r.authorityId]?.name||s.organizationsById?.[r.authorityId]?.name;return C(r.name,P(`${continentNames[r.continentId]||'已知洲域'} · ${r.terrain}`)+S(r.authorityId?'已亲查边界与旧约':'仅获地点标注，边界与旧约尚未现场核实')+(r.authorityId?P(`已查约定范围：${authority||'当地约章'}；已知居民：${people.join('、')||'尚待接洽'}。`):'')+list(r.borders).filter(b=>s.srWorld.knownScenes.includes(b.neighborSceneId)).map(b=>P('已知相邻道路：'+(sim.WORLD_SCENES?.[b.neighborSceneId]?.name||'已知地点'))).join('')+(r.resourceOrigins?P(r.resourceOrigins.remaining?'当前互济仓实际来源：'+cost(r.resourceOrigins.remaining):'已查互济来源；远方库存数量须到场复核。'):'')+(admitted?S('已取得当地约章准入：'+admitted.scope):P('尚未办理当地准入；须筑基并与当地约仓人三米内会面，6灵石2粮、6游戏秒。'))+(s.master.location?.sceneId!==r.sceneId?B('亲赴已知地域','srWorldCommand',[{action:'travel',destination:r.sceneId}]):worldSiteActions(v,list(g.localActions).filter(a=>a.regionId===r.id),'geography')),'geo-'+r.id);}).join('');
 if(list(g.localActions).some(a=>a.choice==='inspectCore'))html+=C('当地旧印的实际维护',P('亲近查验旧印才会得知本地险情。查验后留意消息中的真实期限；修缮需要4木4石2药和9游戏秒，不会以查看菜单激活或重开已结算险情。'));
 return `<details class="sr-world-geography"><summary>洲图、地方旧约与准入</summary>${html}</details>`;}
function transport(s,sim,v){const t=v.transport;if(!t)return '';let html=C('实际行旅方式',list(t.modes).map(m=>P(`${m.name}：${m.scope}`)+S(m.acquired?`已取得实际运具${m.condition===null?'':` · 完好${Math.round(m.condition*100)}%`}`:'尚未取得实际归属的运具')+P(`耗时系数${m.speedFactor} · 精力系数${m.energyFactor} · 额外${cost(m.additionalCost)}${m.minimumRealm?' · 需筑基功体':''}${m.minimumUnderstanding?'与家传理解'+m.minimumUnderstanding:''}`)).join('')+worldSiteActions(v,t.localActions,'transport')+P('个人代步与御物限已知道路的陆路段；远海或界门仍用实际公共班次。两端航栈均实地登记后才能沿既有收费传送路线通行。')+list(t.attunedSceneIds).map(id=>P('本人已登记锚点：'+(sim.WORLD_SCENES?.[id]?.name||'已知航栈'))).join(''));
 html+=list(t.tickets).map(ticket=>C('本人的实际行旅票',S(phase(ticket.status))+P(`${sim.WORLD_SCENES?.[ticket.originSceneId]?.name||'已知出发地'} → ${sim.WORLD_SCENES?.[ticket.destinationSceneId]?.name||'已知目的地'} · 出发世界刻${ticket.departureTick} · 到达世界刻${ticket.arrivalTick}`)+P(`实际旅队${list(ticket.participantIds).length}席 · 已付灵石${ticket.fare}`)+(v.travel?.id===ticket.travelId?B('返回并释放未登乘席位','srWorldCommand',[{action:'return'}])+P('未登乘时可取消并释放席位，已付票价不退；登乘后须实际到港，再购买反向航程。'):''),'ticket-'+ticket.id)).join('');
 return `<details class="sr-world-transport"><summary>舟车班次、代步与御行</summary>${html}</details>`;}
function world(s,sim){const v=call(sim,'viewSRWorld',s);if(!v)return '';let html='';if(v.travel)html+=C('实际行程',S(`${v.travel.routeName} · 尚需${Math.ceil(v.travel.remainingTicks/10)}游戏秒`)+P(v.travel.returnReason)+B('返回/中止行程','srWorldCommand',[{action:'return'}],v.travel.returnAvailable?'':v.travel.returnReason));html+=list(v.destinations).filter(d=>d.known).map(d=>C(d.name,P(`单人主路步行：实际行程${Math.ceil((d.travelDurationTicks||d.durationTicks)/10)}游戏秒 · 候班${Math.ceil((d.waitTicks||0)/10)}游戏秒 · ${cost(d.cost)}`)+list(d.ticketPlans).map(t=>P(`预计班次：出发世界刻${t.departureTick}，到达世界刻${t.arrivalTick}；出发时按实际旅队重新核验。`)).join('')+S(d.reason||'道路已知；出行承担当地风险')+F('srWorldCommandTravel',`<input type="hidden" name="destination" value="${E(d.id)}">`+select('route','路线',[{id:'main',name:'沿主路'},{id:'detour',name:'绕行山路（耗时与费用较高）'}])+select('mode','陆路行旅方式',list(v.transport?.modes).filter(m=>m.acquired&&(m.condition===null||m.condition>.1)).map(m=>({id:m.id,name:m.name})))+travelCargoFields(s)+list(s.homeMemberIds).map(id=>`<label><input type="checkbox" name="companions" value="${E(id)}">邀请${E(s.personsById?.[id]?.name||'门人')}同行（由本人决定）</label>`).join(''),P('上方是单人步行主路预览；出发按绕路、运具与实际同行人数重算耗时和费用，公共票价按人数计。亲自启程会预留有限班次席位；陆路可按实际已走路程掉头，未登乘可取消，公共运具登乘后须到港再返程。'),'确认并亲自启程'),'dest-'+d.id)).join('');if(v.activity)html+=C('当前世界行动',S(`${phase(v.activity.kind)} · ${Math.ceil(v.activity.progressTicks/10)}/${Math.ceil((v.activity.durationTicks||0)/10)}游戏秒`)+B('中止，保留已发生消耗','srWorldCommand',[{action:'cancel'}]));html+=geography(s,sim,v)+transport(s,sim,v)+worldContent(s,sim,v.content);if(v.scene)html+=C(v.scene.name||'当前地点',list(v.scene.contentHints).map(h=>P(h.label)+(h.command?B('亲往取得此传承/材料',h.command,[h.realmId]):h.id?B('当面查验此来源','investigateQuickBreath',[h.id]):'')).join('')+list(v.scene.objects).map(o=>P(o.name||o.label||o.id)+`<div class="button-row">${B('走近该处','srWorldCommand',[{action:'move',x:o.x,y:o.y+o.height/2+1}])}${list(o.choices).map(c=>B(c.label,'srWorldCommand',[{action:'interact',objectId:o.id,choice:c.action}])).join('')}</div>`).join('')+list(v.scene.actors).map(p=>B('查看人物 · '+p.name,'chooseScenePerson',[s.personsById?.[p.personId]?.id??p.personId])).join('')+P('交互需要掌门真实走近；不足条件由活动说明给出。'));
const crises=call(sim,'viewSRCrises',s);if(crises?.preparation){const p=crises.preparation;html+=C('出发前的实际准备',P(p.name+' · '+p.label)+B('走近药师','srWorldCommand',[{action:'move',...p.approachPoint}])+B('提供备绳与行粮','srCrisisCommand',[{action:'supplyRope'}],p.canSupplyRope?'':'需出发前实际会面，先走近药师'));}if(crises?.trapPlan){const t=crises.trapPlan;html+=C('当下脚边的机关',P(t.label)+B('知情布置实际机关','srDanger',['此举真实消耗木石与时间，可能伤害后来者，留下可被发现与追责的痕迹。','srCrisisCommand',[{action:'trap',x:t.x,y:t.y}]]));}html+=list(crises?.known).map(c=>C(c.title,P(c.locationHint||'只有最后获知的位置，需继续寻找')+S(`${c.stageHint||'需查证'} · ${c.remainingEstimate===null?'期限未知':Math.ceil(c.remainingEstimate/10)+'秒'}`)+`<div class="button-row">${c.approachPoint?B('走近已查明位置','srWorldCommand',[{action:'move',...c.approachPoint}]):''}${list(c.actions).map(a=>B(a.label||({treat:'救治',search:'寻找',trap:'布置',breakAnchor:'解除锚点'})[a.action||a.id||a]||a.action||a.id||a,'srCrisisCommand',[{action:a.action||a.id||a,crisisId:c.id}],a.disabled?'先到场搜索并走近当事人':'')).join('')}</div>`,'crisis-'+c.id)).join('');const story=call(sim,'viewSRStory',s);if(story?.canActivateRainChain)html+=C('暴雨后的药路消息',P('雨天药商来讯与药师出行会耗实际时间；可主动了解、查证旧约或暂缓。')+B('雨中听取来讯','srStoryCommand',[{action:'activateRainChain'}],call(sim,'viewWeather',s)?.phase==='rain'?'':'需雨天出现来讯'));if(crises?.treatment)html+=C('当前救治',S(`${Math.ceil(crises.treatment.progressTicks/10)}/${Math.ceil(crises.treatment.durationTicks/10)}游戏秒`)+B('中止救治，保留已耗药材','srCrisisCommand',[{action:'cancel'}]));return html;}
function divination(s,sim,world){
 const v=world?.divination;if(!v)return '';let html='';const budget=v.budget||{};
 const people=[...new Set(list(v.anchorOptions).map(a=>a.personId))];
 if(people.length)html+=C('有锚卜算的实际代价',P(`需炼气${budget.minimumRealm}层、家传听息理解${budget.minimumUnderstanding}和至少${budget.minimumEnergy}精力；每次 ${cost(budget.cost)}、精力${budget.energy}、${budget.durationTicks/10}秒。`)+P('已获锚点与目标按实际联系配对。只给当时的有限范围，不判实时生死；双重息纹会扩大误差，先核对独立来源或亲赴现场反制。'));
 html+=people.map(id=>{const anchors=list(v.anchorOptions).filter(a=>a.personId===id);return C('向'+(anchors[0]?.personName||'已知人物')+'有锚卜算',F('srWorldCommand',`<input type="hidden" name="action" value="divine"><input type="hidden" name="personId" value="${E(id)}">`+select('anchorFactId','与此人实际有关的已获线索',anchors.map(a=>({id:a.factId,name:a.text}))),P('公开代价按上方预算结算；不以无关物证查询陌生人。'),'以相关线索卜算'),'divination-target-'+id);}).join('');
 html+=list(v.observations).map(o=>C('已获得的卜算观测',P(o.text)+S(`世界刻${o.observedTick} · 当时范围约${o.rangeMetres}米${o.errorSignal==='double-trace'?' · 读数存在双重息纹，误差扩大':' · 未见额外重影信号'}`)+P('历史读数保持；后续反制不会改写旧观测，也不会显示当前真坐标。'),'divination-observation-'+o.factId)).join('');
 html+=list(v.countermeasures).map(c=>C('实际反制息纹',P(c.label)+P(`${cost(c.cost)} · ${c.durationTicks/10}秒；需亲自到匠具近旁。`)+(c.position?B('走近已查明匠具','srWorldCommand',[{action:'move',x:c.position.x,y:c.position.y+2}]):B('亲赴已知阵迹所在','srWorldCommand',[{action:'travel',destination:c.sceneId}],s.srWorld.knownScenes.includes(c.sceneId)?'':'先实际获知此路'))+B('现场消解双重息纹','srWorldCommand',[{action:c.command}],!c.active?'阵迹已退，无须重复消耗':!c.position?'先亲自抵达上述地点':'')+P('中止保留已经付出的材料；完成只影响后续读数，仍需独立来源查证。'),'divination-counter-'+c.sourceId)).join('');
 if(['divine','counter-divination'].includes(world?.activity?.kind))html+=C('当前卜算与反制',S(`${phase(world.activity.kind)} · ${Math.ceil(world.activity.progressTicks/10)}/${Math.ceil((world.activity.durationTicks||0)/10)}秒`)+B('中止，保留已耗成本','srWorldCommand',[{action:'cancel'}]));return html;
}
function journal(s,sim){const v=call(sim,'viewSRWorld',s);let html='';const localRecipients=list(v?.scene?.actors).map(p=>({id:p.personId,name:p.name}));
 html+=list(v?.messages).map(m=>{const source=list(v?.scene?.objects).find(o=>o.id===m.sourceId),observed=Number.isSafeInteger(m.observedTick)&&m.observedTick>=0?m.observedTick:'未知',received=Number.isSafeInteger(m.receivedAtTick)&&m.receivedAtTick>=0?m.receivedAtTick:'未知';return C(m.title||'江湖消息',P(m.text||m.statement||m.claim?.text)+P(`来源：${m.speakerName||m.sourceName||'见闻与记录'} · 观察世界刻${observed} · 收到世界刻${received} · ${phase(m.certainty||m.verification||m.status||'unverified')}`)+(source?B('走近当前来源','srWorldCommand',[{action:'move',x:source.x,y:source.y+source.height/2+1}]):'')+B('循来源到场调查','srWorldCommand',[{action:'investigate',sourceId:m.sourceId||m.id}],source?'':'需先到来源所在地点；掌门记忆与口信须寻独立物证')+(m.canShare===true&&localRecipients.length?F('srWorldCommand',`<input type="hidden" name="action" value="share"><input type="hidden" name="claimId" value="${E(m.id)}">`+select('recipientId','向身边人说明所闻',localRecipients),P('须实际会面，耗5秒交流；重复来源不等于独立证据。'),'当面分享消息'):''),'claim-'+m.id);}).join('');
 html+=list(v?.investigations).map(i=>C(i.title||'调查记录',S(i.reason||phase(i.status)||'已保留获知结果'),'investigation-'+i.id)).join('');
 html+=divination(s,sim,v);

 if(v?.reputation)html+=C('地方合作与三层关系',P('传闻、已核实行为、对方利益分别起作用。组织名称不代表个人善恶。')+list(v.reputation.factions).map(f=>P(`${f.name} · 接洽${f.contact} · 诉求${f.request} · 产业${f.industry} · 已知评价${f.reputation}`)).join(''));
const story=call(sim,'viewSRStory',s);if(story){html+=C('旧案与此后',S(story.nextObjective||story.text||story.phase||'循具体事实调查，不凑证据数量')+(!story.completed&&s.story.step>=3?B('继续眼前篇章目标','srStoryCommand',[{action:'advance'}]):'')+list(story.targets).map(p=>P(`${p.name} · ${p.settled?'已核实清算':p.known?'责任已核实':'待调查'} · ${p.locationHint}`)+B('亲赴挑战','srStoryCommand',[{action:'challenge',personId:p.personId}],p.challengeAvailable?'':p.settled?'已清算':p.known?'先实际抵达已知驻地并走近':'先调查可靠来源')).join('')+`<div class="button-row">${B('故地重建','srDanger',['确认故地重建，记录结局后仍可经营。','srStoryCommand',[{action:'ending',choice:'rebuild'}]],story.endingAvailable?'':'核实清算与双亲遗物尚未齐备')}${B('回云岫延续传承','srDanger',['确认回云岫延续传承，记录结局后仍可经营。','srStoryCommand',[{action:'ending',choice:'return'}]],story.endingAvailable?'':'核实清算与双亲遗物尚未齐备')}</div>`);}
return html;}
function cultivation(s,sim){
 const v=call(sim,'viewCultivation',s);if(!v)return '';const b=v.breakthrough,members=list(s.homeMemberIds).map(id=>({id,name:s.personsById?.[id]?.name||'门人'}));
 let html=C('分阶段突破',P(`${sim.realmName?.(b.fromRealm)||b.fromRealm} → ${b.toRealm?sim.realmName?.(b.toRealm)||b.toRealm:'当前境界顶层'}`)+P(`${cost(b.cost)}${b.pillCost?' · 筑基丹'+b.pillCost+'枚':''} · 精力${b.energyCost}`)+P(b.rule)+(b.hazard?P(`${b.hazard.name}：炼化第${list(b.hazard.pulseTicks).map(t=>t/10).join('、')}秒各耗精力${b.hazard.energyPerPulse}，共${list(b.hazard.pulseTicks).length*b.hazard.energyPerPulse}。取消保留已炼化材料和已受灵压，调息后另备真实灵材。`):'')+S(list(b.locks).join('；')||'身体与积累满足，仍需到达静修位置')+B('确认预留并开始突破','srDanger',['开始将预留材料；进入炼化后不退已经消耗的材料，仍可取消并调息恢复。','beginBreakthrough',[]],list(b.locks).join('；')));
 html+=list(v.reliableSources).map(r=>C(r.name,P(`${cost(r.cost)} · ${Math.ceil(r.ticks/10)}游戏秒`)+(r.materialLocation?P(r.materialLocation):'')+B('按此来源准备','reliableFoundation',[r.id]),'foundation-source-'+r.id)).join('');
 html+=list(v.arts).map(a=>C(a.name,P(a.source||'已有可靠来处')+S(`${a.access?'可接触典籍':'尚未取得'} · 理解${a.understanding} · 熟练${a.mastery}${a.main?' · 当前主修':''}`)+P(cost(a.cost))+`<div class="button-row">${B('研习理解','studyArt',[a.id],a.access?'':'先取得典籍')}${a.kind==='main'?B('转修此功体','srDanger',['转修需材料与实际研习时间；已理解知识保留，当前修为按规则衰减。','retrainArt',[a.id]],a.main?'已为主修':''):''}</div>`+(a.canTeach&&members.length?F('teachArt',`<input type="hidden" name="artId" value="${E(a.id)}">`+select('studentId','自愿到场的学习者',members),P('需双方实际入席、理解65与熟练60；耗口粮4及12秒课程。门人可以拒绝。'),'当面商议授业'):''),'sr-art-'+a.id)).join('');
 html+=list(v.orders).map(o=>C('当前研习',S(`${phase(o.kind)} · ${phase(o.phase)} · ${o.reason||'前往实际活动位置'} · ${Math.ceil(o.progressTicks/10)}/${Math.ceil(o.durationTicks/10)}游戏秒`)+B('取消并保留已发生结果','cancelCultivationOrder',[o.id]),'cultivation-order-'+o.id)).join('');
 if(s.story.completed||s.master.realm>=10){const life=v.lifespan;html+=C('八境与有限寿元',P(life?.remainingYears===null?'旧档年龄未知；保留未知，不凭空推算寿尽日期。':`已知年龄${life?.ageYears??'未知'}年 · 剩余${life?.remainingYears??'未知'}年`)+list(v.realms).map(r=>P(`${r.name} · 寿元上限${r.lifespanYears}年 · ${r.condition} · 来源：${r.source}`)).join('')+B('一次延寿灵剂','srDanger',['需灵草60、灵晶12、灵石100与20秒实际炼化；每人仅一次，关闭不衰老。','extendLifespan',[]],life?.extensionUsed?'本次延寿机会已使用':''));}
 if(s.story.completed&&s.master.realm>=10)html+=list(v.highPaths).map(r=>{
 const students=members.filter(p=>!list(r.knownByHomeMembers).includes(p.id));
 const sharing=r.chapterOwned&&students.length?F('inviteHighRealmStudy',`<input type="hidden" name="realmId" value="${E(r.id)}">`+select('personId','邀请返院筑基门人',students),P('共享同一续篇来源；门人自主决定。需口粮4、实际阅卷席与12秒课程，不直接授予境界。'),'邀请实际研习'):'';
 const gifting=list(r.availableMaterialIds).length&&members.length?F('offerHighRealmMaterial',select('itemId','本人携带且未预留的实物',r.availableMaterialIds.map((id,i)=>({id,name:r.materialName+' · 实物'+(i+1)})))+select('personId','当面接收的门人',members),P('双方须同场2.6米且有空，以3秒实际交接同一份灵材；门人可以拒绝，自主决定后续突破。'),'提出实际交接'):'';
 return C(r.name,P(`${r.condition} · 来源：${sim.WORLD_SCENES?.[r.sceneId]?.name||'有偿航路对应港口'}`)+P(`研取续篇 ${cost(r.chapterCost)}，${r.chapterTicks/10}秒；取得${r.materialName} ${cost(r.materialCost)}，${r.materialTicks/10}秒。`)+S(`${r.chapterOwned?'续篇已研习':'续篇尚未取得'} · ${r.materialOwned?'有本人突破灵材':'尚未持有突破灵材'}${r.sourceRemaining===null?'':' · 此来源余'+r.sourceRemaining+'份'}`)+P(r.recovery)+(r.hazard?P(`${r.hazard.name}：实际三次灵压各耗精力${r.hazard.energyPerPulse}；开始前至少准备${Math.max(r.id==='great-vehicle'?70:0,35+3*r.hazard.energyPerPulse)}精力，炼化后可取消调息。`):'')+B('亲赴可靠来源','srWorldCommand',[{action:'travel',destination:r.sceneId}],s.srWorld.knownScenes.includes(r.sceneId)?s.master.location?.sceneId===r.sceneId?'已在此处':'' : '先实查洲图，登记有偿航路')+B('在档案处实际研取续篇','acquireHighRealmChapter',[r.id],r.chapterOwned?'续篇已取得':s.master.location?.sceneId===r.sceneId?'':'先亲自抵达对应港口并走近档案')+B('在登记矿料处取得实物','acquireHighRealmMaterial',[r.id],!r.chapterOwned?'先真实研取续篇':s.master.location?.sceneId===r.sceneId?'':'先亲自抵达对应港口并走近登记矿料')+sharing+gifting,'sr-high-path-'+r.id);
 }).join('');
 if(v.soulExtension?.enabled&&(s.master.realm>=16||list(v.retainedSouls).length||list(v.eligibleSouls).length)){
 html+=C('特殊魂魄留存',P('死亡事实持续，留存不等于复活。普通魂魄在120秒内逐渐消散；留存需元婴、阵术理解60、到遗体近旁，灵晶12与灵草40，实际12秒。')+list(v.eligibleSouls).map(p=>B('知情留存'+p.name,'srDanger',['保护可持续360秒，此人不会复活；需要到达遗体近旁并完成实际仪式。','retainSoul',[p.personId,true]])).join('')+list(v.retainedSouls).map(x=>P(`${x.name||s.personsById?.[x.originPersonId]?.name||'已知亡者'} · ${phase(x.status)} · ${Math.max(0,Math.ceil((x.expiresAtTick-s.worldTick)/10))}秒保护期限`)+B('知情解除保护','srDanger',['解除后魂魄继续消散，死亡记录不变。','releaseRetainedSoul',[x.originPersonId]],x.status==='retained'?'':'当前不在保护期')).join(''));
 }
 if(s.master.realm>=19||list(v.avatars).length)html+=C('化身与神魂反馈',P('形成需化神、灵石200、灵晶30、灵草20与18秒；损毁反馈本体伤势与神魂损失，主动收回需3秒。')+B('知情形成有限化身','srDanger',['化身并非替身免死；损毁将反噬本体15伤势、10精力及10%当前修为。','createAvatar',[true]])+list(v.avatars).map(x=>{
 const e=x.expedition,busy=e&&['outbound','walking','observing','blocked','returning'].includes(e.phase),local=x.position?.kind==='scene';
 const progress=e?.phase==='observing'?` · 现场查验${Math.ceil((e.observationTicks||0)/10)}/6秒`:e?.phase==='returning'&&Number.isFinite(e.returnTicksRemaining)?` · 返回尚需${Math.ceil(e.returnTicksRemaining/10)}秒`:e?.travel?.durationTicks?` · 行程${Math.ceil((e.travel.progressTicks||0)/10)}/${Math.ceil(e.travel.durationTicks/10)}秒`:'';
 const routes=x.status==='active'&&!busy?`<details><summary>提供化身实际探察机会</summary>${P('须本体与闲置化身同地近旁确认出发预算，沿已知道路付真实运费与时间；仅查验公开物件，不代本体救人、领奖或得知人物实时生死。')}${list(v.avatarDestinations).filter(d=>d.id!==x.position?.sceneId&&list(d.objects).length).map(d=>C(d.name,F('sendAvatarExplore',`<input type="hidden" name="avatarId" value="${E(x.id)}"><input type="hidden" name="destination" value="${E(d.id)}">`+select('objectId','要实际查验的公开物件',d.objects),'<label><input type="checkbox" name="informed" required>已知真实行程、运费与损毁反馈，自愿确认。</label>','确认化身亲赴此处'),'avatar-destination-'+x.id+'-'+d.id)).join('')}</details>`:'';
 return C('本人的有限化身',P(`${phase(x.status)} · 化身生命${x.hp}/${x.maxHp}`)+P(x.status==='returned'?'当前化身已收回，不再提供现场活动。':x.status==='destroyed'?'当前化身已损毁，实际反馈与历史保留。':x.status==='returning'?'正在实际收束，期间仍可能受损。':local?'实际位置：'+(sim.WORLD_SCENES?.[x.position.sceneId]?.name||'已知地点')+'（'+x.position.x+'，'+x.position.y+'米）':'化身正在实际行程中；本体位置保持。')+(e?S(`${phase(e.phase)}${progress} · ${e.reason||'按共同世界时间推进实际观察'}`):'')+(e?.travel?.cost?P('已付行程成本：'+cost(e.travel.cost)):'')+routes+(x.status==='active'&&e&&['outbound','walking','observing','blocked'].includes(e.phase)?B('中止实际探察','cancelAvatarExplore',[x.id])+P('赶路中沿已行路线返回且运费不退；到场后就地中止，取消不生成观察事实。'):'')+B('实际收回化身','recallAvatar',[x.id],x.status==='active'?'':'当前不能再次收回'),'sr-avatar-'+x.id);
 }).join(''));

 return html;
}
function alchemy(s,sim){const v=call(sim,'viewEconomy',s),recipes=list(v?.craftRecipes);let html=C('实际开炉炼药',P('药草、灵晶与木石先实际搬至丹炉缓存；灵石和知识由公库预算承担。掌门到场用同一工位制作，取消保留已实际消耗。')+recipes.map(r=>P(`${r.name} · 成丹留在实际药炉，取用需到场 · ${cost(r.cost)} · ${r.durationTicks/10}游戏秒`)+S(list(r.reasons).join('；')||'丹炉、物料与本人条件具备')+B('炼制'+r.name,'craftSR',[r.id],list(r.reasons).join('；'))).join(''));if(v?.craft){const w=v.craft;html+=C('当前实际炉次',P(sim.RECIPES?.[w.recipeId]?.name||'丹药')+S(`${phase(w.phase)} · ${Math.ceil(w.progressTicks/10)}/${Math.ceil(w.durationTicks/10)}游戏秒`)+P('材料在原位置库存预留，实际工序按进度消耗；不因查阅自动完成。')+B('取消并退未发生工序的料','cancelCraftSR'));}return `<div data-sr-production="alchemy">${html}</div>`;}
function persons(s,sim){const people=call(sim,'viewPersons',s);if(!people)return '';return list(people).filter(p=>p.personId!=='person:master').map(p=>C(p.name,S(p.schedule?.reason||'自行权衡生活与修行')+P(`本次承诺尚余${Math.max(0,Math.ceil(((p.schedule?.commitUntilTick??0)-s.worldTick)/10))}游戏秒`)+F('inviteWork',`<input type="hidden" name="personId" value="${E(p.personId)}">`+select('buildingId','提供差事机会',list(s.buildings).filter(b=>sim.BUILDINGS?.[b.type]?.work).map(b=>({id:b.instanceId,name:sim.BUILDINGS[b.type].name}))),P('邀请由本人决定，拒绝与道路/材料阻塞分开。'),'商议差事'),'sr-person-'+p.personId)).join('');}
function spatial(s,sim){
 if(!sim.spatialEnabled?.(s))return '';const state=call(sim,'viewSpatial',s),units=buildingGridEnabled(s),step=units?BUILDING_GRID.metres:.5;
 const types=Object.entries(sim.BUILDINGS||sim.TYPES||{}).map(([id,d])=>({id,name:d.name+(units?' · '+buildingCellLabel(id):'')}));
 const coords=(x,y)=>`${units?'<input type="hidden" name="coordinateUnit" value="cell">':''}<div class="sr-inline">`+input('x','起始列',{type:'number',value:units?x/step+1:x,min:units?2:1,max:units?31:56,step:units?1:.5})+input('y','起始行',{type:'number',value:units?y/step+1:y,min:units?2:1,max:units?31:56,step:units?1:.5})+'</div>';
 let html=C('自由营造',P(units?'选择建筑与起始单位格；设施占整片格子，入口另留通行空地。材料先预留，掌门实际到场后施工，铺路暂缓。':'选择建筑与半米坐标，南向入口自动校验。建造预留材料，掌门到场后施工。')+F('build',select('type','建筑',types)+coords(10,20),'','在此建立施工计划'));
 if(state)html+=C('当前施工',S(`${phase(state.stage)} · ${state.label} · ${Math.round((state.progress||0)*100)}%`)+B('取消施工，按阶段退料','cancelConstruction'));
 html+=list(s.buildings).map(b=>C((sim.BUILDINGS||sim.TYPES)?.[b.type]?.name||b.type,P(`第${b.level}级 · ${units?buildingCellLabel(b.type,b.level):'('+b.transform.x+', '+b.transform.y+')米'}`)+B('升级实际建筑','upgrade',[b.id])+B('迁建选址','relocate',[b.id],b.type==='hall'?'主屋固定在旧址':'')+(b.type==='hall'?'':B('查看拆除影响','demolishConfirm',[b.id])),'sr-building-'+b.id)).join('');return html;
}
function combat(s,sim){const v=call(sim,'viewSRCombat',s);if(!v)return '';let html=C('起手与收势',S(v.pending?`${phase(v.pending.phase)} · ${v.pending.reason}`:'审势行动；暂停可规划，恢复后按实际时序执行')+(v.pending?B('取消尚未执行动作','cancelSRCombatAction'):''));html+=list(v.actions).map(a=>C(a.name,P(`起手${a.windup/10}秒 · 收势${a.recovery/10}秒 · 灵力${a.qi} · 范围${a.range??'自身'}米`)+P(a.role||'按实际位置、遮挡与资源结算')+B('执行'+a.name,'srCombatAction',[a.id,a.id==='ward-node'?{x:s.combat.player.x,y:s.combat.player.y}:null],a.disabled?a.reason:'')+S(a.reason||'动作条件满足'),'sr-combat-'+a.id)).join('');html+=C('自愿同行战术',P('同行者按出发约定、意愿与伤势自主执行。')+`<div class="button-row">${list(v.tactics).map(t=>B(({outbound:'实际赶路',walking:'现场行走',observing:'现场查验',recalled:'已收束观察','counter-divination':'现场消解息纹',content:'现场文书与交付',divine:'有锚卜算',investigate:'现场查证',walk:'实际行走',interact:'现场交互',guard:'护卫',focus:'协同压制',rally:'集结',retreat:'撤离'})[t],'setCombatTactic',[t])).join('')}</div>`+F('srCombatAction',input('x','战场横坐标',{type:'number',value:s.combat.player.x,min:.4,max:11.6,step:.1})+input('y','战场纵坐标',{type:'number',value:s.combat.player.y,min:.4,max:7.6,step:.1}),'','移动至此处'));return html;}
function organization(s,sim){const v=call(sim,'viewOrganization',s);if(!v?.enabled)return '';const people=call(sim,'viewPersons',s)||[];let html=C(v.formal?v.name:'共同立派',P(cost(v.founding.cost))+S(list(v.founding.reasons).join('；')||'人手、传承与供给已具备')+(v.formal?'':F('foundSectSR',input('name','拟定门派名',{value:s.sect.name||'云岫仙府'}),'','确认举行立派仪式')));html+=C('院规与传播',Object.entries(v.policyOptions||{}).map(([key,values])=>F('policySR',`<input type="hidden" name="key" value="${E(key)}">`+select('value',({pillRule:'丹药取用',outingRule:'外出规则',workFocus:'差事侧重',enforcement:'执规原则'})[key]||key,values,s.doctrine?.[key]),P('新规生效与知晓分别记录，不追溯惩罚此前行为。'),'公布此项院规')).join(''));html+=C('邀请自愿任职',F('inviteOfficeSR',select('personId','人选',list(people).filter(p=>p.personId!=='person:master').map(p=>({id:p.personId,name:p.name})))+select('role','职责',[{id:'steward',name:'执事'},{id:'teacher',name:'传法'},{id:'warden',name:'执规'}]),P('有明确任期与报酬，不会永久控制本人。'),'当面商议')+Object.entries(v.offices).map(([role,o])=>P(`${s.personsById?.[o.personId]?.name||'任职者'} · ${role} · ${o.status}`)+B('结束本次任职','resignOffice',[o.personId,role])).join(''));html+=list(v.peaks).map(p=>C(p.name,S(list(p.reasons).join('；')||'用途与主持人已具备')+P(cost(p.cost))+F('foundPeakSR',`<input type="hidden" name="direction" value="${E(p.direction)}">`+select('hostId','自愿主持人',list(p.hosts).filter(h=>h.willing).map(h=>({id:h.personId,name:h.name})))+input('name','峰名',{value:p.name}),'','共同设立峰域'),'sr-peak-'+p.direction)).join('');html+=list(v.caseCandidates).map(c=>C('按已获证据查明责任',F('knowCase',`<input type="hidden" name="factId" value="${E(c.factId)}">`+select('evidenceFactId','同案已知证据',list(c.evidence).map(f=>({id:f.id,name:f.text}))),P('只据已获证据核实实际行为，传闻与门类标签不作凭证。'),'记录已核实的行为'),'sr-candidate-'+c.factId)).join('');html+=list(v.cases).map(c=>C('已核实行为',S(c.reason)+P(`实际损害 ${c.damage??'已记录'}；失控与主动修炼禁忌分开认定。`)+B('公布普通赏令','publishBounty',[c.factId,'normal'])+B('公布紧急赏令','srDanger',['紧急赏令需要更高预算，传播后由愿意的人接取；只能针对已核实行为。','publishBounty',[c.factId,'urgent']]),'sr-case-'+c.factId)).join('');html+=list(v.bounties).map(b=>C('公开赏令',P(`${s.personsById?.[b.targetId]?.name||'已核实目标'} · 悬赏${b.reward}灵石`)+S(phase(b.phase))+B('掌门接取','acceptBounty',[b.id,'person:master'])+(list(b.proofCandidates).length?F('redeemBounty',`<input type="hidden" name="id" value="${E(b.id)}">`+select('proofFactId','同目标实际行动凭证',b.proofCandidates.map(f=>({id:f.id,name:f.text}))),P('已发生且合法的行动才能兑付；同一凭证不能重复领取。'),'查验凭证并兑付'):'')+(list(b.correctionCandidates).length?F('correctBounty',`<input type="hidden" name="id" value="${E(b.id)}">`+select('correctionFactId','同案已知纠错证据',b.correctionCandidates.map(f=>({id:f.id,name:f.text}))),P('纠正此前赏令；已发生损害与人物记忆不会撤销。'),'按证据纠正赏令'):''),'sr-bounty-'+b.id)).join('');const weather=call(sim,'viewWeather',s);if(weather)html+=C('天气与院中排水',S(weather.label||weather.phase)+P(`积水${weather.wetness??0} · 排水${weather.drainage??0}`)+P('需青石12、灵木8；掌门亲自在场施工10游戏秒，取消按进度保留已耗材料。')+B('投入材料改善排水','improveDrainage')+B('取消排水施工','cancelDrainage'));return html;}
function covenants(s,sim){const v=call(sim,'viewCovenants',s);if(!v)return '';const people=call(sim,'viewPersons',s)||[];let html=C('会面、知情与誓约',P(v.rule)+Object.entries(v.modes).map(([id,m])=>P(`${m.name}：${cost(m.cost)}；违约伤势${m.backlashWound}，持续${m.recoveryTicks/10}游戏秒。`)).join('')+Object.entries(v.templates).map(([id,t])=>C(t.name,P(`条款：${t.quantity}份${names[t.resource]||t.resource}，在${t.deadlineTicks/10}游戏秒内实际交付；一次客观延期${t.graceTicks/10}秒。解除代价${cost(t.releaseCost)}，需${t.releaseTicks/10}秒。`)+F('formCovenant',`<input type="hidden" name="templateId" value="${E(id)}">`+select('mode','约束方式',Object.entries(v.modes).map(([id,m])=>({id,name:m.name})))+select('counterpartyId','实际会面的对象',list(people).filter(p=>p.personId!=='person:master').map(p=>({id:p.personId,name:p.name}))),'<label><input type="checkbox" name="informed" required>已阅读期限、材料、违约伤势与协商解除代价，自愿确认。</label>','提出签署'),'sr-covenant-template-'+id)).join(''));html+=list(v.records).map(c=>C(c.terms.name,S(`${phase(c.phase)} · 已交${c.delivered}/${c.terms.quantity} · ${c.deadlineTick===null?'尚未签成':Math.max(0,Math.ceil((c.deadlineTick-s.worldTick)/10))+'秒到期'}`)+`<div class="button-row">${B('实际交付','deliverCovenant',[c.id])}${B('当面商议解除','releaseCovenant',[c.id])}${B('确因道路阻断申请延期','extendCovenant',[c.id,'road-blocked'])}${B('确因伤势申请延期','extendCovenant',[c.id,'injury'])}${B('明知而违约','srDanger',['明知拒交将产生已说明的关系/伤势后果；这不是取消未签成的操作。','breachCovenant',[c.id,true]])}</div>`,'sr-covenant-'+c.id)).join('');html+=list(v.orders).map(o=>C('签署与履约过程',S(`${phase(o.kind)} · ${phase(o.phase)} · ${o.progressTicks/10}/${o.durationTicks/10}秒`)+B('取消尚未实际履约的操作','cancelCovenantOrder',[o.id]),'sr-covenant-order-'+o.id)).join('');return html;}
function mother(s,sim){const v=call(sim,'viewMotherChain',s);if(!v)return '';let html=C(v.name,P(v.benefit)+P(v.warning)+S(v.link?`已内化版本 · ${phase(v.link.status)}${v.knownHolder?' · 已核实相关持有者'+v.knownHolder:''}`:'尚未研习，不会因为阅读而扣费或内化')+(!v.link?F('learnQuickBreath','<label><input type="checkbox" name="informed" required>已读增益与未知通路风险，自愿研习。</label>','','确认研习此缺页法'):''));html+=C('独立查证与安全校勘',list(v.knownClues).map(c=>P(({"independent-copy":'取得独立抄本',"old-patient":'查访旧修习者'})[c]||c)).join('')+Object.entries(v.clueSites||{}).map(([id,t])=>P(t.label+'；须真实抵达后近处查验。')+(s.master.location?.sceneId===t.sceneId?B('走近查验位置','srWorldCommand',[{action:'move',x:t.x,y:t.y+t.height/2+1}]):B('先亲赴此地','srWorldCommand',[{action:'travel',destination:t.sceneId}],s.srWorld.knownScenes.includes(t.sceneId)?'':'需先获得该地点位置'))+B('当面查验来源','investigateQuickBreath',[id],s.master.location?.sceneId===t.sceneId?'':'先抵达上述地点')).join('')+P(`校勘需要 ${cost(v.counters.collate.cost)}，${v.counters.collate.ticks/10}秒。`)+B('按已获线索校勘','collateQuickBreath'));html+=list(v.crises).map(c=>C('已感知的异常抽取',S(`${phase(c.phase)} · 已损失${c.lost}/${c.cap} · ${c.reason}`)+P(c.conclusion||'此时可以以已掌握的知识采取反制')+P(`短暂断流${cost(v.counters.cut.cost)}、精力${v.counters.cut.energy}、${v.counters.cut.ticks/10}秒；破锚需${cost(v.counters.break.cost)}、亲赴石桥。`)+B('短暂断流争取窗口','cutMotherFlow',[c.id])+(v.anchor?P('已知锚点：石桥（'+v.anchor.x+'，'+v.anchor.y+'米）')+(s.master.location?.sceneId===v.anchor.sceneId?B('走近已知锚点','srWorldCommand',[{action:'move',x:v.anchor.x,y:v.anchor.y}]):B('亲赴石桥','srWorldCommand',[{action:'travel',destination:v.anchor.sceneId}])):'')+B('在石桥实际破锚','breakMotherAnchor',['person:master'],v.anchor?'':'先取得独立查证线索'),'sr-mother-crisis-'+c.id)).join('');html+=list(v.orders).map(o=>C('校勘与反制进度',S(`${phase(o.phase)} · ${o.reason||'按实际位置与世界时序推进'} · ${Math.ceil(o.progressTicks/10)}/${Math.ceil(o.durationTicks/10)}秒`),'sr-mother-order-'+o.id)).join('');return html;}
export function renderSRPanel(s,sim,tab){if(!sim.srEnabled?.(s)||!s.srWorld)return '';let body='';if(tab==='self'){body=equipment(s,sim)+cultivation(s,sim);const a=s.activitiesById[s.master.activityId];if(a?.kind==='sr-harvest')body=C('当前实际采集',S(`${Math.ceil(a.progressTicks/10)}/${Math.ceil(a.durationTicks/10)}游戏秒 · ${a.reason||'在场采集有限来源'}`)+B('取消采集，保留已发生消耗','cancelMasterHarvest'))+body;}if(tab==='manuals')body=cultivation(s,sim)+mother(s,sim);if(tab==='disciples')body=persons(s,sim);if(tab==='build')body=spatial(s,sim);if(tab==='production')body=economy(s,sim)+alchemy(s,sim)+lateEconomy(s,sim);if(tab==='explore')body=world(s,sim)+combat(s,sim)+descent(s,sim)+aftermath(s,sim);if(tab==='sect')body=organization(s,sim)+covenants(s,sim);if(tab==='journal')body=journal(s,sim);return body?`${s.story?.onboarding&&s.story.step<4?'<details class="sr-opening-options"><summary>更多可选操作与后续准备</summary>':''}<section class="sr-workflows"><h3>${E(({self:'装备与修行',manuals:'研习与真实掌握',disciples:'日程与自愿差事',build:'单位格与施工',production:'实际库存与物流',explore:'山路、地点与救援',sect:'组织、门规与履约',journal:'消息、调查与旧案'})[tab])}</h3><div class="sr-grid">${body}</div><p class="ui-note">活动由共同世界时间推进；保存与取消沿用当前档位，后台和关闭不补推进。</p></section>${s.story?.onboarding&&s.story.step<4?'</details>':''}`:'';}
export function dialogueSettings(status){return `<details class="sr-workflows"><summary>可选对白表达（当前${status.enabled?'开启':'关闭'}）</summary><article class="sr-card" data-key="sr-ai"><p>基础玩法完整，无需联网。服务只选择已审措辞；当前${status.enabled?'开启':'关闭'}。临时密钥和配置不进入存档，刷新后需重新填写。</p><p>使用自己的服务可能产生费用；请求次数上限不是货币费用上限。剩余${status.remaining}次/本次会话，最多一个请求在途。</p>${F('dialogueConfig',input('endpoint','HTTPS chat-completions完整地址',{value:status.endpoint,type:'url'})+input('model','服务模型',{value:status.model})+input('key',status.keyPresent?'临时密钥（已有；留空保留）':'临时密钥（仅当前会话）',{type:'password'})+input('budget','本次会话请求次数上限',{type:'number',value:status.budget,min:0,max:100,step:1}),'<label><input name="enabled" type="checkbox"'+(status.enabled?' checked':'')+'>主动开启可选表达</label>','应用服务设置')}<div class="button-row">${B('试读问候','dialogueGreet')}${B('关闭并取消请求','dialogueDisable')}${B('清除临时密钥','dialogueClear')}</div><p id="sr-ai-response" class="sr-ai-status" role="status">本地问候：愿君今日安好。</p></article></details>`;}
export function srFormArguments(command,values){
 const num=name=>{if(values[name]===undefined||String(values[name]).trim()==='')throw new Error('请填写完整数字后再确认。');const n=Number(values[name]);if(!Number.isFinite(n))throw new Error('请输入有效数字。');return n;};
 if(command==='learnQuickBreath'){if(values.informed!=='on')throw new Error('请阅读风险，再自愿确认。');return [true];}
 if(command==='formCovenant'){if(values.informed!=='on')throw new Error('请先阅读具体条款与代价，再自愿确认。');return [values.mode,values.templateId,values.counterpartyId,true];}
 if(command==='foundSectSR')return [values.name];
 if(command==='policySR')return [values.key,values.value];
 if(command==='inviteOfficeSR')return [values.personId,values.role];
 if(command==='foundPeakSR')return [values.direction,values.hostId,values.name];
 if(command==='srCombatAction')return ['move',{x:num('x'),y:num('y')}];
 if(command==='inviteWork')return [values.personId,values.buildingId];
 if(command==='build')return [values.type,...['x','y'].map(k=>values.coordinateUnit==='cell'?(num(k)-1)*BUILDING_GRID.metres:num(k))];
 if(command==='relocate')return [num('id'),...['x','y'].map(k=>values.coordinateUnit==='cell'?(num(k)-1)*BUILDING_GRID.metres:num(k))];
 if(command==='startTransport')return [values.sourceId,values.targetId,values.carrierId||'person:master',{[values.resource]:num('amount')}];
 if(command==='transferProperty')return [values.sourceId,values.targetId,values.resource,num('quantity'),'gift'];
 if(command==='redeemBounty')return [values.id,values.proofFactId];
 if(command==='correctBounty')return [values.id,values.correctionFactId];
 if(command==='knowCase')return [values.factId,[values.evidenceFactId]];
 if(command==='giftEquipment')return [values.id,values.recipientId];
 if(command==='teachArt')return [values.artId,values.studentId];
 if(command==='inviteHighRealmStudy')return [values.personId,values.realmId];
 if(command==='offerHighRealmMaterial')return [values.itemId,values.personId];
 if(command==='sendAvatarExplore'){if(values.informed!=='on')throw new Error('请先阅读实际行程与化身损毁反馈，再自愿确认。');return [values.avatarId,values.destination,values.objectId,true];}
 if(command==='craftPill')return [values.recipeId];
 if(command==='retainSoul'){if(values.informed!=='on')throw new Error('请先阅读留存期限和代价，再自愿确认。');return [values.personId,true];}
 if(command==='lendEquipment')return [values.id,values.borrowerId,num('durationTicks')];
 if(command==='srWorldCommandTravel'){const cargo=Object.fromEntries(Object.entries(values).filter(([key])=>key.startsWith('cargo_')).map(([key,value])=>[key.slice(6),Number(value)]));return [{action:'travel',destination:values.destination,route:values.route,...(values.mode?{mode:values.mode}:{}),companions:values.companions||[],...(Object.keys(cargo).length?{cargo}:{})}];}
 if(command==='srWorldCommand')return [{...values}];
 if(command==='srCrisisCommand')return [{...values,...(values.x!==undefined?{x:num('x'),y:num('y')}:{})}];
 throw new Error('未知操作表单，请重新打开当前系统。');
}
