import{attachMapInput}from'./map-input.mjs';
import{TYPES,RESOURCE,CELLS,initial,canPay,capacity,upgradeCost,build,assign,upgrade,recruit,breakthrough,tick,rates,QUESTS,claim,validateSave,addLog,buildingLock,isAway,demolish}from'./living-world.mjs';
import{createExpansion}from'./expansion.mjs';
import{createPersistence}from'./persistence.mjs';
import{renderCommunity}from'./community.mjs';
const persistence=createPersistence(()=>localStorage,validateSave);
const restored=persistence.load();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let state=restored||initial(),tab='build',selected=1,building=null,hover=null,showGrid=false,toastTimer,lastTime=0,uiTime=0,assetsReady=false,zoom=1,pan={x:0,y:0},modalOpen=false,renderKey='';
const canvas=$('#world'),ctx=canvas.getContext('2d'),imgs={};
let expansion;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const icons={jade:'◇',wood:'♧',stone:'▱',herb:'❧',crystal:'◈',insight:'☷'};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>Math.floor(n).toLocaleString('zh-CN');
const cost=c=>Object.entries(c).map(([k,v])=>`${icons[k]} ${v}`).join('　');
const reward=c=>Object.entries(c).map(([k,v])=>`${RESOURCE[k]} +${v}`).join(' · ');
const spriteStyle=i=>i<6?`background-position:${(i%3)*50}% ${Math.floor(i/3)*100}%`:`background-image:url('./assets/newbuildings.png');background-size:300% 100%;background-position:${(i-6)*50}% 0`;
const day=t=>`第 ${Math.floor(t/120)+1} 日`;
function toast(s){if(modalOpen){let note=$('#modal-feedback');if(!note){note=document.createElement('p');note.id='modal-feedback';note.setAttribute('role','status');$('#modal-body').append(note);}note.textContent=s;}$('#toast').textContent=s;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),3500);}
function mutate(fn){try{const r=fn();render(true);return r;}catch(e){toast(e.message);return null;}}
function openModal(title,html){$('#modal-title').textContent=title;$('#modal-body').innerHTML=html;modalOpen=true;$('#modal').showModal();}
function saveProgress(replace=false){persistence.save(state,{replace});$('#save-status').textContent=persistence.status;}
function closeModal(){modalOpen=false;$('#modal').close();saveProgress();}
$('#close-modal').onclick=closeModal;$('#modal').addEventListener('close',()=>{modalOpen=false;});
function screen(){const w=canvas.clientWidth,h=canvas.clientHeight;const mobile=w<760;const base=mobile?Math.max(w/1160,h/1024):Math.max(w/1536,h/1024);return{w,h,scale:base*zoom,ox:w/2+pan.x-(mobile?700:810)*base*zoom,oy:(h-(mobile?150:130))/2+pan.y-465*base*zoom};}
function tilePos(x,y){return {x:750+(x-y)*61,y:290+(x+y)*31};}
function tileAt(x,y){const a=(x-750)/61,b=(y-290)/31;return{x:Math.round((a+b)/2),y:Math.round((b-a)/2)};}
function pointerPos(e){const r=canvas.getBoundingClientRect(),s=screen();return{x:(e.clientX-r.left-s.ox)/s.scale,y:(e.clientY-r.top-s.oy)/s.scale};}
function diamond(x,y,fill,stroke){const p=tilePos(x,y);ctx.beginPath();ctx.moveTo(p.x,p.y-31);ctx.lineTo(p.x+61,p.y);ctx.lineTo(p.x,p.y+31);ctx.lineTo(p.x-61,p.y);ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.1;ctx.stroke();}}
function buildingSprite(b,alpha=1){const p=tilePos(b.x,b.y),i=TYPES[b.type].sprite,im=i<6?imgs.buildings:imgs.newbuildings;if(!im)return;const sw=im.width/3,sh=i<6?im.height/2:im.height;const width=b.type==='hall'?157:133;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(im,(i%3)*sw,i<6?Math.floor(i/3)*sh:0,sw,sh,p.x-width/2,p.y-width+24,width,width);ctx.restore();}
function pill(text,x,y,bg='#f4f5e6ee',fg='#365540'){ctx.font='12px "Microsoft YaHei",sans-serif';const w=ctx.measureText(text).width+20;ctx.fillStyle=bg;ctx.beginPath();ctx.roundRect(x-w/2,y-10,w,21,3);ctx.fill();ctx.strokeStyle='#829c6550';ctx.lineWidth=.6;ctx.stroke();ctx.fillStyle=fg;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x,y+1);}
function draw(now){if(!assetsReady)return;const s=screen();ctx.setTransform(Math.min(devicePixelRatio,1.5),0,0,Math.min(devicePixelRatio,1.5),0,0);ctx.clearRect(0,0,s.w,s.h);ctx.fillStyle='#bdd7d0';ctx.fillRect(0,0,s.w,s.h);ctx.translate(s.ox,s.oy);ctx.scale(s.scale,s.scale);ctx.drawImage(imgs[expansion?.scene()||'map']||imgs.map,0,0,1536,1024);if(expansion&&expansion.scene()!=='map'){expansion.draw(ctx,now);return;}
 if(showGrid||building){for(const c of CELLS){const occupied=state.buildings.some(b=>b.x===c.x&&b.y===c.y);diamond(c.x,c.y,occupied?'#365d4a12':'#e8f2c50a',occupied?'#365d4a44':'#faf6c475');}}
 if(selected&&!building){const b=state.buildings.find(b=>b.id===selected);if(b)diamond(b.x,b.y,'#f5ecac35','#d8be6c');}
 if(building&&hover){const good=CELLS.some(c=>c.x===hover.x&&c.y===hover.y)&&!state.buildings.some(b=>b.x===hover.x&&b.y===hover.y)&&canPay(state,TYPES[building].cost);diamond(hover.x,hover.y,good?'#a7e5ba66':'#d3886b66',good?'#d9f3b5':'#a95338');buildingSprite({type:building,...hover},.62);}
 const sprites=state.buildings.map(b=>({kind:'building',y:tilePos(b.x,b.y).y,b}));for(const d of state.disciples){if(isAway(state,d.id))continue;const dest=state.buildings.find(b=>b.id===d.job)||state.buildings[0],p=tilePos(dest.x,dest.y);const phase=state.time*.17+d.id*2.2;const walk=!reduced&&(d.job===null||!['hall','meditation'].includes(dest.type));const x=p.x+42+(walk?Math.sin(phase)*20:0),y=p.y+18+(walk?Math.cos(phase)*10:0);sprites.push({kind:'disciple',y,d,x});}
 sprites.sort((a,b)=>a.y-b.y);for(const o of sprites){if(o.kind==='building')buildingSprite(o.b);else{const sw=imgs.disciples.width/4;ctx.save();ctx.globalAlpha=.16;ctx.fillStyle='#193e28';ctx.beginPath();ctx.ellipse(o.x,o.y,11,5,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.drawImage(imgs.disciples,o.d.portrait*sw,0,sw,imgs.disciples.height,o.x-16,o.y-42,32,45);}}
 for(const b of state.buildings){const p=tilePos(b.x,b.y),d=state.disciples.find(d=>d.job===b.id),t=TYPES[b.type];pill(`${t.name} · ${b.level}级`,p.x,p.y+33,b.id===selected?'#345d48f2':'#f5f6e6ed',b.id===selected?'#fcf4d1':'#42614c');if(t.work&&!d)pill('待派遣',p.x,p.y+53,'#f4ebd7ed','#a27e43');else if(Object.keys(t.out).length){ctx.fillStyle='#45634866';ctx.fillRect(p.x-27,p.y+49,54,3);ctx.fillStyle='#e2d59a';ctx.fillRect(p.x-27,p.y+49,54*b.progress/t.duration,3);}else if(b.type==='meditation'&&d)pill(`修炼中 ${Math.floor(d.xp)}/${d.realm*100}`,p.x,p.y+53,'#e7f2e1ea','#5f8b71');}
 if(!reduced){ctx.fillStyle='#fffadf';for(let i=0;i<15;i++){const x=250+((i*137+now*.004)%950),y=310+(i*61)%350+Math.sin(now*.001+i)*8;ctx.globalAlpha=.3+.2*Math.sin(now*.002+i);ctx.beginPath();ctx.arc(x,y,1.5,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}}
function resize(){canvas.width=canvas.clientWidth*Math.min(devicePixelRatio,1.5);canvas.height=canvas.clientHeight*Math.min(devicePixelRatio,1.5);draw(performance.now());}new ResizeObserver(resize).observe(canvas);
function render(force=false){const rr=rates(state);$('#resources').innerHTML=Object.entries(RESOURCE).map(([k,name])=>`<div class="resource" title="${name}：每 20 秒产出 ${rr[k].toFixed(1)}"><span class="resource-icon">${icons[k]}</span><div><div class="resource-top"><span class="resource-value">${num(state.resources[k])}</span><span class="resource-name">${name}</span></div><div class="resource-rate">+${rr[k].toFixed(1)} / 20秒</div></div></div>`).join('');$('#game-date').textContent=`${day(state.time)} · ${['辰时','巳时','午时','未时','申时','酉时'][Math.floor(state.time/20)%6]}`;$('#status-time').textContent=state.speed?`时光流转 · ${state.speed} 倍速`:'时光暂歇';$('#pause').textContent=state.speed?'Ⅱ':'▷';$('#pause').setAttribute('aria-label',state.speed?'暂停游戏':'继续游戏');$$('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===state.speed));$('#disciple-count').textContent=state.disciples.length;$('#bottom-summary').textContent=tab==='build'?`已营造 ${state.buildings.length} 座 · 选择建筑后点击空地`:tab==='disciples'?`弟子 ${state.disciples.length} / ${capacity(state)} · 闲暇 ${state.disciples.filter(d=>d.job===null).length} 人`:'山中岁月，皆有回响';
 const q=QUESTS.find(q=>!state.claimed.includes(q.id));$('#quest-count').textContent=`${state.claimed.length} / ${QUESTS.length}`;if(q){$('#quest').innerHTML=`<h3 class="quest-heading"><i>${QUESTS.indexOf(q)+1}</i>${q.title}</h3><p class="quest-copy">${q.text}</p><div class="quest-reward">${reward(q.reward)}</div><button class="quest-button ${q.check(state)?'ready':''}" id="quest-action">${q.check(state)?'领取奖励':'前往完成'}</button><div class="quest-dots">${QUESTS.map(x=>`<span class="${state.claimed.includes(x.id)?'done':''}"></span>`).join('')}</div>`;$('#quest-action').onclick=()=>q.check(state)?mutate(()=>claim(state,q.id)):q.id==='quarry'?chooseBuild('quarry'):q.id==='meditation'?chooseBuild('meditation'):expansion.quest(q.id);}else $('#quest').innerHTML='<h3 class="quest-heading">初境已成</h3><p class="goal-finish">山门渐盛，仙途方启。继续营造仙府，招募弟子，修习更高境界。</p><div class="quest-dots"><span class="done"></span><span class="done"></span><span class="done"></span></div>';
 renderDetail(force);
 if(tab==='build'){const key=`build:${building}:${Object.values(TYPES).map(t=>canPay(state,t.cost)).join()}`;if(force||renderKey!==key){renderKey=key;$('#bottom-content').innerHTML=`<div class="building-cards">${Object.entries(TYPES).map(([k,t],i)=>`<button class="build-card ${building===k?'selected':''} ${!canPay(state,t.cost)?'insufficient':''}" data-build="${k}" title="${t.desc} ${k==='hall'?'已建成':reward(t.cost)}"><span class="build-index">0${i+1}</span><div class="sprite-thumb" style="${spriteStyle(t.sprite)}"></div><span class="build-name">${t.name}</span><span class="build-cost">${k==='hall'?'仙府根基 · 已建成':cost(t.cost)}</span></button>`).join('')}</div>`;$$('[data-build]').forEach(b=>b.onclick=()=>b.dataset.build==='hall'?selectBuilding(1):chooseBuild(b.dataset.build));}}
 if(tab==='disciples'){const scroll=$('.disciples')?.scrollLeft||0;$('#bottom-content').innerHTML=`<div class="disciples">${state.disciples.map(d=>{const job=state.buildings.find(b=>b.id===d.job);return`<article class="disciple-card"><div class="disciple-header"><div class="portrait" style="background-position:${d.portrait*100/3}% 0"></div><div><div class="disciple-name">${esc(d.name)}</div><div class="disciple-meta">${esc(d.root)} · 炼气${d.realm}层</div></div></div><div class="disciple-job"><span>${job?TYPES[job.type].name:'府中休憩'}</span><span>${Math.floor(d.xp)} / ${d.realm*100}</span></div><div class="progress"><div style="width:${d.xp/d.realm}%"></div></div><div class="disciple-actions"><button class="secondary" data-assign="${d.id}">安排事务</button><button class="primary" data-breakthrough="${d.id}" ${d.xp<d.realm*100||d.realm>=9?'disabled':''}>${d.realm>=9?'境界已满':'突破'}</button></div></article>`;}).join('')}<button class="recruit-card" id="recruit"><strong>＋</strong><span>招募弟子</span><small>灵石 80 · 灵草 10</small></button></div>`;$('.disciples').scrollLeft=scroll;$$('[data-assign]').forEach(b=>b.onclick=()=>assignModal(Number(b.dataset.assign)));$$('[data-breakthrough]').forEach(b=>b.onclick=()=>breakthroughModal(Number(b.dataset.breakthrough)));$('#recruit').onclick=()=>mutate(()=>{const d=recruit(state);toast(`${d.name}拜入仙府，记得安排事务。`);});}
 if(tab==='journal'){$('#bottom-content').innerHTML=`<div class="journal">${state.logs.map(l=>`<div class="log-row"><time>${day(l.time)}</time><span>${esc(l.text)}</span></div>`).join('')}</div>`;}
 expansion?.render();
 if(tab==='market')renderCommunity(state,mutate,toast);
 if(force)saveProgress();
}
function renderDetail(force){const b=state.buildings.find(b=>b.id===selected);if(!b){$('#detail').innerHTML='<div class="selection-hint">点选府中建筑<br>查看详情与安排弟子</div>';return;}const t=TYPES[b.type],d=state.disciples.find(d=>d.job===b.id);const key=`${b.id}:${b.level}:${state.disciples.map(d=>d.job).join()}:${building}`;if(force||$('#detail').dataset.key!==key){$('#detail').dataset.key=key;$('#detail').innerHTML=`<div class="detail-top"><h3>${t.name}</h3><span class="level">${b.level} 级</span><button class="detail-close" aria-label="收起建筑详情">×</button></div><div class="building-display"><div class="sprite-thumb" style="${spriteStyle(t.sprite)}"></div></div><p class="detail-desc">${t.desc}</p><div class="detail-rule"></div>${Object.keys(t.out).length?`<div class="detail-label"><span>${t.work?(d?'正在生产':'等待弟子'):'灵气凝聚'}</span><span id="production-time"></span></div><div class="progress"><div id="production-progress"></div></div><div class="detail-label"><span>每轮产出</span><span>${reward(Object.fromEntries(Object.entries(t.out).map(([k,v])=>[k,+(v*b.level*(d?d.talent*(1+.1*(d.realm-1)):1)).toFixed(1)])))}</span></div>`:''}${t.work?`<label class="detail-label" for="assign-select">执事弟子 <span>一处建筑 · 一名执事</span></label><select id="assign-select"><option value="">暂不派遣</option>${state.disciples.map(p=>`<option value="${p.id}" ${isAway(state,p.id)?'disabled':''} ${p.id===d?.id?'selected':''}>${esc(p.name)} · ${p.job===null?'闲暇':p.id===d?.id?'正在此处':TYPES[state.buildings.find(x=>x.id===p.job).type].short}</option>`).join('')}</select>`:b.type==='house'?`<p class="house-hint">当前仙府可容纳 ${capacity(state)} 名弟子。<br>升级居所可继续扩充容量。</p>`:'<button id="hall-disciples" class="secondary full">查看与安排弟子</button>'}${b.level<3?`<button id="upgrade" class="primary full">升级建筑<span class="upgrade-cost">${cost(upgradeCost(b))}</span></button>`:'<div class="detail-label">已达当前最高等级</div>'}${b.type!=='hall'?'<button id="demolish" class="secondary full" style="font-size:12px">拆除并返还建造材料</button>':''}`;$('.detail-close').onclick=()=>$('#detail').classList.remove('mobile-open');if($('#assign-select'))$('#assign-select').onchange=e=>mutate(()=>{const prior=state.disciples.find(p=>p.job===b.id);if(prior&&String(prior.id)!==e.target.value)assign(state,prior.id,null);if(e.target.value)assign(state,Number(e.target.value),b.id);toast('已更新弟子分工');});if($('#upgrade'))$('#upgrade').onclick=()=>mutate(()=>{upgrade(state,b.id);toast(`${t.name}已升至 ${b.level} 级`);});if($('#hall-disciples'))$('#hall-disciples').onclick=()=>setTab('disciples');if($('#demolish'))$('#demolish').onclick=()=>demolishModal(b);}
 if($('#production-time'))$('#production-time').textContent=`${Math.floor(b.progress)} / 20 秒`;if($('#production-progress'))$('#production-progress').style.width=`${b.progress/20*100}%`;}
function setTab(next){tab=next;$('.bottom-panel').classList.remove('folded');if(next==='build'&&expansion?.scene()!=='map')expansion?.selectScene('map');renderKey='';$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));render(true);}
function selectBuilding(id){selected=id;cancelBuild();$('#detail').classList.add('mobile-open');render(true);}
function chooseBuild(type){const lock=buildingLock(state,type);if(lock){toast(lock);return;}if(expansion?.scene()!=='map')expansion?.selectScene('map');if(!canPay(state,TYPES[type].cost)){toast(`营造${TYPES[type].name}所需材料不足。`);return;}building=type;$('#placement-bar').classList.remove('hidden');$('#placement-text').textContent=`营造${TYPES[type].name} · 点击亮起的空地`;$('#detail').classList.remove('mobile-open');setTab('build');canvas.style.cursor='crosshair';}
function cancelBuild(){building=null;hover=null;$('#placement-bar').classList.add('hidden');canvas.style.cursor='grab';render(true);}
function assignModal(id){const d=state.disciples.find(d=>d.id===id);openModal(`安排${d.name}`,`<p>调整分工立即生效。主殿与聚灵台提升修为，生产建筑提供营造所需物资。</p><label for="modal-job">选择事务</label><select id="modal-job"><option value="">府中休憩</option>${state.buildings.filter(b=>b.type==='hall'||TYPES[b.type].work).map(b=>{const occupied=isAway(state,id)||(b.type!=='hall'&&state.disciples.some(p=>p.id!==id&&p.job===b.id));return`<option value="${b.id}" ${d.job===b.id?'selected':''} ${occupied?'disabled':''}>${TYPES[b.type].name} #${b.id}${occupied?' · 已有执事':''}</option>`;}).join('')}</select><button id="confirm-job" class="primary full">确认安排</button>`);$('#confirm-job').onclick=()=>{const value=$('#modal-job').value;try{assign(state,id,value?Number(value):null);closeModal();render(true);toast('已安排新的事务');}catch(e){toast(e.message);}};}
function breakthroughModal(id){const d=state.disciples.find(d=>d.id===id);openModal('叩问仙途',`<p>${esc(d.name)}修为已满，可突破至炼气${d.realm+1}层。境界提升后，生产效率增加。</p><p class="modal-rewards">所需：灵石 ${30*d.realm} · 灵草 ${12*d.realm}</p><button id="confirm-breakthrough" class="primary full">凝神突破</button>`);$('#confirm-breakthrough').onclick=()=>{try{breakthrough(state,id);closeModal();render(true);toast(`${d.name}成功突破至炼气${d.realm}层！`);}catch(e){$('#modal-body').insertAdjacentHTML('beforeend',`<p>${esc(e.message)}</p>`);}};}
function demolishModal(b){openModal('拆除建筑',`<p>确定拆除${TYPES[b.type].name}？返还全部营造材料，驻守弟子恢复闲暇；正在炼丹的丹炉不可拆除。</p><button id="confirm-demolish" class="primary full">确认拆除并返还材料</button>`);$('#confirm-demolish').onclick=()=>{try{demolish(state,b.id);selected=state.buildings.find(x=>x.type==='hall').id;closeModal();render(true);toast('建筑已拆除，材料已返还。');}catch(e){toast(e.message);}};}
$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#cancel-build').onclick=cancelBuild;$('#pause').onclick=()=>{state.speed=state.speed?0:1;render();};$$('[data-speed]').forEach(b=>b.onclick=()=>{state.speed=Number(b.dataset.speed);render();});$('#zoom-in').onclick=()=>zoom=Math.min(2,zoom+.15);$('#zoom-out').onclick=()=>zoom=Math.max(.65,zoom-.15);$('#recenter').onclick=()=>{zoom=1;pan.x=0;pan.y=0;};$('#grid-toggle').onclick=()=>{showGrid=!showGrid;$('#grid-toggle').setAttribute('aria-pressed',showGrid);};
const mapInput=attachMapInput(canvas,{pan,enabled:()=>!modalOpen,onDragChange:active=>canvas.classList.toggle('is-dragging',active),onHover:e=>{const p=pointerPos(e);hover=tileAt(p.x,p.y);},onActivate:e=>{const p=pointerPos(e);if(expansion?.scene()!=='map'){expansion.activate(p);return;}const tile=tileAt(p.x,p.y);if(building){mutate(()=>{const b=build(state,building,tile.x,tile.y);selected=b.id;cancelBuild();$('#detail').classList.add('mobile-open');toast(`${TYPES[b.type].name}落成${TYPES[b.type].work?'，可在右侧派遣弟子。':'。'}`);});}else{const hit=state.buildings.filter(b=>{const p2=tilePos(b.x,b.y);return Math.abs(p.x-p2.x)<68&&p.y>p2.y-112&&p.y<p2.y+57;}).sort((a,b)=>tilePos(b.x,b.y).y-tilePos(a.x,a.y).y)[0];if(hit)selectBuilding(hit.id);}}});
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.65,Math.min(2,zoom-e.deltaY*.0008));},{passive:false});
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON','A'].includes(e.target.tagName)||modalOpen)return;if(e.code==='Space'){e.preventDefault();$('#pause').click();}if(e.key==='Escape'){cancelBuild();$('#detail').classList.remove('mobile-open');}if(e.key==='+'||e.key==='=')$('#zoom-in').click();if(e.key==='-')$('#zoom-out').click();});
$('#help').onclick=()=>openModal('山居入门',`<ol><li>在下方「营造」选择建筑，再点击山坪上的空地建造。</li><li>点选地图上的建筑，派遣弟子生产灵木、青石或灵草。</li><li>在「门人」中安排修炼。主殿可以修炼，聚灵台修炼更快；修为满后消耗灵石与灵草突破。</li><li>完成右侧「仙府纪事」领取奖励，建造弟子居后可招募新人。</li><li>营造丹霞炉后可炼丹，在门人页服丹精进。山外游历中途需要处理奇遇，归来带回灵材和声望；宗门二阶解锁寒潭、灵泉与高阶丹方。</li><li>空格暂停；拖动画卷平移，滚轮缩放。触屏可拖动地图，并用左侧按钮缩放。</li></ol><div class="settings-note">每 20 秒结算一次生产。弹窗打开时游戏暂歇；进度自动保存在当前浏览器，换设备前请导出存档。当前为山门烟火版本，最高炼气九层、建筑三级、宗门三阶；支持导入旧版存档。</div>`);
$('#settings').onclick=()=>openSettings();function openSettings(){openModal('存档与设置',`<p>把青岚仙府收入一纸画卷，下次导入即可接续游玩。</p><div class="settings-note">${esc(persistence.status)}。每 5 秒、关键操作后与离开页面时保存到当前浏览器；刷新后自动续玩。保留上一份备份。不同浏览器不互通，清理网站数据会清除本机进度，请定期导出。离开期间不结算收益。</div><div class="settings-actions"><button id="export-save" class="primary">导出存档</button><button id="load-save" class="secondary">导入存档</button></div><button id="reset-game" class="secondary danger">另起仙府</button>`);$('#export-save').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`青岚仙府-第${Math.floor(state.time/120)+1}日.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出仙府存档。');};$('#load-save').onclick=()=>$('#import-file').click();$('#reset-game').onclick=()=>{openModal('另起仙府',`<p>当前进度及本机自动存档将被新仙府替换。建议先导出存档。</p><button id="reset-confirm" class="primary full">确认重新开始</button>`);$('#reset-confirm').onclick=()=>{state=initial();saveProgress(true);selected=1;building=null;closeModal();cancelBuild();setTab('build');toast('新一卷仙府岁月，徐徐展开。');};};}
$('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1024*1024)throw new Error('存档文件过大。');const candidate=validateSave(JSON.parse(await f.text()));openModal('导入仙府存档',`<p>将载入${day(candidate.time)}、${candidate.buildings.length}座建筑、${candidate.disciples.length}名弟子的进度，替换当前仙府。</p><button id="confirm-import" class="primary full">确认载入存档</button>`);$('#confirm-import').onclick=()=>{state=candidate;saveProgress(true);selected=state.buildings.find(b=>b.type==='hall').id;closeModal();cancelBuild();setTab('build');toast('画卷已展开，仙府进度已恢复。');};}catch(e){toast('无法导入：'+e.message);}e.target.value='';};
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(name,description,inputSchema,execute,readOnly=false)=>{try{Promise.resolve(context.registerTool({name,description,inputSchema,annotations:{readOnlyHint:readOnly,untrustedContentHint:false},execute}, {signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register('read_estate','读取当前仙府资源、建筑、弟子和空闲地块。',{type:'object',properties:{},additionalProperties:false},()=>({resources:{...state.resources},buildings:state.buildings.map(b=>({...b})),disciples:state.disciples.map(d=>({...d})),speed:state.speed,emptyCells:CELLS.filter(c=>!state.buildings.some(b=>b.x===c.x&&b.y===c.y))}),true);
 register('build_estate_building','在指定空闲地块花费资源完成建筑营造。',{type:'object',properties:{type:{type:'string',enum:['farm','lumber','quarry','house','meditation','alchemy','library','well']},x:{type:'integer'},y:{type:'integer'}},required:['type','x','y'],additionalProperties:false},input=>{if(!input||!['farm','lumber','quarry','house','meditation','alchemy','library','well'].includes(input.type)||!Number.isInteger(input.x)||!Number.isInteger(input.y))throw new Error('Invalid building input');const b=build(state,input.type,input.x,input.y);selected=b.id;render(true);return{building:{...b},resources:{...state.resources}};});
 register('assign_estate_disciple','调配弟子到建筑，buildingId 为 null 时休憩。',{type:'object',properties:{discipleId:{type:'integer'},buildingId:{type:['integer','null']}},required:['discipleId','buildingId'],additionalProperties:false},input=>{if(!input||!Number.isInteger(input.discipleId)||(input.buildingId!==null&&!Number.isInteger(input.buildingId)))throw new Error('Invalid assignment');assign(state,input.discipleId,input.buildingId);render(true);return{disciple:{...state.disciples.find(d=>d.id===input.discipleId)}};});
 register('set_estate_speed','设置游戏速度：0 暂停，1 正常，2 或 4 加速。',{type:'object',properties:{speed:{type:'integer',enum:[0,1,2,4]}},required:['speed'],additionalProperties:false},input=>{if(!input||![0,1,2,4].includes(input.speed))throw new Error('Invalid speed');state.speed=input.speed;render();return{speed:state.speed};});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
expansion=createExpansion({getState:()=>state,getTab:()=>tab,setTab,chooseBuild,openModal,closeModal,mutate,toast,esc,cancelBuild,refresh:()=>render(true),resetCamera:()=>{pan.x=0;pan.y=0;zoom=1;}});
render(true);resize();Promise.all(Object.entries({map:'map.webp',buildings:'buildings.png',disciples:'disciples.png',valley:'valley.webp',lake:'lake.webp',newbuildings:'newbuildings.png'}).map(([k,file])=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{imgs[k]=img;resolve();};img.onerror=()=>reject(new Error(file));img.src='./assets/'+file;}))).then(()=>{assetsReady=true;$('#asset-status').classList.add('hidden');draw(performance.now());}).catch(()=>{$('#asset-status').textContent='画卷加载失败，请刷新重试';});registerTools();
let lastDraw=0;
setInterval(()=>saveProgress(),5000);
window.addEventListener('pagehide',()=>saveProgress());
document.addEventListener('visibilitychange',()=>{if(document.hidden)saveProgress();});
window.addEventListener('storage',event=>{if(event.key==='xianfu:simulation-web-game:save'){state.speed=0;saveProgress();toast('另一窗口已保存进度。此处已暂停，请刷新后续玩，避免覆盖。');}});
if(restored)toast('青岚画卷已续上，欢迎掌门归山。');
function frame(now){const dt=lastTime?Math.min((now-lastTime)/1000,.25):0;lastTime=now;if(assetsReady&&!modalOpen&&!document.hidden)tick(state,dt);if(now-uiTime>700){render();uiTime=now;}if(!document.hidden&&now-lastDraw>33){draw(now);lastDraw=now;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
