import * as prior from './living-world.mjs?v=ea-160-courtyard-20261008-r15';
export * from './living-world.mjs?v=ea-160-courtyard-20261008-r15';
const {TYPES,RESOURCE,CELLS,addLog,pay,canPay,capacity,EXPEDITIONS,RECIPES}=prior;

export const TECHNIQUES={
 qingyuan:{name:'青岚养元诀',kind:'main',element:'neutral',realm:1,source:'家传炼气篇 · 随身带出',description:'适性宽和的入门功法。修炼修为收益提高 12%。',cost:null},
 spring:{name:'春雨养脉法',kind:'support',element:'water',realm:1,source:'母亲药理手札 · 第一章整理',description:'温养经脉，休憩时精力恢复提高。',cost:null},
 ember:{name:'赤阳行气诀',kind:'main',element:'fire',realm:2,source:'云游修士交换',description:'进境较快，修炼额外消耗精力，与寒泉法门冲突。',cost:{jade:140,herb:25}},
 frost:{name:'寒泉静心诀',kind:'main',element:'water',realm:2,source:'云游修士交换',description:'清心凝神，减少修炼消耗，与赤阳法门冲突。',cost:{jade:140,crystal:2}},
 flame:{name:'凝火诀',kind:'support',element:'fire',realm:2,source:'行脚丹师交换',description:'凝聚丹火，辅助修炼；与寒泉主修相斥。',cost:{jade:100,herb:20}},
 wood:{name:'青木调息法',kind:'support',element:'wood',realm:1,source:'灵植师交换',description:'借草木生机辅助修行，与水行主修相生。',cost:{jade:90,wood:40}}
};
export const STORY=[
 {title:'雨夜余烬',text:'双亲以生命护你逃离栖霞。沿母亲留下的记忆来到旧别院，先治好逃亡的伤势。',action:'确认伤势已愈'},
 {title:'一剂生机',text:'山下采药人陆知微为亲人求药。以母亲留下的药理救治，或许能结下一段善缘。需要灵草 10。',action:'赠药救人'},
 {title:'孤客来投',text:'修好灵草田与伐木场，让这处山院能养活愿意留下的人。年轻散修林长风也在寻找安身之地。',action:'接纳来客'},
 {title:'旧卷余温',text:'建成藏经阁，整理母亲药理札记。旧玉简记载的商路，将成为追查灭门真相的起点。',action:'整理遗卷'}
];
TYPES.hall.name='别院主屋';TYPES.hall.desc='母亲留下的采药别院。凝聚少量灵石，供门人安身与修炼。';
TYPES.farm.desc='栽种凝露草。门人自主选择照料，持续收获灵草。';TYPES.lumber.desc='择木而伐，取材造府。门人依照院中需求与自身意愿采集灵木。';TYPES.meditation.desc='汇聚天地灵气，供门人自主修炼。基础修炼收益为每秒 2 点修为。';
const traits=['仁心','野心','守信','自律','好奇'];
const positions=()=>({x:3,y:3});
function master(){return{name:'沈砚',realm:6,xp:0,talent:1.75,energy:80,wound:30,action:'rest',work:0,position:positions(),path:[],main:'qingyuan',support:[],knowledge:{qingyuan:40},learning:null,journey:null};}
function mind(id){const sets=[[82,44,78,68,62],[45,88,36,57,80],[65,60,70,85,48],[38,91,30,70,90]];return{traits:sets[(id-1)%4],goal:['精研草木','求取长生','守成护道','求索奇法'][(id-1)%4],main:null,support:[],knowledge:{},learning:null,activity:'rest',reason:'初到山院，正在观察环境。',memories:[],lastPillDay:-1,caution:0};}
function remember(s,d,text){d.mind.memories.unshift({time:s.time,text});d.mind.memories=d.mind.memories.slice(0,8);}
function rand(s){let x=s.sim.seed>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;s.sim.seed=x>>>0;return s.sim.seed/4294967296;}
function setup(s,legacy=false){s.version=4;s.master=master();s.story={step:legacy?4:0,intro:legacy};s.doctrine={books:legacy?['qingyuan','spring']:['qingyuan'],sealed:[],workFocus:'balanced',pillRule:'shared',routes:[]};s.sim={seed:618033,carry:0,decision:0};s.incidents=[];s.incidentId=1;s.disciples.forEach(d=>{d.mind=mind(d.id);d.job=null;});if(legacy){s.master.wound=0;addLog(s,'旧画卷已续入「余烬立山」：现有资源与建筑保留，门人开始自主安排修行与事务。');}return s;}
export function initial(){const s=setup(prior.initial());s.resources={jade:110,wood:65,stone:45,herb:16,crystal:0,insight:0};s.buildings=s.buildings.filter(b=>b.type==='hall');s.nextId=2;s.disciples=[];s.logs=[{time:0,text:'栖霞一夜成灰。你携残存传承来到云岫别院，父母留下的最后一句话是：活下去。'}];return s;}
export function stage(s){return s.story.step>=4&&s.disciples.length>=5?2:s.story.step>=2?1:0;}
export const STAGE_NAMES=['结庐避祸','隐姓山居','山院初成'];
export function buildingLock(s,type){const lock=prior.buildingLock(s,type);if(lock)return lock;if(['library','meditation','alchemy'].includes(type)&&stage(s)<1)return '完成赠药救人后开放';if(type==='well'&&s.sect.level<2)return '正式立派后开放 · 后续篇章';return '';}
export function build(s,type,x,y){if(s.master.position.x===x&&s.master.position.y===y)throw Error('掌门正在此处，请先移动到其他地块。');const lock=buildingLock(s,type);if(lock)throw Error(lock);return prior.build(s,type,x,y);}
export function recruit(s){if(stage(s)<1)throw Error('先结识第一位追随者。');const d=prior.recruit(s);d.name=['顾听澜','云见月','裴照雪','江晚棠','叶松声','苏归岚','洛清川','许望舒'][(d.id-1)%8];d.mind=mind(d.id);remember(s,d,'为安身与求道来到云岫山院。');return d;}
export function assign(){throw Error('门人自主选择事务，请在院务中发布差事侧重。');}
export function breakthrough(){throw Error('门人会根据修为和府库资源自主决定突破。');}
export function usePill(){throw Error('门人自主服丹；可通过院规设置丹药取用规则。');}
export function upgradeSect(){throw Error('正式立派需要筑基与成型传承，后续篇章开放。');}
export function setPolicy(s,key,value){const options={workFocus:['balanced','wood','stone','herb','insight'],pillRule:['shared','permission']};if(!options[key]?.includes(value))throw Error('院规选项无效。');s.doctrine[key]=value;addLog(s,key==='workFocus'?'掌门调整了差事侧重，门人将自行权衡。':`丹药取用改为${value==='shared'?'按需共用':'须获准许'}。`);}
export function sealBook(s,id){if(id==='qingyuan'||!s.doctrine.books.includes(id))throw Error('基础传承不可封存。');const i=s.doctrine.sealed.indexOf(id);if(i<0)s.doctrine.sealed.push(id);else s.doctrine.sealed.splice(i,1);addLog(s,`${TECHNIQUES[id].name}${i<0?'已列为禁阅':'重新开放'}。已有修行不会被抹去。`);}
export function obtainBook(s,id){const t=TECHNIQUES[id];if(!t?.cost||s.doctrine.books.includes(id)||stage(s)<1)throw Error('此传承尚不可交换，或已经拥有。');pay(s,t.cost);s.doctrine.books.push(id);addLog(s,`以物资从${t.source}取得《${t.name}》。`);}
export function compatible(person,id){const t=TECHNIQUES[id];if(!t)return false;const ids=[person.main,...person.support].filter(x=>x&&x!==id);const elements=ids.map(x=>TECHNIQUES[x].element);const all=new Set([...ids,id]);if(all.has('frost')&&(all.has('ember')||all.has('flame')))return false;return true;}
export function studyLock(s,person,id,isMaster=false){const t=TECHNIQUES[id];if(!t||!s.doctrine.books.includes(id))return '府中尚无此传承';if(person.realm<t.realm)return `需炼气${t.realm}层`;const p=isMaster?person:person.mind;if(p.main===id||p.support.includes(id))return '已经修习';if(!compatible(p,id))return '与现有功法相冲';if(t.kind==='support'&&p.support.length>=(person.realm>=4&&person.talent>=1.6?2:1))return '辅修精力已满';if(id!=='qingyuan'&&!s.buildings.some(b=>b.type==='library'))return '需要藏经阁供研习';return '';}
export function masterAction(s,action){const m=s.master;if(m.journey)throw Error('先结束掌门游历。');if(!['rest','heal','cultivate','wood','stone','herb','teach'].includes(action))throw Error('行动无效。');if(action==='heal'){if(m.wound<=0)throw Error('伤势已经痊愈。');if(m.action==='heal')return;pay(s,{herb:6});}if(action==='cultivate'&&m.wound>0)throw Error('先疗伤，再静心修炼。');m.action=action;m.path=[];m.work=0;m.learning=null;}
export function masterStudy(s,id){const m=s.master;if(m.journey||m.wound>0)throw Error('疗伤归院后方可研习。');const lock=studyLock(s,m,id,true);if(lock)throw Error(lock);m.learning={id,progress:0};m.action='study';m.path=[];addLog(s,`掌门开始研习《${TECHNIQUES[id].name}》。`);}
export function masterBreakthrough(s){const m=s.master;if(m.journey||m.wound>0)throw Error('归院调息后方可突破。');if(m.realm>=9)throw Error('筑基篇尚未开放，需后续追查失落传承。');if(m.xp<m.realm*100)throw Error('修为未满。');pay(s,{jade:m.realm*30,herb:m.realm*12});m.xp-=m.realm*100;m.realm++;addLog(s,`掌门突破至炼气${m.realm}层。`);}
export function masterPill(s,id){const m=s.master,r=RECIPES[id];if(!r||m.journey||s.pills[id]<1)throw Error('丹药不足，或掌门尚在山外。');if(m.xp>=m.realm*100&&(!r.effect.energy||m.energy>=100))throw Error('此时服丹没有收益。');s.pills[id]--;m.xp=Math.min(m.realm*100,m.xp+r.effect.xp);m.energy=Math.min(100,m.energy+r.effect.energy);}
export function moveMaster(s,x,y){const m=s.master;if(m.journey)throw Error('掌门尚未归山。');const key=(x,y)=>`${x},${y}`,free=new Set(CELLS.filter(c=>!s.buildings.some(b=>b.x===c.x&&b.y===c.y)).map(c=>key(c.x,c.y)));if(!free.has(key(x,y)))return false;const queue=[{...m.position,path:[]}],seen=new Set([key(m.position.x,m.position.y)]);while(queue.length){const p=queue.shift();if(p.x===x&&p.y===y){m.path=p.path;m.action='walk';m.learning=null;return true;}for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,y:p.y+dy},k=key(n.x,n.y);if(free.has(k)&&!seen.has(k)){seen.add(k);queue.push({...n,path:[...p.path,n]});}}}return false;}
export function storyReady(s){return[s.master.wound===0,s.resources.herb>=10,s.buildings.some(b=>b.type==='farm')&&s.buildings.some(b=>b.type==='lumber'),s.buildings.some(b=>b.type==='library')][s.story.step]||false;}
function join(s,name,root,portrait){const id=Math.max(0,...s.disciples.map(d=>d.id))+1;const d={id,name,root,portrait,realm:1,xp:0,talent:id===1?1.15:1.08,energy:100,trait:id===1?'草木亲和':'求道心切',job:null,mind:mind(id)};s.disciples.push(d);remember(s,d,id===1?'掌门赠药救治亲人，我愿留下照看药圃。':'听闻云岫愿传基础功法，我来此求一处安身之地。');return d;}
export function advanceStory(s){if(!storyReady(s))throw Error('先完成这一段的目标。');const step=s.story.step;if(step===0){addLog(s,'伤势渐平。母亲的药理札记仍在，你决定先用它救人、安身。');}if(step===1){if(s.disciples.length>=capacity(s))throw Error('先准备足够居所。');pay(s,{herb:10});join(s,'陆知微','木灵根',1);addLog(s,'陆知微因赠药之恩留下。她有自己的志向，并不因此承诺追随复仇。');}if(step===2){if(s.disciples.length>=capacity(s))throw Error('先准备足够居所。');join(s,'林长风','土灵根',2);addLog(s,'林长风来到山院，希望凭自己的选择求得长生。');}if(step===3){if(!s.doctrine.books.includes('spring'))s.doctrine.books.push('spring');s.resources.insight+=8;addLog(s,'整理出《春雨养脉法》与一封旧商路信笺。第一章告一段落，追查栖霞的道路尚待展开。');}s.story.step++;}
export function offerRoute(s,id){if(!EXPEDITIONS[id])throw Error('路线不存在。');const i=s.doctrine.routes.indexOf(id);if(i<0)s.doctrine.routes.push(id);else s.doctrine.routes.splice(i,1);addLog(s,`${EXPEDITIONS[id].name}${i<0?'已列为可接游历差事':'已从差事中撤下'}。`);}
export function startMasterTravel(s,id){const r=EXPEDITIONS[id],m=s.master,lock=prior.expeditionLock(s,id);if(!r||lock)throw Error(lock||'路线不存在');if(m.journey||m.wound>0||m.energy<r.energy||m.realm<r.minRealm)throw Error('需伤势痊愈、精力与境界满足，且没有进行中的行程。');pay(s,r.cost);m.energy-=r.energy;m.learning=null;m.action='travel';m.path=[];m.journey={routeId:id,total:r.duration,remaining:r.duration,status:'traveling',encounterResolved:false,multiplier:1};addLog(s,`掌门亲往「${r.name}」。`);}
export function resolveMasterEncounter(s,choice){const m=s.master,e=m.journey;if(e?.status!=='encounter'||!['careful','bold'].includes(choice))throw Error('当前没有可处理的奇遇。');if(choice==='bold'){if(m.energy<10)throw Error('需额外 10 点精力。');m.energy-=10;e.multiplier=1.5;}e.encounterResolved=true;e.status='traveling';}
export function cancelMasterTravel(s){if(!s.master.journey)throw Error('掌门未在游历。');s.master.journey=null;s.master.action='rest';addLog(s,'掌门提前归院，本次出行不结算收获。');}
function learn(s,p,id,name){const t=TECHNIQUES[id];if(t.kind==='main')p.main=id;else if(!p.support.includes(id))p.support.push(id);p.knowledge[id]=20;p.learning=null;addLog(s,`${name}初步掌握《${t.name}》。`);}
function xpFactor(p){return(p.main==='ember'?1.22:p.main==='qingyuan'?1.12:1)*(p.support.includes('wood')?(p.main==='frost'?1.15:1.06):1)*(p.support.includes('flame')?1.06:1);}
function addIncident(s,d,kind){if(s.incidents.some(x=>x.discipleId===d.id&&!x.handled))return;s.incidents.push({id:s.incidentId++,discipleId:d.id,kind,time:s.time,discoverAt:s.time+25,discovered:false,handled:false});s.incidents=s.incidents.slice(-20);}
export function settleIncident(s,id,choice){const e=s.incidents.find(x=>x.id===id),d=s.disciples.find(d=>d.id===e?.discipleId);if(!e?.discovered||e.handled||!d||!['warn','forgive'].includes(choice))throw Error('此事当前不可处置。');e.handled=true;if(choice==='warn')d.mind.caution=Math.min(5,d.mind.caution+1);else d.mind.caution=Math.max(0,d.mind.caution-1);remember(s,d,choice==='warn'?'掌门就违背院规一事劝诫我，我会记得此次处置。':'掌门听取解释后不予追究。');addLog(s,`对${d.name}的${e.kind==='pill'?'私取丹药':'私阅封存典籍'}，掌门决定${choice==='warn'?'劝诫并记录':'不予追究'}。`);}
function decide(s,d){const p=d.mind,[kind,ambition,integrity,discipline,curiosity]=p.traits;if(prior.isAway(s,d.id))return;
 if(d.xp>=d.realm*100&&d.realm<9&&d.energy>=30&&canPay(s,{jade:30*d.realm,herb:12*d.realm})){prior.breakthrough(s,d.id);remember(s,d,'自行调息突破，境界更进一步。');}
 if(s.pills.qi>0&&d.xp<d.realm*100-30&&p.lastPillDay!==prior.gameDay(s)&&!s.incidents.some(e=>e.discipleId===d.id&&!e.handled)){const allowed=s.doctrine.pillRule==='shared',tempted=ambition-integrity-p.caution*10>25&&rand(s)<.35;if(allowed||tempted){prior.usePill(s,'qi',d.id);p.lastPillDay=prior.gameDay(s);if(!allowed){s.logs.shift();addIncident(s,d,'pill');}else remember(s,d,'依照按需共用的院规，服用聚气丹。');}}
 if(d.energy<25){d.job=null;p.activity='rest';p.reason='精力不足，先休憩恢复。';p.learning=null;return;}
 const choices=[{activity:'rest',job:null,score:Math.max(0,65-d.energy),reason:'暂歇身心，恢复精力。'}];
 if(p.learning&&s.doctrine.sealed.includes(p.learning.id)&&curiosity-integrity-p.caution*10<=25)p.learning=null;
 if(p.learning){choices.push({activity:'study',job:null,score:90,learning:p.learning,reason:`继续研习《${TECHNIQUES[p.learning.id].name}》，暂缓其他事务。`});}
 else for(const id of s.doctrine.books){if(studyLock(s,d,id))continue;const sealed=s.doctrine.sealed.includes(id),defy=curiosity-integrity-p.caution*10>25;if(sealed&&!defy)continue;const t=TECHNIQUES[id],affinity=(d.root.startsWith('木')&&t.element==='wood'||d.root.startsWith('水')&&t.element==='water'||d.root.startsWith('火')&&t.element==='fire')?15:0;if(t.kind==='main'&&p.main&&((p.knowledge[p.main]||0)<45||id==='qingyuan'))continue;choices.push({activity:'study',job:null,learning:{id,progress:0},score:35+curiosity*.4+affinity+(p.main?0:20)-(sealed?20:0),reason:sealed?'独自参阅古卷，暂不愿详谈。':`对《${t.name}》生出兴趣，准备花时间参悟。`});}
 for(const b of s.buildings){const t=TYPES[b.type];if(b.type!=='hall'&&!t.work)continue;if(b.type!=='hall'&&s.disciples.some(x=>x.id!==d.id&&x.job===b.id))continue;const cultivation=['hall','meditation'].includes(b.type);if(cultivation&&!p.main)continue;const output=Object.keys(t.out)[0],need=output?Math.max(0,75-s.resources[output])*.45:0,focus=output===s.doctrine.workFocus?20:0;choices.push({activity:cultivation?'cultivate':'work',job:b.id,score:cultivation?(d.xp>=d.realm*100?0:22+ambition*.45):18+discipline*.3+kind*.12+need+focus+(d.job===b.id?7:0),reason:cultivation?'希望精进境界，选择修炼。':`${focus?'响应院中差事，':'考虑府库需要，'}前往${t.name}。`});}
 if(!s.expedition&&p.main&&d.energy>=70)for(const id of s.doctrine.routes){const r=EXPEDITIONS[id];if(!prior.expeditionLock(s,id)&&d.realm>=r.minRealm&&canPay(s,r.cost))choices.push({activity:'travel',route:id,score:15+ambition*.3+curiosity*.3,reason:`愿意接下「${r.name}」，去山外见识。`});}
 for(const c of choices)c.score+=rand(s)*8;choices.sort((a,b)=>b.score-a.score);const chosen=choices[0];if(chosen.activity==='travel'){prior.startExpedition(s,chosen.route,d.id);p.activity='travel';p.reason=chosen.reason;remember(s,d,chosen.reason);return;}
 const changed=p.activity!==chosen.activity||d.job!==chosen.job||p.learning?.id!==chosen.learning?.id;d.job=chosen.job;p.activity=chosen.activity;p.reason=chosen.reason;p.learning=chosen.learning||null;if(changed)remember(s,d,chosen.reason);
}
function step(s){
 if(s.sim.decision<=0){for(const d of s.disciples)decide(s,d);s.sim.decision=10;}s.sim.decision--;
 if(s.expedition?.status==='encounter'){const d=s.disciples.find(d=>d.id===s.expedition.discipleId);prior.resolveEncounter(s,d.energy>=10&&d.mind.traits[1]+d.mind.traits[4]>130?'bold':'careful');remember(s,d,'依据自己的判断处理了途中灵迹。');}
 const previous=new Map(s.disciples.map(d=>[d.id,{xp:d.xp,energy:d.energy,away:prior.isAway(s,d.id)}]));prior.tick(s,1);
 for(const d of s.disciples){const p=d.mind,before=previous.get(d.id);if(before.away||prior.isAway(s,d.id))continue;if(p.activity==='study'){d.energy=Math.max(0,before.energy-.25);if(p.learning){p.learning.progress+=d.talent*(s.master.action==='teach'?1.5:1);if(p.learning.progress>=60){const id=p.learning.id,secret=s.doctrine.sealed.includes(id);learn(s,p,id,d.name);if(secret){s.logs.shift();addIncident(s,d,'book');}else remember(s,d,`通过研习掌握了《${TECHNIQUES[id].name}》。`);p.activity='rest';s.sim.decision=0;}}}else if(d.job!==null){d.energy=Math.max(0,before.energy-(p.main==='frost'?.18:p.main==='ember'?.42:.3));if(d.xp>before.xp)d.xp=Math.min(d.realm*100,before.xp+(d.xp-before.xp)*xpFactor(p));if(p.main)p.knowledge[p.main]=Math.min(100,(p.knowledge[p.main]||0)+.05);}else if(p.support.includes('spring'))d.energy=Math.min(100,d.energy+.4);}
 const m=s.master;if(m.journey){const e=m.journey;if(e.status==='traveling'){e.remaining=Math.max(0,e.remaining-1);if(!e.encounterResolved&&e.remaining<=e.total/2){e.remaining=e.total/2;e.status='encounter';}else if(!e.remaining){const r=EXPEDITIONS[e.routeId];for(const[k,v]of Object.entries(r.reward))s.resources[k]+=Math.floor(v*e.multiplier);s.sect.reputation+=r.reputation;s.stats.expeditions++;m.xp=Math.min(m.realm*100,m.xp+35);m.journey=null;m.action='rest';addLog(s,`掌门自「${r.name}」归来，带回灵材与见闻。`);}}}
 else if(m.action==='walk'){if(m.path.length)m.position=m.path.shift();if(!m.path.length)m.action='rest';}
 else if(m.action==='heal'){m.wound=Math.max(0,m.wound-2);m.energy=Math.min(100,m.energy+.5);if(!m.wound){m.action='rest';addLog(s,'逃亡伤势已愈，根基未损。');}}
 else if(m.action==='rest'){m.energy=Math.min(100,m.energy+1.3+(m.support.includes('spring')?.4:0));}
 else if(m.energy<=1){m.action='rest';m.learning=null;addLog(s,'掌门精力不足，暂歇调息。');}
 else if(m.action==='cultivate'){m.energy-=m.main==='frost'?.18:m.main==='ember'?.42:.25;m.xp=Math.min(m.realm*100,m.xp+2.2*m.talent*xpFactor(m));m.knowledge[m.main]=Math.min(100,(m.knowledge[m.main]||0)+.08);}
 else if(m.action==='study'&&m.learning){m.energy-=.3;m.learning.progress+=m.talent;if(m.learning.progress>=60){learn(s,m,m.learning.id,'掌门');m.action='rest';}}
 else if(m.action==='teach'){m.energy-=.2;}
 else if(['wood','stone','herb'].includes(m.action)){m.energy-=.2;m.work++;if(m.work>=10){m.work=0;s.resources[m.action]+=m.action==='wood'?8:6;}}
 for(const e of s.incidents)if(!e.discovered&&s.time>=e.discoverAt){e.discovered=true;const d=s.disciples.find(d=>d.id===e.discipleId);remember(s,d,'私下的行为被院中查知，等待掌门回应。');addLog(s,`核查记录后发现${d.name}${e.kind==='pill'?'私取丹药':'私阅封存典籍'}，可在院务中处理。`);}
}
export function tick(s,dt){if(!Number.isFinite(dt)||dt<=0||!s.speed)return;const speed=s.speed;s.sim.carry+=Math.min(dt,3600)*speed;s.speed=1;try{while(s.sim.carry>=1){s.sim.carry-=1;step(s);}}finally{s.speed=speed;}}
export function traitText(d){return d.mind.traits.map((n,i)=>({n,name:traits[i]})).sort((a,b)=>b.n-a.n).slice(0,2).map(x=>`${x.name} ${x.n}`).join(' · ');}

export function validateSave(input){
 if(input?.version!==4)return setup(prior.validateSave(input),true);
 const s=structuredClone(input),bad=()=>{throw Error('余烬立山存档字段异常。');},num=(n,min=0,max=1e12)=>typeof n==='number'&&Number.isFinite(n)&&n>=min&&n<=max,int=(n,min=0,max=1e12)=>Number.isSafeInteger(n)&&num(n,min,max),str=(v,max=200)=>typeof v==='string'&&v.length<=max;
 if(!num(s.time)||![0,1,2,4].includes(s.speed)||!s.resources||!Object.keys(RESOURCE).every(k=>num(s.resources[k]))||!Array.isArray(s.buildings)||s.buildings.length>CELLS.length||!Array.isArray(s.disciples)||s.disciples.length>100||!int(s.nextId,1)||!s.stats||!['built','breakthroughs','crafted','expeditions'].every(k=>int(s.stats[k]))||!Array.isArray(s.claimed)||new Set(s.claimed).size!==s.claimed.length||!s.claimed.every(id=>prior.QUESTS.some(q=>q.id===id)))bad();
 const ids=new Set(),cells=new Set(),jobs=new Set();for(const b of s.buildings){const k=`${b.x},${b.y}`;if(!int(b.id,1)||ids.has(b.id)||cells.has(k)||!TYPES[b.type]||!int(b.level,1,3)||(!num(b.progress)||b.progress>=20)||!CELLS.some(c=>c.x===b.x&&c.y===b.y))bad();ids.add(b.id);cells.add(k);}if(s.buildings.filter(b=>b.type==='hall').length!==1||s.nextId<=Math.max(...ids)||s.disciples.length>capacity(s)||s.buildings.filter(b=>b.type==='alchemy').length>1)bad();
 const validStudy=p=>{if(p.main!==null&&!TECHNIQUES[p.main]||p.main&&TECHNIQUES[p.main].kind!=='main'||!Array.isArray(p.support)||p.support.length>2||new Set(p.support).size!==p.support.length||!p.support.every(id=>TECHNIQUES[id]?.kind==='support')||!p.knowledge||Object.entries(p.knowledge).some(([k,v])=>!TECHNIQUES[k]||!num(v,0,100)))bad();if(p.learning!==null&&(!TECHNIQUES[p.learning?.id]||!num(p.learning.progress,0,60)))bad();};
 const dids=new Set();for(const d of s.disciples){if(!int(d.id,1)||dids.has(d.id)||!str(d.name,20)||!str(d.root,20)||!str(d.trait,30)||!int(d.realm,1,9)||!num(d.xp,0,d.realm*100)||!num(d.talent,.5,2)||!num(d.energy,0,100)||!int(d.portrait,0,3)||(d.job!==null&&(!ids.has(d.job)||!['hall','meditation'].includes(s.buildings.find(b=>b.id===d.job).type)&&!TYPES[s.buildings.find(b=>b.id===d.job).type].work)))bad();if(d.job!==null&&s.buildings.find(b=>b.id===d.job).type!=='hall'){if(jobs.has(d.job))bad();jobs.add(d.job);}dids.add(d.id);const p=d.mind;if(!p||!Array.isArray(p.traits)||p.traits.length!==5||!p.traits.every(n=>num(n,0,100))||!str(p.goal,30)||!str(p.reason)||!['rest','study','work','cultivate','travel'].includes(p.activity)||!int(p.lastPillDay,-1)||!int(p.caution,0,5)||!Array.isArray(p.memories)||p.memories.length>8||!p.memories.every(x=>num(x.time)&&str(x.text)))bad();validStudy(p);}
 const validJourney=(e,npc=false)=>{const r=EXPEDITIONS[e?.routeId];if(!r||e.total!==r.duration||!num(e.remaining,0,e.total)||!['traveling','encounter'].includes(e.status)||typeof e.encounterResolved!=='boolean'||![1,1.5].includes(e.multiplier)||e.status==='encounter'&&(e.encounterResolved||e.remaining!==e.total/2)||!e.encounterResolved&&(e.multiplier!==1||e.remaining<e.total/2)||npc&&!dids.has(e.discipleId))bad();};
 const m=s.master;if(!m||!str(m.name,20)||!int(m.realm,1,9)||!num(m.xp,0,m.realm*100)||!num(m.talent,.5,2)||!num(m.energy,0,100)||!num(m.wound,0,100)||!num(m.work,0,10)||!['rest','heal','cultivate','wood','stone','herb','teach','study','walk','travel'].includes(m.action)||!CELLS.some(c=>c.x===m.position?.x&&c.y===m.position?.y)||!Array.isArray(m.path)||m.path.length>CELLS.length||!m.path.every(p=>CELLS.some(c=>c.x===p.x&&c.y===p.y)))bad();validStudy(m);if(m.main===null)bad();if(m.journey!==null)validJourney(m.journey);if(s.expedition!==null)validJourney(s.expedition,true);
 if(!s.sect||!int(s.sect.level,1,3)||!num(s.sect.reputation)||!s.pills||!['qi','spirit'].every(k=>int(s.pills[k])))bad();if(s.crafting!==null){const c=s.crafting,r=RECIPES[c?.recipeId];if(!r||!s.buildings.some(b=>b.type==='alchemy')||!num(c.total,.01,r.duration)||!num(c.remaining,0,c.total))bad();}
 const c=s.community;if(!c||c.day!==prior.gameDay(s)||!int(c.completed)||!Array.isArray(c.fulfilled)||new Set(c.fulfilled).size!==c.fulfilled.length||!c.fulfilled.every(id=>prior.commissions(s).some(o=>o.id===id))||c.completed<c.fulfilled.length||!c.trades||!Object.keys(prior.GOODS).every(k=>int(c.trades[k],0,5)))bad();
 const a=s.doctrine;if(!s.story||!int(s.story.step,0,4)||typeof s.story.intro!=='boolean'||!a||!Array.isArray(a.books)||!a.books.includes('qingyuan')||a.books.length>6||new Set(a.books).size!==a.books.length||!a.books.every(id=>TECHNIQUES[id])||!Array.isArray(a.sealed)||!a.sealed.every(id=>a.books.includes(id)&&id!=='qingyuan')||!['balanced','wood','stone','herb','insight'].includes(a.workFocus)||!['shared','permission'].includes(a.pillRule)||!Array.isArray(a.routes)||a.routes.length>4||!a.routes.every(id=>EXPEDITIONS[id]))bad();
 if(!s.sim||!int(s.sim.seed,1,4294967295)||(!num(s.sim.carry)||s.sim.carry>=1)||!num(s.sim.decision,0,10)||!int(s.incidentId,1)||!Array.isArray(s.incidents)||s.incidents.length>20||!s.incidents.every(e=>int(e.id,1)&&e.id<s.incidentId&&dids.has(e.discipleId)&&['pill','book'].includes(e.kind)&&num(e.time)&&num(e.discoverAt)&&typeof e.discovered==='boolean'&&typeof e.handled==='boolean'))bad();
 s.logs=Array.isArray(s.logs)?s.logs.filter(l=>l&&num(l.time)&&str(l.text)).slice(0,50):[];return s;
}
