import{GOODS,commissions,fulfill,trade,canPay,RESOURCE}from'./living-world.mjs?v=ea-120-preview-20261005-r3';
export function renderCommunity(s,mutate,toast){
 const quotedDay=Math.floor(s.time/120);
 const root=document.querySelector('#bottom-content'),fmt=obj=>Object.entries(obj).map(([k,v])=>`${RESOURCE[k]} ${v}`).join(' · ');
 root.innerHTML=`<div class="community-board"><section class="notice-board"><div class="board-heading"><h3>山门委托</h3><small>第 ${Math.floor(s.time/120)+1} 日 · ${Math.ceil(120-s.time%120)} 秒后轮换</small></div><div class="order-list">${commissions(s).map(o=>{const done=s.community.fulfilled.includes(o.id),ready=canPay(s,o.cost||{})&&(!o.pill||s.pills[o.pill]>0);return`<article class="order-card"><span class="order-seal">${done?'已结缘':'委托'}</span><h4>${o.name}</h4><p>${o.text}</p><div class="order-cost">交付：${o.pill?'聚气丹 × 1':fmt(o.cost)}</div><div class="order-reward">酬谢：${fmt(o.reward)} · 声望 ${o.rep}</div><button class="primary" data-order="${o.id}" ${done||!ready?'disabled':''}>${done?'今日已完成':ready?'交付委托':'物资不足'}</button></article>`;}).join('')}</div></section><section class="market-stall"><div class="board-heading"><h3>云游货郎</h3><small>每份 10 灵材 · 每日各 5 份</small></div>${Object.entries(GOODS).map(([k,g])=>`<div class="trade-row"><div><strong>${g.name}</strong><small>余 ${5-s.community.trades[k]} 份 · 持有 ${Math.floor(s.resources[k])}</small></div><button class="secondary" data-goods="${k}" data-side="sell" ${s.resources[k]<10?'disabled':''}>卖出 +${g.sell}灵石</button><button class="primary" data-goods="${k}" data-side="buy" ${s.resources.jade<g.buy||s.community.trades[k]>=5?'disabled':''}>买入 ${g.buy}灵石</button></div>`).join('')}<p class="market-note">用余材换灵石，或补齐营造缺料。委托与货郎在每个游戏日开始时更新；暂停时不轮换。</p></section></div>`;
 root.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>mutate(()=>{fulfill(s,b.dataset.order,quotedDay);toast('委托已交付，酬谢收入府库。');}));
 root.querySelectorAll('[data-goods]').forEach(b=>b.onclick=()=>mutate(()=>trade(s,b.dataset.goods,b.dataset.side,quotedDay)));
 document.querySelector('#bottom-summary').textContent=`已结善缘 ${s.community.completed} 次`;
}
