import * as SIM from './ea-sim.mjs?v=ea-142-release-20261005-r1';
import {EA_SHELL,createEAUI} from './ea-ui.mjs?v=ea-142-release-20261005-r1';
import {createEAPersistence,MAX_IMPORT_BYTES} from './ea-persistence.mjs?v=ea-142-release-20261005-r1';
import {createWorldRenderer} from './ea-courtyard-renderer.mjs?v=ea-142-release-20261005-r1';
import {attachMapInput} from './map-input.mjs?v=ea-142-release-20261005-r1';
import {scenicPosition} from './ea-scenic.mjs?v=ea-142-release-20261005-r1';
import {sceneInteractionReady,sceneInteractionTarget} from './ea-interactions.mjs?v=ea-142-release-20261005-r1';
import {createRuntimeClock,createFrameDiagnostics} from './ea-runtime.mjs?v=ea-142-release-20261005-r1';
import {recommendedPlot} from './ea-onboarding.mjs?v=ea-142-release-20261005-r1';
import {createOpeningAudio} from './ea-opening-audio.mjs?v=ea-142-release-20261005-r1';

const VERSION=SIM.GAME_VERSION;
const runtimeClock=createRuntimeClock(),diagnostics=createFrameDiagnostics();
let lastPaintAt=null;
let mapInputStop=null,lastIntentCheck=0,pendingRegionDialogue=null;
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const timeText=value=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'尚未保存';
const clone=value=>structuredClone(value);
document.querySelector('#game').innerHTML=EA_SHELL;
let state=SIM.initial(),haveSession=false,volatile=false,activeSlot=null,dirty=false,lastGood=clone(state),ui,world;
let pendingRecommendation=null;
let mode='inspect',buildType=null,relocateId=null,selection=null,scene='map',tab='self',toastTimer,lastAuto=0,lastUI=0,lastFrame=performance.now(),busy=false,hiddenPause=false;
let saveMessage='请选择世界档案',resumeAfterPagehide=false,parked=null,saveError=false;
const acceptanceId=new URLSearchParams(location.search).get('acceptance');
const previewScope=acceptanceId==='1'||/^qa-[a-z0-9-]{1,48}$/.test(acceptanceId||'');
const previewNamespace=previewScope?(acceptanceId==='1'?'xianfu:simulation-web-game:ea-acceptance:':`xianfu:simulation-web-game:ea-acceptance-${acceptanceId}:`):undefined;
const preferenceKey=previewScope?`${previewNamespace}preferences`:'xianfu:ea:preferences';
const preferences={music:false,sfx:false,musicVolume:.6,sfxVolume:.6,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,textScale:1};
try{const p=JSON.parse(localStorage.getItem(preferenceKey)||'{}');for(const key of Object.keys(preferences))if(typeof p[key]===typeof preferences[key])preferences[key]=p[key];}catch{}
for(const key of ['musicVolume','sfxVolume'])preferences[key]=Number.isFinite(preferences[key])?Math.max(0,Math.min(1,preferences[key])):.6;
preferences.textScale=Math.max(.9,Math.min(1.2,preferences.textScale));
const modal=$('modal');
if(previewScope)document.body.classList.add('acceptance-preview');
const persistence=createEAPersistence({namespace:previewNamespace,validate:SIM.validateSave,gameVersion:VERSION,dataVersion:5,getState:()=>haveSession&&!volatile?state:undefined,onChange(event){
 if(haveSession&&event.mode==='writer'&&event.result?.code==='saved'){dirty=false;saveError=false;saveMessage=event.result.message;}
 if(haveSession&&event.result?.ok===false){state.speed=0;saveError=true;saveMessage=event.result.message||persistence.status;}if(haveSession&&!volatile&&persistence.mode!=='writer'){state.speed=0;saveMessage=persistence.status;}
 updateSaveStatus();
}});

function toast(message,error=false){if(modal.open){let notice=$('modal-notice');if(!notice){notice=document.createElement('p');notice.id='modal-notice';notice.setAttribute('role','alert');($('modal-body').querySelector('.prologue-content')||$('modal-body')).prepend(notice);}notice.textContent=message;notice.className=error?'warning-callout':'ui-note success';}const el=$('toast');if(!el)return;el.textContent=message;el.className='toast visible'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),5200);}
function openModal(title,html){modal.classList.toggle('cinematic',title.startsWith('序章 ·'));mapInputStop?.cancel?.();runtimeClock.suspend();$('close-modal').hidden=!haveSession;$('modal-title').textContent=title;$('modal-body').innerHTML=html;if(!modal.open)modal.showModal();$('modal-body').scrollTop=0;audio.suspend();}
function closeModal(){if(!haveSession)return;modal.close();lastFrame=performance.now();runtimeClock.resume(lastFrame);audio.sync();}
function updateSaveStatus(){const el=$('save-status');if(!el)return;const text=haveSession&&saveError?saveMessage:volatile?'仅内存试玩 · 请导出':haveSession?(persistence.canWrite?(saveError?saveMessage:dirty?'有新进度 · 即将保存':saveMessage):'只读 · '+persistence.status):saveMessage;el.textContent=text;el.title=haveSession&&!volatile?`世界 ${activeSlot} · ${timeText(persistence.savedAt)}。浏览器关闭后，从本机存档继续。`:text;el.classList.toggle('save-warning',volatile||haveSession&&!persistence.canWrite||saveMessage.includes('失败'));}
function persistPreferences(){document.documentElement.style.setProperty('--text-scale',preferences.textScale);document.documentElement.classList.toggle('reduced-motion',preferences.reducedMotion);try{localStorage.setItem(preferenceKey,JSON.stringify(preferences));}catch{}audio.sync();}
function checkpoint(){return `第${Math.floor(state.time/120)+1}日 · ${SIM.realmName(state.master.realm)} · 篇章${state.story.step}`;}
function saveNow({silent=false,important=false}={}){if(!haveSession)return {ok:false};if(volatile){if(!silent)toast('本次是内存试玩，请用「导出当前进度」保存文件。');return {ok:false};}const r=persistence.saveNow(state,important?{checkpoint:checkpoint()}:{});saveMessage=r.message;saveError=!r.ok;if(r.ok){dirty=false;lastGood=clone(state);}else{state.speed=0;if(!silent)toast(r.message,true);}updateSaveStatus();if(!silent&&r.ok)toast('当前进度已保存到本机。');return r;}
function mayAct(){if(!haveSession){showSlots();return false;}if(!volatile&&!persistence.canWrite){toast('当前窗口只读，请在存档设置中请求接管。',true);return false;}return true;}
const allowed=new Set(['setIntroPage','acknowledgeOnboarding','requestSceneInteraction','cancelSceneInteraction','setNarrativePage','acknowledgeNarrative','acknowledgeIntro','advanceStory','build','upgrade','toggleBuilding','repairBuilding','relocate','demolish','recruit','obtainBook','sealBook','masterStudy','forgetSupport','returnToBasics','masterBreakthrough','masterRiskBreakthrough','masterPill','masterAction','masterTeach','moveMaster','moveScenicMaster','craft','trade','fulfill','claim','setPolicy','offerRoute','upgradeSect','societyCommand','foundSect','inviteOffice','foundPeak','inviteMentor','setSocietyPolicy','settleIncident','resolvePersonalQuest','resolveWorldVisitor','resolveSocietyVisitor','startExploration','moveExploration','resolveExploration','leaveRegion','combatAction','acknowledgeCombat','startMasterTravel','resolveMasterEncounter','cancelMasterTravel']);
function act(name,...args){if(!mayAct())return null;if(!allowed.has(name)||typeof SIM[name]!=='function'){toast('此操作尚未接入，请刷新页面。',true);return null;}const before=clone(state);let committed=false;try{if(state.master.sceneIntent&&!['requestSceneInteraction','setNarrativePage','acknowledgeNarrative','acknowledgeIntro'].includes(name))SIM.cancelSceneInteraction(state);const result=SIM[name](state,...args);if(name==='requestSceneInteraction'&&!result.ready&&state.speed===0)state.speed=1;const startedCombat=before.combat?.status!=='active'&&state.combat?.status==='active';if(startedCombat)state.speed=1;SIM.validateSave(state);committed=true;dirty=true;lastGood=clone(state);if(startedCombat)ui?.fold();if((startedCombat||['startExploration','startMasterTravel','combatAction'].includes(name))&&state.world.exploration&&scene!=='journey')selectScene('journey');if(!state.world.exploration&&scene==='journey'&&!state.combat)selectScene('map');const major=state.story.step!==before.story.step||state.master.realm!==before.master.realm||state.society.peaks.length!==before.society.peaks.length||state.sect.level!==before.sect.level;
  if(!['moveMaster','moveScenicMaster','moveExploration','combatAction'].includes(name))saveNow({silent:true,important:major});
  if(result?.accepted===false)toast(result.reason||'对方暂时不愿接受。');else if(result?.reason)toast(result.reason);audio.effect(name==='combatAction'?'battle':'action');refresh(true);return result===undefined?true:result;
 }catch(error){if(!committed)state=before;else state.speed=0;toast(error.message||'操作未完成。',true);return null;}}
function setMode(next){mode=next;canvasMode();refresh(true);}
function canvasMode(){const el=$('mode-label');if(el)el.textContent=mode==='build'?'营造 · 选择空地':mode==='move'?'迁建 · 选择空地':mode==='walk'?'掌门 · 点地行走':'观景 · 点选 / 拖动';$('world')?.classList.toggle('placing',['build','move'].includes(mode));$('master-mode')?.setAttribute('aria-pressed',String(mode==='walk'));}
function chooseBuild(type){
 if(!mayAct())return;const t=SIM.BUILDINGS[type];if(!t)return;
 const lock=SIM.buildingLock(state,type);if(lock){toast(lock,true);return;}
 selectScene('map');world.setOverview(false);
 if(state.story.onboarding&&state.story.step<4&&['farm','lumber','library'].includes(type)&&!state.buildings.some(b=>b.type===type)){
  const plot=recommendedPlot(state,type,SIM.placementLock);pendingRecommendation=plot?{type,x:plot.x,y:plot.y}:null;
  openModal('初次营造 · '+t.name,`<div class="build-recommendation"><span class="eyebrow">给山院添一处真实设施</span><h3>${esc(t.name)}</h3><p>${esc(t.desc)}</p><p>本次消耗：${Object.entries(t.cost).map(([k,v])=>esc(SIM.RESOURCES[k])+' '+v).join(' · ')}。</p><p>${plot?'推荐地块 '+(plot.x+1)+' / '+(plot.y+1)+'：靠近主屋，入口与院路保持连通。预览后仍可改选其他空地。':'暂未找到连通的推荐空地，可自由选择；无效位置不会扣费。'}</p><p>道路影响能否抵达，生产还需要门人自主前来照料。</p><div class="actions">${plot?`<button class="primary" data-placement-preview="${esc(type)}">预览推荐位置</button>`:''}<button data-placement-free="${esc(type)}">自由选址</button><button data-resume>暂不营造</button></div></div>`);return;
 }
 beginPlacement(type);
}
function beginPlacement(type,plot=null){if(!mayAct())return;closeModal();buildType=type;relocateId=null;mode='build';world.setGrid(true);world.setHoverPlot?.(plot);if(plot)world.focusScenic?.(plot.x,plot.y);else pendingRecommendation=null;canvasMode();updatePlacement();refresh(true);}
function finishPlacement(){mode='inspect';buildType=null;relocateId=null;pendingRecommendation=null;world.setGrid(false);refresh(true);}
function ensureRunning(){if(mayAct()&&state.speed===0){state.speed=1;dirty=true;refresh(true);}}
function observeWork(buildingId,personId){selection={kind:'person',id:personId};selectScene('map');world.setGrid(false);world.setOverview(false);world.focus(0,0);ui.renderDetail(selection);const d=state.disciples.find(d=>d.id===personId);toast(d?d.name+'：'+d.mind.reason:'可以在人物档案中回顾这次收获。');}

function startRelocate(id){const b=state.buildings.find(b=>b.id===Number(id));if(!b)return;selectScene('map');buildType=b.type;relocateId=b.id;mode='move';canvasMode();updatePlacement();closeModal();}
function preview(){if(!buildType||!['build','move'].includes(mode))return null;const p=world?.getHover();return {type:buildType,recommended:pendingRecommendation,lock:p?SIM.placementLock(state,buildType,Math.round(p.x),Math.round(p.y),relocateId)||(SIM.canPay(state,mode==='move'?{jade:10*(state.buildings.find(b=>b.id===relocateId)?.level||1),wood:8*(state.buildings.find(b=>b.id===relocateId)?.level||1)}:SIM.BUILDINGS[buildType].cost)?'':'营造物资不足'):'选择空地'};}
function updatePlacement(){const bar=$('placement-bar');if(!bar)return;bar.hidden=!['build','move'].includes(mode);const p=preview();const confirm=$('placement-confirm');if(confirm){confirm.hidden=!pendingRecommendation||mode!=='build';confirm.disabled=!!pendingRecommendation&&(!!SIM.placementLock(state,buildType,pendingRecommendation.x,pendingRecommendation.y)||!SIM.canPay(state,SIM.BUILDINGS[buildType].cost));} $('placement-text').textContent=p?`${mode==='move'?'迁建':'营造'} · ${SIM.BUILDINGS[p.type].name}　${p.lock||'此处可安置 · 点击确认'}`:'';}
function selectScene(id){if(!['map','valley','lake','journey'].includes(id))return;if(id==='journey'&&!state.world.exploration&&!state.combat&&!state.master.journey){toast('先在「山外」选择目的地，再随掌门出行。');return;}scene=id;if(id==='map'&&state.combat?.status==='active'){state.speed=0;toast('查看山院时战斗已暂停。返回战场后点击继续。');}world?.setScene(id==='journey'?'valley':id);world?.recenter();refresh(true);}
function locate(kind,id){selection={kind,id:Number(id)};selectScene('map');const b=kind==='building'?state.buildings.find(b=>b.id===Number(id)):state.disciples.find(d=>d.id===Number(id));if(b){const p=b.position||b;world.focus(p.x,p.y);}ui?.renderDetail(selection);}
function setTab(next){tab=next;ui?.unfold();refresh(true);}
function refresh(force=false){if(!ui)return;ui.render({force});canvasMode();updatePlacement();updateSaveStatus();world?.render(performance.now(),true);}

function slotMeta(meta){return meta?`<p><strong>${esc(meta.leader)} · ${esc(meta.realm)}</strong></p><p>${esc(meta.sect)} · 第 ${meta.day} 日 · 门人 ${meta.people}</p><small>本机保存：${esc(timeText(meta.savedAt))}</small>`:'<p>从云岫旧药庐开始。</p><small>三个世界独立保存</small>';}
function slotCard(v){let action='';if(v.status==='ready')action=`<button class="primary" data-slot-open="${v.slot}">继续修行</button>`;else if(v.status==='empty')action=`<button class="primary" data-slot-new="${v.slot}">新建世界</button>`;else if(v.status==='migration-available')action=`<button class="primary" data-slot-migrate="${v.slot}">保留旧档并迁移</button>`;else if(v.status==='recovery-required')action=`<button class="primary" data-slot-recover="${v.slot}">选择备份恢复</button>`;else action='<span class="warning">本机存储暂不可用</span>';
 return `<article class="slot-card"><span class="eyebrow">世界 · ${['一','二','三'][v.slot-1]}</span><h3>${v.status==='empty'?'一卷新篇':v.status==='migration-available'?'旧日山院':v.status==='recovery-required'?'待修复的旧卷':esc(v.meta?.sect||'云岫仙府')}</h3>${slotMeta(v.meta)}${v.error?`<p class="warning">${esc(v.error)}</p>`:''}${v.warning?`<small>${esc(v.warning)}</small>`:''}<div class="actions">${action}${v.status!=='empty'&&v.status!=='unavailable'?`<button data-slot-backups="${v.slot}">备份</button>`:''}</div></article>`;}
function showSlots(){if(haveSession&&!volatile&&persistence.canWrite)saveNow({silent:true});openModal('云岫仙府 · 一卷山居',`<div class="start-menu"><p class="eyebrow">单人 · 仙侠经营 · EA ${VERSION}</p><h2>灯火未熄，山门待归。</h2><p>你是沈氏遗孤沈砚。父母以性命换你逃出栖霞，残卷与旧药庐，是重新立足的起点。</p><div class="slot-grid">${persistence.listSlots().map(slotCard).join('')}</div><div class="actions"><button data-import>导入存档文件</button><button data-paste-import>粘贴存档</button>${haveSession?'<button data-resume>返回当前世界</button>':''}${!navigator.locks||persistence.listSlots().some(v=>v.status==='unavailable')?'<button data-memory>仅内存试玩</button>':''}</div><p class="muted">每 5 秒及重要操作自动保存。请使用同一设备、浏览器与网址续玩；清理网站数据会移除本机档案。可导出文件，在另一设备导入。关闭网页期间不推进时间。</p></div>`);}
async function detach(){if(haveSession&&dirty&&(volatile||!persistence.canWrite)){openModal('当前进度尚未保存',`<p>这份进度只在当前窗口中。请先导出文件，或明确放弃后重新选择世界。</p><div class="actions"><button class="primary" data-export>导出当前进度</button><button data-discard-session>放弃未保存进度，返回选档</button><button data-resume>继续当前世界</button></div>`);return false;}if(haveSession&&dirty&&!volatile&&persistence.canWrite){const r=saveNow({silent:true});if(!r.ok){toast('先导出当前进度，再切换世界。',true);return false;}}haveSession=false;volatile=false;persistence.release();return true;}
function adopt(next,slot,{memory=false,readonly=false,fresh=false}={}){state=SIM.validateSave(next);activeSlot=slot;haveSession=true;volatile=memory;dirty=false;saveError=false;lastGood=clone(state);diagnostics.reset();lastPaintAt=null;ui?.resetNarrative?.();pendingRegionDialogue=null;if(readonly||state.combat?.status==='active')state.speed=0;mode='inspect';buildType=null;relocateId=null;selection=null;pendingRecommendation=null;scene=state.world.exploration?'journey':'map';world.setScene(scene==='journey'?'valley':scene);world.recenter();if(state.combat?.status==='active')ui?.fold();saveMessage=memory?'仅内存试玩':persistence.status;closeModal();refresh(true);lastFrame=performance.now();if(!readonly&&!state.story.intro&&state.story.step===0)ui.openPrologue(state.story.onboarding?.introPage||0);else if(!readonly&&!fresh)ui.showResume();if(readonly)toast('以只读方式查看，世界暂停。需要继续时可在设置中接管。');else if(state.combat?.status==='active')toast('战斗进度已恢复并暂停，准备好后点击继续。');}
async function openSlot(slot,takeover=false){if(busy)return;busy=true;try{if(!await detach())return;const r=await persistence.open(Number(slot),{takeover});activeSlot=Number(slot);if(r.ok&&r.state){adopt(r.state,activeSlot);return;}if(r.status==='empty'&&r.ok){showNew(slot);return;}if(persistence.mode==='writer'&&r.status==='migration-available'){showMigration(slot);return;}if(persistence.mode==='writer'&&r.status==='recovery-required'){showBackups(slot);return;}openModal('世界正在另一处展开',`<p>${esc(r.message)}</p>${r.state?slotMeta(r.meta):''}<div class="actions">${r.code==='not-writer'?`<button class="primary" data-slot-takeover="${slot}">请求接管此世界</button>`:''}${r.state?`<button data-slot-readonly="${slot}">只读查看</button>`:''}<button data-slots>返回世界列表</button>${persistence.mode==='unsafe'?'<button data-memory>仅内存试玩</button>':''}</div><p class="muted">接管后原窗口会保存并暂停。同一档案只允许一个窗口推进。</p>`);}catch(e){toast(e.message,true);}finally{busy=false;}}
function showNew(slot){const view=persistence.inspect(slot);openModal(view.status==='empty'?'启卷 · 云岫山居':'重开此卷',`<p>天资卓绝的沈氏遗孤，炼气六层，身负逃亡之伤。这里还不是一个宗门。</p><label>掌门姓名 <input id="new-master" value="沈砚" maxlength="20" autocomplete="off"></label>${view.status!=='empty'?'<p class="warning">此操作会替换此档位。现有有效档案会保留为备份，建议先导出。</p>':''}<div class="actions"><button class="primary" data-confirm-new="${slot}">落脚云岫</button><button data-slots>返回</button></div>`);}
async function createSlot(slot){if(busy)return;const name=$('new-master')?.value||'沈砚';busy=true;try{if(!await detach())return;const opened=await persistence.open(Number(slot));if(persistence.mode!=='writer'){toast(opened.message,true);showSlots();return;}const fresh=SIM.initial({name});const r=await persistence.replace(Number(slot),fresh,{confirmed:true});if(!r.ok){openModal('新卷尚未保存',`<div class="warning-callout">${esc(r.message)}</div><p>这份新卷还没有保存成功。你可以先体验开局，结束前导出文件；内存试玩不会自动保存，关页后会丢失未导出的进度。</p><div class="actions"><button class="primary" data-memory data-memory-name="${esc(name)}">内存试玩（不自动保存）</button><button data-slots>返回世界列表</button></div>`);return;}adopt(fresh,Number(slot),{fresh:true});toast('新卷已保存。先调息养伤，再安顿山院。');}catch(e){toast(e.message,true);}finally{busy=false;}}
function showMigration(slot){const v=persistence.inspect(slot);openModal('旧卷续写 · 迁移预览',`<p>保留旧版原文，复制到新版世界；人物、物资、建筑、已知传承与进行中的行程会继续保留。</p>${slotMeta(v.meta)}<div class="settings-list">${(v.migration?.candidates||[]).map(c=>`<article><p>${c.id==='legacy-backup'?'旧版备份':'旧版主档'} · ${c.valid?'可迁移':esc(c.error)}</p>${c.valid?`<button class="primary" data-confirm-migrate="${slot}" data-source="${esc(c.id)}">从此记录迁移</button>`:''}</article>`).join('')}</div><div class="actions"><button data-bundle="${slot}">导出原始资料</button><button data-slots>返回</button></div>`);}
async function migrate(slot,source){if(busy)return;busy=true;try{if(!await detach())return;const r=await persistence.migrateLegacy(Number(slot),{source,confirmed:true});if(r.ok){adopt(r.state,Number(slot));toast('旧卷已保留，新版迁移完成。');}else toast(r.message,true);}finally{busy=false;}}
const backupSnapshots=new Map();
function showBackups(slot){if(haveSession&&dirty&&!volatile&&persistence.canWrite)saveNow({silent:true});const v=persistence.inspect(slot),backups=[...v.backups,...v.preserved];backupSnapshots.clear();for(const b of backups){try{backupSnapshots.set(`${slot}:${b.id}`,{raw:persistence.exportSlot(Number(slot),{source:b.id}),meta:b.meta});}catch{}}openModal(`世界 ${slot} · 档案与恢复`,`${v.error?`<p class="warning">${esc(v.error)}</p>`:''}<p>恢复前会保留当前原始记录。只会从校验通过的记录恢复，不会自动抹去损坏档案。</p><div class="settings-list">${backups.length?backups.map(b=>`<article>${slotMeta(b.meta)}<small>${b.valid?'完整可用':esc(b.error)}${b.meta?.checkpoint?' · '+esc(b.meta.checkpoint):''}</small><div class="actions">${b.valid?`<button data-restore="${slot}" data-source="${esc(b.id)}">恢复此记录</button>`:''}<button data-export-source="${slot}" data-source="${esc(b.id)}">导出原文</button></div></article>`).join(''):'<p>目前没有滚动备份。首次保存后，每次更新会保留最近三份有效记录。</p>'}</div><div class="actions"><button data-bundle="${slot}">导出全部恢复资料</button><button data-slot-new="${slot}">另起新卷</button><button data-slots>返回世界列表</button></div>`);}
function confirmRestore(slot,id){const b=backupSnapshots.get(`${slot}:${id}`);if(!b){toast('请重新打开备份列表选择记录。',true);return;}openModal('恢复这段山居岁月？',`${slotMeta(b?.meta)}<p>当前主档原文会保留，世界将回到所选记录。</p><div class="actions"><button class="primary" data-confirm-restore="${slot}" data-source="${esc(id)}">确认恢复</button><button data-slot-backups="${slot}">返回备份列表</button></div>`);}
async function recover(slot,id){if(busy)return;const fixed=backupSnapshots.get(`${slot}:${id}`);if(!fixed){toast('请重新选择备份记录。',true);return;}busy=true;try{if(!await detach())return;const r=await persistence.importInto(Number(slot),fixed.raw,{confirmed:true});if(r.ok){adopt(r.state,Number(slot));toast('已恢复所选记录。');}else toast(r.message,true);}finally{busy=false;}}
function download(text,name){const blob=new Blob([text],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportText(){try{openModal('藏卷 · 存档文本',`<p>这是当前窗口的完整进度。下载不可用或本机空间不足时，可全选复制并另存为 JSON 文件，再用「粘贴存档」恢复。</p><label for="export-save">完整存档文本</label><textarea id="export-save" rows="9" readonly spellcheck="false">${esc(persistence.exportState(state))}</textarea><div class="actions"><button data-select-export>全选文本</button><button data-settings>返回设置</button></div>`);}catch(e){toast('无法读取当前状态：'+e.message,true);}}
function exportCurrent(){try{download(persistence.exportState(state),`云岫仙府-世界${activeSlot||'试玩'}-${new Date().toISOString().slice(0,10)}.json`);toast('已导出当前内存中的完整进度。');}catch(e){toast('无法导出当前状态：'+e.message,true);}}
let pendingImport=null;
async function readImport(file){if(!file)return;if(file.size>MAX_IMPORT_BYTES){toast('存档文件最多 2 MB。',true);return;}try{const text=await file.text(),r=persistence.parseImport(text);if(!r.ok){toast(r.message||r.error,true);return;}pendingImport=text;openModal('导入预览 · 选择世界档位',`${slotMeta(r.meta)}<p>导入前先校验完整档案。请选择落档位置；已有世界会保留备份。</p><div class="slot-grid">${persistence.listSlots().map(v=>`<article class="slot-card"><h3>世界 ${v.slot}</h3>${slotMeta(v.meta)}<button data-import-slot="${v.slot}">${v.status==='empty'?'导入此空档':'替换此档位'}</button></article>`).join('')}</div>${previewScope?'<p class="ui-note">验收试读只替换当前窗口，不写入本机档位；当前未保存的验收进度会结束。</p><button data-qa-read>验收试读（不写入本机）</button>':''}<button data-slots>取消</button>`);}catch(e){toast(e.message,true);}}
async function importInto(slot){if(busy||!pendingImport)return;busy=true;try{if(!await detach())return;const r=await persistence.importInto(Number(slot),pendingImport,{confirmed:true});if(r.ok){pendingImport=null;adopt(r.state,Number(slot));toast('存档已导入。');}else toast(r.message,true);}finally{busy=false;}}
function performanceText(){const d=diagnostics.snapshot();return d.ready?`本窗口可见画面采样 ${d.samples} 帧 · 平均 ${d.fps} FPS · 帧间隔 P95 ${d.frameP95Ms.toFixed(1)} ms · 游戏处理 P95 ${d.workP95Ms.toFixed(1)} ms。`:'画面采样不足，回到场景后再查看。';}
function settings(){openModal('山居设置',`<div class="settings-list"><article><h3>当前世界 ${activeSlot||'· 试玩'}</h3><p>${esc(volatile?'仅内存试玩，关闭网页前请导出':persistence.status)}</p><small>${esc(timeText(persistence.savedAt))}</small><div class="actions"><button data-save>立即保存</button><button data-export>导出当前进度</button><button data-export-text>查看存档文本</button>${saveError&&!volatile?'<button data-memory-continue>转为内存继续</button>':''}<button data-import>导入文件</button><button data-paste-import>粘贴存档</button><button data-slots>切换世界</button>${activeSlot?`<button data-slot-backups="${activeSlot}">备份与恢复</button>`:''}${haveSession&&!volatile&&!persistence.canWrite?`<button class="primary" data-slot-takeover="${activeSlot}">请求接管</button>`:''}</div></article><article><h3>视听与阅读</h3><label><input type="checkbox" data-pref="music" ${preferences.music?'checked':''}> 山间清音</label><label class="volume-control">音乐音量<input type="range" min="0" max="1" step="0.05" data-pref="musicVolume" value="${preferences.musicVolume}" aria-label="音乐音量"></label><label><input type="checkbox" data-pref="sfx" ${preferences.sfx?'checked':''}> 操作音效</label><label class="volume-control">音效音量<input type="range" min="0" max="1" step="0.05" data-pref="sfxVolume" value="${preferences.sfxVolume}" aria-label="音效音量"></label><label><input type="checkbox" data-pref="reducedMotion" ${preferences.reducedMotion?'checked':''}> 减少动态效果</label><label>文字大小 <select data-pref="textScale"><option value="1" ${preferences.textScale===1?'selected':''}>标准</option><option value="1.1" ${preferences.textScale===1.1?'selected':''}>较大</option><option value="1.2" ${preferences.textScale===1.2?'selected':''}>大字</option></select></label></article><article><h3>当前画面运行情况</h3><p class="runtime-metrics">${esc(performanceText())}</p><p>统计来自本窗口的可见画面，后台与长时间中断不计入。低性能设备可减少动态效果。</p></article><article><h3>续玩方式</h3><p>每 5 秒、重要操作和切到后台时尝试保存。关页后下次可从「继续修行」续玩；关闭期间不结算离线收益。换设备请导出并导入文件。</p><p>存档仅属于本浏览器与此网址。无痕模式、清理网站数据或浏览器存储限制可能影响保留。</p></article></div><button class="primary" data-resume>回到山中</button>`);}

const openingAudio=createOpeningAudio({enabled:()=>preferences.sfx,volume:()=>preferences.sfxVolume,visible:()=>modal.open&&modal.classList.contains('cinematic')&&!document.hidden});
const audio=(()=>{let ctx=null,ambient=null,lastNote=0,step=0;function init(){if(!ctx){const C=window.AudioContext||window.webkitAudioContext;if(C)ctx=new C();}if(ctx?.state==='suspended')ctx.resume().catch(()=>{});return ctx;}function note(freq,duration,volume,type='sine'){if(!ctx||ctx.state!=='running'||volume<=0)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,ctx.currentTime);g.gain.linearRampToValueAtTime(volume,ctx.currentTime+.05);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+duration);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration);}return {prologue:page=>openingAudio.play(page),effect(kind){if(!preferences.sfx)return;init();note(kind==='battle'?146.83:329.63,.3,.035*preferences.sfxVolume,'triangle');},sync(){if(modal.open&&modal.classList.contains('cinematic')){openingAudio.play(Number(modal.dataset.introScene)||0);return;}openingAudio.stop();if((preferences.music||preferences.sfx)&&haveSession&&!document.hidden&&!modal.open)init();else if(ctx)ctx.suspend().catch(()=>{});},suspend(){openingAudio.stop();ctx?.suspend().catch(()=>{});},tick(now){if(!preferences.music||!ctx||ctx.state!=='running'||document.hidden||modal.open||now-lastNote<3100)return;lastNote=now;const notes=[196,220,261.63,293.66,329.63,293.66,261.63,220];note(notes[step++%notes.length],4,.012*preferences.musicVolume);}};})();

ui=createEAUI({getState:()=>state,act,setTab,getTab:()=>tab,openModal,closeModal,toast,getMode:()=>mode,setMode,chooseBuild,selectScene,getScene:()=>scene,getSelection:()=>selection,locate,openPerson:id=>ui.openPerson(id),settings,saveNow,refresh,startRelocate,interact,cancelInteraction,getDiagnostics:()=>diagnostics.snapshot(),approachRegion,ensureRunning,observeWork,isMemorySession:()=>volatile,getIntroSoundEnabled:()=>preferences.sfx,presentPrologue:page=>{modal.dataset.introScene=String(page);audio.prologue?.(page);},clearSelection:()=>{selection=null;}});
const canvas=$('world');
function interact(kind,id,choice){if(scene!=='map')selectScene('map');world.setOverview(false);setMode('inspect');return act('requestSceneInteraction',kind,id,choice,kind==='person'?world.getPersonPosition?.(id):null);}
function cancelInteraction(){const result=act('cancelSceneInteraction');if(result!==null&&state.master.action==='walk')act('masterAction','rest');return result;}
function approachRegion(){const active=SIM.explorationOptions(state)?.active;if(!active?.landmark)return;selectScene('journey');ui.fold();if(active.canInteract){pendingRegionDialogue=null;ui.openRegionInteraction();return;}pendingRegionDialogue=active.id;if(act('moveExploration',active.landmark.x,active.landmark.y)!==null&&state.speed===0){state.speed=1;dirty=true;}refresh(true);}
function checkRegionDialogue(){if(!pendingRegionDialogue||modal.open||hiddenPause||document.hidden)return;const active=SIM.explorationOptions(state)?.active;if(active?.id!==pendingRegionDialogue||state.combat){pendingRegionDialogue=null;return;}if(active.canInteract){pendingRegionDialogue=null;ui.openRegionInteraction();}}
function checkSceneInteraction(now){
 if(!haveSession||modal.open||hiddenPause||document.hidden||!volatile&&!persistence.canWrite||!state.master.sceneIntent||now-lastIntentCheck<180)return;lastIntentCheck=now;
 const intent=state.master.sceneIntent,personPosition=intent.kind==='person'?world.getPersonPosition?.(intent.id):null;
 if(intent.kind==='person'&&!personPosition){cancelInteraction();toast('此人已离开山院，归院后再交谈。');return;}
 const ready=sceneInteractionReady(state,personPosition);
 if(ready?.cancelled){cancelInteraction();toast(ready.reason,true);return;}
 if(ready){act('cancelSceneInteraction');if(ready.option.command&&act(ready.option.command,...ready.option.args)===null)return;ui.finishSceneInteraction(ready.option,ready.target,ready.intent);return;}
 if(!state.master.scenic?.path?.length&&state.master.action!=='walk'){const target=sceneInteractionTarget(state,intent.kind,intent.id);if(target)act('requestSceneInteraction',intent.kind,intent.id,intent.action,personPosition);}
}
world=createWorldRenderer(canvas,{getState:()=>state,getMode:()=>mode,getSelection:()=>selection,getCampaignScene:s=>scene==='journey'?SIM.getCampaignScene(s):null,getPrefs:()=>preferences,getHomeInteractions:SIM.homeInteractions,getPreview:preview,onLoad:failed=>{const el=$('asset-status');if(el){el.hidden=!failed.length;el.innerHTML=failed.length?'<span>部分画卷未载入，已保留可用内容</span><button type="button" data-retry-assets>重试加载</button>':'';}}});
mapInputStop=attachMapInput(canvas,{pan:world.pan,enabled:()=>haveSession&&!modal.open,onHover:e=>{world.setHover(e);updatePlacement();},onDragChange:v=>canvas.classList.toggle('dragging',v),onActivate:e=>{
 const picked=world.pick(e);if(picked.distance>75){toast('请点击山路或交互点附近。');return;}if(scene==='valley'||scene==='lake'){setTab('explore');toast('此处为舆图预览，在「山外」选择目的地出行。');return;}
 if(scene==='journey'){const current=SIM.getCampaignScene(state);if(current?.type==='combat'&&current.interactive===false){toast('此战已结束，请先确认战果。');return;}if(state.combat?.status==='active'){act('combatAction',picked.kind==='enemy'?'attack':'move',picked.kind==='enemy'?picked.id:{x:picked.x,y:picked.y});}else if(state.world.exploration?.status==='exploring'){act('moveExploration',picked.x,picked.y);if(picked.kind==='landmark'){if(picked.id==='exit')act('leaveRegion');else ui.openRegionInteraction();}}else toast('正在途中，请稍候。');return;}
 if(mode==='build'||mode==='move'){const r=mode==='move'?act('relocate',relocateId,picked.x,picked.y):act('build',buildType,picked.x,picked.y);if(r!==null){const name=SIM.BUILDINGS[r.type]?.name;finishPlacement();selection={kind:'building',id:r.id};ui.renderDetail(selection);world.focus(r.x,r.y);toast((name||'设施')+'已经落成；入口连通，可观察门人的自主选择。');}return;}
 if(mode==='walk'){const p=world.screenPoint(e);act('moveScenicMaster',p.x,p.y);return;}
 if(picked.kind==='story-object'){interact('building',picked.buildingId,'story');return;}
 if(picked.kind==='peak'||picked.kind==='overview'){setTab('sect');return;}if(picked.kind==='person'){selection={kind:'person',id:picked.id};ui.renderDetail(selection);ui.openSceneInteraction('person',picked.id);}else if(picked.kind==='building'){selection={kind:'building',id:picked.id};ui.renderDetail(selection);}else if(picked.kind==='area'){setTab(picked.id==='gate'?'explore':picked.id==='meditation'?'self':'build');toast('此处尚无已建成设施，可在营造中筹建。');}else{selection=null;ui.renderDetail(null);}refresh(true);
}});
canvas.addEventListener('wheel',e=>{if(modal.open)return;e.preventDefault();world.setZoom(e.deltaY>0?-.07:.07);world.render(performance.now(),true);},{passive:false});
canvas.addEventListener('pointerleave',()=>{world.setHover(null);updatePlacement();});
$('close-modal').addEventListener('click',closeModal);modal.addEventListener('cancel',e=>{if(!haveSession)e.preventDefault();});modal.addEventListener('close',()=>{if(modal.open)return;lastFrame=performance.now();runtimeClock.resume(lastFrame);audio.sync();});
$('import-file').addEventListener('change',e=>{readImport(e.target.files[0]);e.target.value='';});

document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;try{
 if('slots'in d)showSlots();else if('slotOpen'in d)await openSlot(d.slotOpen);else if('slotTakeover'in d)await openSlot(d.slotTakeover,true);else if('slotNew'in d)showNew(d.slotNew);else if('confirmNew'in d)await createSlot(d.confirmNew);else if('slotMigrate'in d)showMigration(d.slotMigrate);else if('confirmMigrate'in d)await migrate(d.confirmMigrate,d.source);else if('slotRecover'in d||'slotBackups'in d)showBackups(d.slotRecover||d.slotBackups);else if('restore'in d)confirmRestore(d.restore,d.source);else if('confirmRestore'in d)await recover(d.confirmRestore,d.source);else if('slotReadonly'in d){const v=persistence.inspect(Number(d.slotReadonly));if(v.state)adopt(v.state,Number(d.slotReadonly),{readonly:true});}
 else if('memory'in d){if(await detach())adopt(SIM.initial({name:d.memoryName||'沈砚'}),null,{memory:true,fresh:true});}
 else if('discardSession'in d){haveSession=false;dirty=false;volatile=false;persistence.release();showSlots();}else if('resume'in d)closeModal();else if('save'in d)saveNow();else if('export'in d)exportCurrent();else if('exportText'in d)exportText();else if('selectExport'in d){$('export-save').focus();$('export-save').select();}else if('settings'in d)settings();else if('memoryContinue'in d)openModal('暂续此卷',`<p>当前进度将只保留在此窗口中，本机旧档和备份保持原样。关闭网页前，请导出文件或复制存档文本；准备好后可手动继续时间。</p><div class="actions"><button data-export>先导出当前进度</button><button data-export-text>查看存档文本</button><button class="primary" data-confirm-memory>确认转为内存继续</button><button data-settings>返回设置</button></div>`);else if('confirmMemory'in d){persistence.release();volatile=true;dirty=true;state.speed=0;saveError=false;saveMessage='仅内存试玩 · 请导出';lastGood=clone(state);closeModal();refresh(true);toast('已转为内存继续，关闭前请导出当前进度。');}else if('pasteImport'in d)openModal('粘贴存档',`<p>粘贴导出的完整 JSON 存档。校验后选择档位，替换前会再次确认。</p><label for="paste-save">存档内容</label><textarea id="paste-save" rows="8" spellcheck="false" maxlength="2097152"></textarea><button class="primary" data-parse-paste>校验并预览</button>`);else if('parsePaste'in d){const text=$('paste-save').value;readImport({size:new TextEncoder().encode(text).length,text:async()=>text});}else if('import'in d)$('import-file').click();else if('qaRead'in d&&previewScope&&pendingImport){const parsed=persistence.parseImport(pendingImport);if(parsed.ok){persistence.release();pendingImport=null;adopt(parsed.state,null,{memory:true,fresh:true});state.speed=0;refresh(true);}}else if('importSlot'in d){const slot=Number(d.importSlot);openModal('确认导入',`<p>将导入世界 ${slot}，现有主档会保留备份。</p><button class="primary" data-confirm-import="${slot}">确认导入</button><button data-slots>取消</button>`);}else if('confirmImport'in d)await importInto(d.confirmImport);else if('bundle'in d)download(persistence.exportBundle(Number(d.bundle)),`云岫-世界${d.bundle}-恢复资料.json`);else if('exportSource'in d)download(backupSnapshots.get(`${d.exportSource}:${d.source}`)?.raw??persistence.exportSlot(Number(d.exportSource),{source:d.source}),`云岫-备份原文.json`);
 else if('placementPreview'in d){const plot=pendingRecommendation&&pendingRecommendation.type===d.placementPreview?pendingRecommendation:null;beginPlacement(d.placementPreview,plot);}else if('placementFree'in d)beginPlacement(d.placementFree);else if(b.id==='placement-confirm'&&pendingRecommendation){const p=pendingRecommendation,result=act('build',p.type,p.x,p.y);if(result!==null){finishPlacement();selection={kind:'building',id:result.id};ui.renderDetail(selection);world.focus(result.x,result.y);toast(SIM.BUILDINGS[result.type].name+'已经落成。门人会自主考虑前来照料。');}}else if('introSound'in d){preferences.sfx=!preferences.sfx;persistPreferences();audio.prologue?.(Number(modal.dataset.introScene));b.textContent=preferences.sfx?'关闭雨声与音效':'开启雨声与音效';b.setAttribute('aria-pressed',String(preferences.sfx));}
 else if('retryAssets'in d){b.disabled=true;await world.retryAssets?.();b.disabled=false;refresh(true);}
 else if('relocate'in d)startRelocate(d.relocate);
 else if('speed'in d){if(mayAct()){state.speed=Number(d.speed);dirty=true;refresh(true);}}
 else if(b.id==='pause'){if(mayAct()){state.speed=state.speed?0:1;dirty=true;refresh(true);}}
 else if(b.id==='estate-overview'){selectScene('map');setMode('inspect');world.setOverview();ui.fold();world.render(performance.now(),true);}else if(b.id==='settings')settings();else if(b.id==='zoom-in')world.setZoom(.14);else if(b.id==='zoom-out')world.setZoom(-.14);else if(b.id==='recenter'){const p=scene==='journey'?SIM.getCampaignScene(state)?.player:state.master.position;if(p)world.focus(p.x,p.y,scene==='journey');else world.recenter();}else if(b.id==='grid-toggle'){const g=world.setGrid();b.setAttribute('aria-pressed',String(g));}else if(b.id==='master-mode'){selectScene('map');setMode(mode==='walk'?'inspect':'walk');}else if(b.id==='cancel-build')finishPlacement();
 }catch(error){toast(error.message,true);}});
document.addEventListener('input',e=>{const key=e.target.dataset.pref;if(['musicVolume','sfxVolume'].includes(key)){preferences[key]=Number(e.target.value);persistPreferences();}});
document.addEventListener('change',e=>{const key=e.target.dataset.pref;if(key&&Object.hasOwn(preferences,key)){preferences[key]=e.target.type==='checkbox'?e.target.checked:Number(e.target.value);persistPreferences();}});
let lastKeyMove=0;
document.addEventListener('keydown',e=>{if(modal.open||e.target.closest('input,select,textarea,[contenteditable="true"]')||!haveSession)return;if(e.key==='Escape'){if(state.master.sceneIntent)cancelInteraction();mode='inspect';buildType=null;relocateId=null;refresh(true);return;}if(e.code==='Space'&&!e.target.closest('button')){e.preventDefault();$('pause').click();return;}const delta={w:[0,-1],a:[-1,0],s:[0,1],d:[1,0],ArrowUp:[0,-1],ArrowLeft:[-1,0],ArrowDown:[0,1],ArrowRight:[1,0]}[e.key];if(delta&&performance.now()-lastKeyMove>150){e.preventDefault();lastKeyMove=performance.now();if(scene==='journey'){const p=SIM.getCampaignScene(state)?.player;if(p&&!(state.combat&&state.combat.status!=='active'))act(state.combat?.status==='active'?'combatAction':'moveExploration',...(state.combat?.status==='active'?['move',{x:p.x+delta[0]*1.5,y:p.y+delta[1]*1.5}]:[p.x+(delta[0]||delta[1])*1.5,4]));}else if(scene==='map'){world.setOverview(false);setMode('walk');{const p=state.master.scenic?.path?.at(-1)||scenicPosition(state.master);act('moveScenicMaster',p.x+delta[0]*45,p.y+delta[1]*45);}}}if(scene==='journey'&&state.combat?.status==='active'){const action={j:'attack',k:'spell',l:'dodge',h:'guard',r:'retreat'}[e.key.toLowerCase()];if(action){e.preventDefault();act('combatAction',action);}}});

document.addEventListener('visibilitychange',()=>{hiddenPause=document.hidden;if(document.hidden){runtimeClock.suspend();mapInputStop?.cancel?.();if(haveSession&&!volatile&&persistence.canWrite)saveNow({silent:true});audio.suspend();}else{lastFrame=performance.now();runtimeClock.resume(lastFrame);audio.sync();}});
window.addEventListener('pagehide',()=>{resumeAfterPagehide=haveSession&&!volatile;runtimeClock.suspend();mapInputStop?.cancel?.();audio.suspend();parked=resumeAfterPagehide?{state:clone(state),saved:false,head:persistence.captureHead()}:null;const r=persistence.release(resumeAfterPagehide?{state}:{});if(parked)parked.saved=!!r.ok&&r.code==='saved';});
window.addEventListener('pageshow',async e=>{if(e.persisted&&resumeAfterPagehide&&activeSlot){const r=await persistence.open(activeSlot);if(parked&&!parked.saved){state=parked.state;state.speed=0;haveSession=true;dirty=true;saveError=true;saveMessage='离开前保存失败，内存进度仍保留，请重试或导出。';if(r.ok&&persistence.matchesHead(parked.head)){saveNow({silent:true});}else if(r.ok){persistence.release();saveMessage='另一窗口已有更新；旧内存进度已保留并暂停，请先导出，再选择恢复记录。';}toast(saveMessage,!persistence.canWrite);updateSaveStatus();}else if(r.ok&&r.state)adopt(r.state,activeSlot);else{state.speed=0;toast(r.message,true);updateSaveStatus();}parked=null;}lastFrame=performance.now();runtimeClock.resume(lastFrame);});
document.addEventListener('freeze',()=>{runtimeClock.suspend();mapInputStop?.cancel?.();if(haveSession&&!volatile&&persistence.canWrite)saveNow({silent:true});});
document.addEventListener('resume',()=>{lastFrame=performance.now();runtimeClock.resume(lastFrame);});
function loop(now){const started=performance.now(),timing=runtimeClock.next(now),dt=timing.dt;lastFrame=now;if(haveSession&&!modal.open&&!hiddenPause&&(volatile||persistence.canWrite)&&state.speed){try{const prev=state.time;SIM.tick(state,dt);if(state.time!==prev){dirty=true;if(!state.world.exploration&&scene==='journey'&&!state.combat)selectScene('map');}}catch(e){state=clone(lastGood);state.speed=0;toast('世界已暂停，保留上个完整状态：'+e.message,true);}}
 if(now-lastUI>550){lastUI=now;ui.render();updateSaveStatus();updatePlacement();}if(haveSession&&dirty&&!volatile&&persistence.canWrite&&now-lastAuto>5000){lastAuto=now;saveNow({silent:true});}const painted=world.render(now);checkSceneInteraction(now);checkRegionDialogue();if(haveSession&&!modal.open&&!hiddenPause&&(volatile||persistence.canWrite))ui.maybeNarrative?.();audio.tick(now);if(painted){const paintElapsed=lastPaintAt===null?0:now-lastPaintAt;lastPaintAt=now;diagnostics.record({elapsedMs:paintElapsed,workMs:performance.now()-started,visible:haveSession&&!document.hidden&&!modal.open,droppedGap:timing.droppedGap||paintElapsed>1000});}requestAnimationFrame(loop);}
persistPreferences();refresh(true);showSlots();requestAnimationFrame(loop);
