import{TYPES,RESOURCE,RECIPES,EXPEDITIONS,buildingLock,isAway,sectUpgradeCost,upgradeSect,craft,usePill,expeditionLock,startExpedition,cancelExpedition,resolveEncounter,canPay}from'./sect-sim.mjs?v=ea-160-courtyard-20261009-r37';
import{startMasterTravel,resolveMasterEncounter,cancelMasterTravel,offerRoute}from'./sect-sim.mjs?v=ea-160-courtyard-20261009-r37';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
export function createExpansion(api){
 const {getState,getTab,setTab,chooseBuild,openModal,closeModal,mutate,toast,esc,resetCamera,cancelBuild}=api;
 let scene='map',selectedRoute='valley_path';
 const names={map:'云岫别院',valley:'青萝幽谷',lake:'寒潭遗境'};
 const descriptions={map:'晴 · 灵气充盈',valley:'草木有灵 · 循溪问道',lake:'月照寒潭 · 古阵长眠'};
 const fmt=c=>Object.entries(c).map(([k,v])=>`${RESOURCE[k]} ${v}`).join(' · ');
 const progress=(n,max)=>`<div class="progress"><div style="width:${Math.max(0,Math.min(100,n/max*100))}%"></div></div>`;
 const bind=(selector,fn)=>$$(selector).forEach(el=>el.onclick=()=>fn(el));
 function selectScene(next){if(!names[next])return;scene=next;resetCamera();cancelBuild();$('#detail').classList.remove('mobile-open');if(scene!=='map'){selectedRoute=Object.keys(EXPEDITIONS).find(k=>EXPEDITIONS[k].scene===scene);setTab('explore');}else api.refresh();}
 bind('[data-scene]',el=>selectScene(el.dataset.scene));
 $('#fold-panel').onclick=()=>{const folded=$('.bottom-panel').classList.toggle('folded');$('#fold-panel').textContent=folded?'⌃':'⌄';$('#fold-panel').setAttribute('aria-label',folded?'展开管理面板':'收起管理面板');};
 function travelDialog(id){const s=getState(),r=EXPEDITIONS[id],m=s.master;selectedRoute=id;const lock=expeditionLock(s,id);if(lock){toast(lock);return;}if(m.journey){if(m.journey.status==='encounter')return encounterDialog();toast('掌门已有行程，可从上方行程条查看。');return;}
 openModal(r.name,`<div class="route-cover ${r.scene}"><span>掌门亲往 · ${r.duration} 秒</span></div><p>${r.description} 掌门亲历的奇遇由你作出选择。</p><p>出行消耗：${fmt(r.cost)} · 精力 ${r.energy}</p><p>基础收获：${fmt(r.reward)} · 声望 ${r.reputation}</p><button id="travel-confirm" class="primary full">掌门启程</button>`);
 $('#travel-confirm').onclick=()=>{try{startMasterTravel(s,id);closeModal();scene=r.scene;resetCamera();setTab('explore');toast('掌门已启程。');}catch(err){toast(err.message);}};
 }
 function encounterDialog(){const s=getState(),e=s.master.journey;if(e?.status!=='encounter')return;const r=EXPEDITIONS[e.routeId];openModal('掌门奇遇 · 灵迹乍现',`<div class="route-cover ${r.scene}"><span>${r.name}</span></div><p>${r.scene==='valley'?'溪水尽头，古木灵纹亮起，幽径深处传来铃音。':'寒潭浮现残缺阵纹，月色映出水下的晶簇。'}如何继续？</p><button class="encounter-choice" data-choice="careful"><strong>循道而行</strong><span>保留精力，获得原定收获。</span></button><button class="encounter-choice" data-choice="bold" ${s.master.energy<10?'disabled':''}><strong>深入灵迹</strong><span>额外消耗 10 精力，资源收获增加 50%。</span></button>`);bind('[data-choice]',el=>{try{resolveMasterEncounter(s,el.dataset.choice);closeModal();api.refresh();}catch(err){toast(err.message);}});}
 function pillDialog(discipleId){const s=getState(),d=s.disciples.find(d=>d.id===discipleId);if(isAway(s,d.id)){toast('此门人正在游历，归山后可服丹。');return;}openModal(`${d.name} · 服丹调息`,`<p>当前修为 ${Math.floor(d.xp)} / ${d.realm*100}，精力 ${Math.floor(d.energy)} / 100。修为满时，请先突破，以免浪费药力。</p>${Object.entries(RECIPES).map(([id,r])=>`<button class="encounter-choice" data-pill-use="${id}" ${s.pills[id]<1?'disabled':''}><strong>${r.name} <small>× ${s.pills[id]}</small></strong><span>${r.description}</span></button>`).join('')}`);bind('[data-pill-use]',el=>{try{usePill(s,el.dataset.pillUse,d.id);closeModal();api.refresh();toast(`${d.name}已服丹调息。`);}catch(e){toast(e.message);}});}
 function renderAlchemy(){const s=getState(),has=s.buildings.some(b=>b.type==='alchemy'),c=s.crafting;$('#bottom-content').innerHTML=`<div class="craft-layout"><div class="furnace-status"><span class="seal-glyph">丹</span><h3>${c?'炉火正旺':has?'丹炉待启':'丹房未立'}</h3><p>${c?`${RECIPES[c.recipeId].name} · 尚需 ${Math.ceil(c.remaining)} 秒`:has?'以草木之精，养修行之身。':'先在主峰营造丹霞炉。'}</p>${c?progress(c.total-c.remaining,c.total):!has?'<button id="build-alchemy" class="primary">营造丹霞炉</button>':'<span class="subtle">升级丹霞炉可缩短炼制时间</span>'}</div><div class="recipe-list">${Object.entries(RECIPES).map(([id,r])=>`<article class="recipe-card"><div class="recipe-head"><span class="pill-orb ${id}" aria-hidden="true">${id==='qi'?'气':'息'}</span><div><h3>${r.name}</h3><small>丹囊库存 × ${s.pills[id]}</small></div></div><p>${r.description}</p><div class="cost-line">${fmt(r.cost)} · ${r.duration}秒</div><button class="primary" data-craft="${id}" ${!has||!!c||s.sect.level<r.sectLevel||!canPay(s,r.cost)?'disabled':''}>${s.sect.level<r.sectLevel?'宗门二阶解锁':c?'丹炉炼制中':'开炉炼丹'}</button></article>`).join('')}</div></div>`;if($('#build-alchemy'))$('#build-alchemy').onclick=()=>chooseBuild('alchemy');bind('[data-craft]',el=>mutate(()=>craft(s,el.dataset.craft)));}
 function renderExplore(){const s=getState();$('#bottom-content').innerHTML=`<div class="route-list">${Object.entries(EXPEDITIONS).map(([id,r])=>{const lock=expeditionLock(s,id);return`<article class="route-card ${r.scene} ${selectedRoute===id?'chosen':''}"><span class="route-zone">${names[r.scene]} · ${r.duration}秒</span><h3>${r.name}</h3><p>${r.description}</p><div class="route-meta">炼气${r.minRealm}层 · 精力 ${r.energy}</div><div class="route-loot">${fmt(r.reward)}</div><div class="route-actions"><button class="secondary" data-view-route="${id}">观境</button><button class="primary" data-route="${id}" ${lock?'disabled':''}>${lock||'亲往'}</button><button class="secondary" data-offer-route="${id}" ${lock?'disabled':''}>${s.doctrine.routes.includes(id)?'撤下差事':'发布差事'}</button></div></article>`;}).join('')}</div>`;bind('[data-offer-route]',el=>mutate(()=>offerRoute(s,el.dataset.offerRoute)));bind('[data-view-route]',el=>{selectedRoute=el.dataset.viewRoute;scene=EXPEDITIONS[selectedRoute].scene;resetCamera();api.refresh();});bind('[data-route]',el=>travelDialog(el.dataset.route));}
 function renderSect(){const s=getState(),c=sectUpgradeCost(s);$('#bottom-content').innerHTML=`<div class="sect-layout"><div class="sect-emblem"><span>${['','初','盛','玄'][s.sect.level]}</span><div><h3>青岚仙府</h3><p>${['','初立山门','灵境初成','玄门气象'][s.sect.level]} · ${s.sect.level}阶</p></div></div><div class="sect-growth"><div class="stage-line">${['立府','开境','承道'].map((n,i)=>`<span class="${s.sect.level>i?'lit':''}">${['壹','贰','叁'][i]} · ${n}</span>`).join('')}</div><div class="detail-label"><span>宗门声望</span><span>${s.sect.reputation}${c?' / '+c.reputation:''}</span></div>${progress(s.sect.reputation,c?.reputation||s.sect.reputation||1)}<p>${c?s.sect.level===1?'二阶解锁寒潭遗境、灵泉与灵息丹。':'三阶成就玄门气象，继续培育门人与仙府。':'已达当前最高品阶，仙途仍可继续。'}</p></div><div class="sect-upgrade">${c?`<p class="cost-line">晋升所需<br>${fmt(c.cost)}</p><button id="sect-upgrade" class="primary" ${s.sect.reputation<c.reputation||!canPay(s,c.cost)?'disabled':''}>晋升宗门</button>`:'<span class="max-sect">玄门已成</span>'}<small>声望来自宗门纪事与游历</small></div></div>`;if($('#sect-upgrade'))$('#sect-upgrade').onclick=()=>mutate(()=>{upgradeSect(s);toast('宗门气象焕然一新，新的灵境已开启。');});}
 function render(){const s=getState(),tab=getTab();$('.bottom-panel').dataset.tab=tab;$$('[data-scene]').forEach(el=>{el.classList.toggle('active',el.dataset.scene===scene);el.setAttribute('aria-pressed',String(el.dataset.scene===scene));});$('#scene-title').innerHTML=`${names[scene]}<span class="small-seal">${scene==='map'?'府':'境'}</span>`;$('.eyebrow').textContent=`${scene==='map'?'云岫山':'山外山'} · 宗门${s.sect.level}阶 · 声望 ${s.sect.reputation}`;$('#scene-weather').textContent=descriptions[scene];$('#grid-toggle').disabled=scene!=='map';
  const journey=s.master.journey,npc=s.expedition,banner=$('#expedition-banner');banner.classList.toggle('hidden',!journey&&!npc);if(journey){banner.classList.toggle('encounter',journey.status==='encounter');banner.textContent=journey.status==='encounter'?'✦ 掌门遇见灵迹 · 点击抉择':`掌门 · ${EXPEDITIONS[journey.routeId].name} · 还需 ${Math.ceil(journey.remaining)} 秒`;banner.onclick=()=>{if(journey.status==='encounter')return encounterDialog();openModal('掌门行程',`<p>正在「${EXPEDITIONS[journey.routeId].name}」游历，尚需 ${Math.ceil(journey.remaining)} 秒。</p><button id="cancel-master-travel" class="secondary full">提前归院（不结算奖励）</button>`);$('#cancel-master-travel').onclick=()=>{cancelMasterTravel(s);closeModal();api.refresh();};};}else if(npc){const d=s.disciples.find(d=>d.id===npc.discipleId);banner.classList.remove('encounter');banner.textContent=`${d.name}自主游历 · ${EXPEDITIONS[npc.routeId].name}`;banner.onclick=()=>openModal('门人行程',`<p>${esc(d.name)}自行接下游历差事，途中选择将依据其性格作出。</p><p>${esc(d.mind.reason)}</p>`);}
  if(tab==='alchemy')renderAlchemy();if(tab==='explore')renderExplore();
  if(tab==='build')$$('[data-build]').forEach(el=>{const type=el.dataset.build;if(type==='hall')return;const lock=buildingLock(s,type);el.classList.toggle('locked',!!lock);if(lock)el.title=lock;});
  if(scene!=='map'){const r=EXPEDITIONS[selectedRoute];$('#detail').innerHTML=`<div class="detail-top"><h3>${r.name}</h3><span class="level">${r.sectLevel}阶灵境</span></div><div class="route-preview ${scene}"></div><p class="detail-desc">${r.description}</p><div class="detail-label"><span>历练门槛</span><span>炼气${r.minRealm}层</span></div><div class="detail-label"><span>预计耗时</span><span>${r.duration}秒</span></div><p class="reward-line">${fmt(r.reward)}</p><button id="detail-travel" class="primary full">${expeditionLock(s,selectedRoute)||'掌门亲往'}</button>`;$('#detail-travel').onclick=()=>travelDialog(selectedRoute);}
  if(['alchemy','sect','explore'].includes(tab))$('#bottom-summary').textContent=tab==='alchemy'?`丹囊 ${s.pills.qi+s.pills.spirit} 枚`:tab==='sect'?`已游历 ${s.stats.expeditions} 次`:'点击地标或选择下方路线';
 }
 function draw(ctx,now){const s=getState();for(const[id,r]of Object.entries(EXPEDITIONS).filter(([,r])=>r.scene===scene)){const selected=selectedRoute===id,locked=!!expeditionLock(s,id);ctx.save();ctx.translate(r.x,r.y);ctx.fillStyle=selected?'#d3b673ee':'#103b3cdd';ctx.strokeStyle=locked?'#819da2':'#dec994';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,selected?25:20,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=selected?'#173536':'#f6e6b7';ctx.font='20px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(locked?'封':r.scene==='lake'?'境':'灵',0,1);ctx.fillStyle='#143b37ed';ctx.fillRect(-76,34,152,50);ctx.strokeStyle='#bea56a';ctx.strokeRect(-76,34,152,50);ctx.fillStyle='#f0e1b9';ctx.font='17px serif';ctx.fillText(r.name,0,52);ctx.fillStyle='#bacdc1';ctx.font='12px sans-serif';ctx.fillText(locked?'宗门二阶开启':`炼气${r.minRealm}层 · ${r.duration}秒`,0,71);ctx.restore();}}
 return{scene:()=>scene,selectScene,render,draw,activate:p=>{const hit=Object.entries(EXPEDITIONS).find(([,r])=>r.scene===scene&&Math.abs(p.x-r.x)<90&&p.y>r.y-35&&p.y<r.y+85);if(hit)travelDialog(hit[0]);},quest:id=>{if(id==='alchemy'){if(getState().buildings.some(b=>b.type==='alchemy'))setTab('alchemy');else chooseBuild('alchemy');}else if(id==='expedition')selectScene('valley');else if(id==='sect2')setTab('sect');else setTab('disciples');}};
}
