export const TYPES={
 hall:{name:'仙府主殿',short:'主殿',sprite:0,desc:'仙府根基，自行凝聚灵石。弟子在此可静心修炼。',cost:{},out:{jade:8},duration:20,work:false,max:3},
 farm:{name:'灵草田',short:'灵田',sprite:1,desc:'栽种凝露草。派遣弟子照料后，持续收获灵草。',cost:{jade:30,wood:25,stone:10},out:{herb:8},duration:20,work:true,max:3},
 lumber:{name:'伐木场',short:'伐木',sprite:2,desc:'择木而伐，取材造府。派遣弟子采集灵木。',cost:{jade:25,wood:20,stone:8},out:{wood:14},duration:20,work:true,max:3},
 quarry:{name:'采石场',short:'采石',sprite:3,desc:'开采山间青石，为仙府营造与扩建提供材料。',cost:{jade:40,wood:30},out:{stone:12},duration:20,work:true,max:3},
 house:{name:'弟子居',short:'居所',sprite:4,desc:'一方静室，一盏清灯。每级增加两名弟子容量。',cost:{jade:65,wood:55,stone:30},out:{},duration:20,work:false,max:3},
 meditation:{name:'聚灵台',short:'聚灵',sprite:5,desc:'汇聚天地灵气。派遣弟子修炼，每秒获得 2 点修为。',cost:{jade:60,wood:40,stone:25},out:{},duration:20,work:true,max:3}
};
export const RESOURCE={jade:'灵石',wood:'灵木',stone:'青石',herb:'灵草'};
export const NAMES=['沈青禾','陆知微','林长风','云见月','顾听澜','江晚棠','裴照雪','温南星','叶松声','苏归岚','洛清川','许望舒'];
export const CELLS=[];
for(let x=0;x<8;x++)for(let y=0;y<7;y++){if((x===0&&y<2)||(x===7&&y>4)||(y===0&&x>5))continue;CELLS.push({x,y});}
export function initial(){return {version:1,time:0,speed:1,resources:{jade:260,wood:140,stone:90,herb:35},buildings:[{id:1,type:'hall',x:3,y:2,level:1,progress:0},{id:2,type:'farm',x:4,y:4,level:1,progress:0},{id:3,type:'lumber',x:1,y:3,level:1,progress:0}],disciples:[{id:1,name:NAMES[0],root:'木灵根',talent:1.15,portrait:0,realm:1,xp:22,job:2},{id:2,name:NAMES[1],root:'水灵根',talent:1.08,portrait:1,realm:1,xp:45,job:null},{id:3,name:NAMES[2],root:'土灵根',talent:1,portrait:2,realm:1,xp:16,job:3}],nextId:4,claimed:[],stats:{built:0,breakthroughs:0},logs:[{time:0,text:'你携三名弟子，于云岫山立下青岚仙府。'}]};}
export function addLog(s,text){s.logs.unshift({time:s.time,text});s.logs=s.logs.slice(0,50);}
export function canPay(s,c){return Object.entries(c).every(([k,v])=>s.resources[k]>=v);}
export function pay(s,c){if(!canPay(s,c))throw new Error('材料不足，请先安排弟子生产。');for(const[k,v]of Object.entries(c))s.resources[k]-=v;}
export function capacity(s){return 3+s.buildings.filter(b=>b.type==='house').reduce((n,b)=>n+2*b.level,0);}
export function upgradeCost(b){return {jade:50*b.level,wood:35*b.level,stone:25*b.level};}
export function build(s,type,x,y){if(!TYPES[type]||type==='hall')throw new Error('该建筑不可营造。');if(!CELLS.some(c=>c.x===x&&c.y===y))throw new Error('此处无法建造，请选择山坪内地块。');if(s.buildings.some(b=>b.x===x&&b.y===y))throw new Error('此地块已有建筑。');pay(s,TYPES[type].cost);const b={id:s.nextId++,type,x,y,level:1,progress:0};s.buildings.push(b);s.stats.built++;addLog(s,`${TYPES[type].name}落成。`);return b;}
export function assign(s,discipleId,buildingId){const d=s.disciples.find(d=>d.id===discipleId);if(!d)throw new Error('未找到弟子。');if(buildingId!==null){const b=s.buildings.find(b=>b.id===buildingId);if(!b||(b.type!=='hall'&&!TYPES[b.type].work))throw new Error('此处不能派遣弟子。');if(b.type!=='hall'&&s.disciples.some(p=>p.id!==d.id&&p.job===b.id))throw new Error('此处已有弟子执事。');}d.job=buildingId;addLog(s,`${d.name}${buildingId===null?'开始在府中休憩。':`前往${TYPES[s.buildings.find(b=>b.id===buildingId).type].name}。`}`);}
export function upgrade(s,id){const b=s.buildings.find(b=>b.id===id);if(!b)throw new Error('未找到建筑。');if(b.level>=TYPES[b.type].max)throw new Error('建筑已达当前最高等级。');pay(s,upgradeCost(b));b.level++;addLog(s,`${TYPES[b.type].name}升至 ${b.level} 级。`);}
export function recruit(s){if(s.disciples.length>=capacity(s))throw new Error('弟子居所不足，请建造或升级弟子居。');pay(s,{jade:80,herb:10});const id=s.disciples.length+1;const d={id,name:NAMES[(id-1)%NAMES.length],root:['木灵根','水灵根','土灵根','火灵根'][(id-1)%4],talent:1+(id%3)*.08,portrait:(id-1)%4,realm:1,xp:0,job:null};s.disciples.push(d);addLog(s,`${d.name}拜入仙府。`);return d;}
export function breakthrough(s,id){const d=s.disciples.find(d=>d.id===id);if(!d)throw new Error('未找到弟子。');if(d.realm>=9)throw new Error('已达炼气九层，本版境界已满。');if(d.xp<d.realm*100)throw new Error('修为未满，先安排修炼。');pay(s,{jade:30*d.realm,herb:12*d.realm});d.xp-=d.realm*100;d.realm++;s.stats.breakthroughs++;addLog(s,`${d.name}突破至炼气${d.realm}层。`);}
export function rates(s){const out={jade:0,wood:0,stone:0,herb:0};for(const b of s.buildings){const d=s.disciples.find(d=>d.job===b.id);if(TYPES[b.type].work&&!d)continue;const m=b.level*(d?d.talent*(1+.1*(d.realm-1)):1);for(const[k,v]of Object.entries(TYPES[b.type].out))out[k]+=v*m;}return out;}
export function tick(s,dt){if(!s.speed)return;dt*=s.speed;s.time+=dt;for(const b of s.buildings){const t=TYPES[b.type];const d=s.disciples.find(d=>d.job===b.id);if(t.work&&!d)continue;if(Object.keys(t.out).length){b.progress+=dt;while(b.progress>=t.duration){b.progress-=t.duration;const m=b.level*(d?d.talent*(1+.1*(d.realm-1)):1);for(const[k,v]of Object.entries(t.out))s.resources[k]+=v*m;}}}for(const d of s.disciples){const b=s.buildings.find(b=>b.id===d.job);if(b&&(b.type==='hall'||b.type==='meditation'))d.xp=Math.min(d.realm*100,d.xp+dt*(b.type==='meditation'?2*b.level:.6)*d.talent);}}
export const QUESTS=[{id:'quarry',title:'开山取石',text:'建造一座采石场，补齐营造物资。',check:s=>s.buildings.some(b=>b.type==='quarry'),reward:{jade:60,wood:30}}, {id:'meditation',title:'引灵入府',text:'建造一座聚灵台，开启弟子修炼。',check:s=>s.buildings.some(b=>b.type==='meditation'),reward:{jade:80,herb:25}}, {id:'breakthrough',title:'仙途初成',text:'让一名弟子完成首次境界突破。',check:s=>s.stats.breakthroughs>0,reward:{jade:120,wood:60,stone:40}}];
export function claim(s,id){const q=QUESTS.find(q=>q.id===id);if(!q||!q.check(s)||s.claimed.includes(id))throw new Error('尚未完成，或奖励已领取。');for(const[k,v]of Object.entries(q.reward))s.resources[k]+=v;s.claimed.push(id);addLog(s,`完成「${q.title}」，已收取奖励。`);}
export function validateSave(s){if(!s||s.version!==1||!Number.isFinite(s.time)||s.time<0||![0,1,2,4].includes(s.speed)||!Array.isArray(s.buildings)||s.buildings.length>CELLS.length||!Array.isArray(s.disciples)||s.disciples.length<1||s.disciples.length>100||!s.resources||!s.stats||!Number.isInteger(s.nextId)||!Array.isArray(s.claimed)||!s.claimed.every(id=>QUESTS.some(q=>q.id===id))||new Set(s.claimed).size!==s.claimed.length)throw new Error('存档格式不正确。');for(const k of Object.keys(RESOURCE))if(!Number.isFinite(s.resources[k])||s.resources[k]<0||s.resources[k]>1e12)throw new Error('存档资源异常。');const ids=new Set(),positions=new Set();for(const b of s.buildings){if(!Number.isInteger(b.id)||b.id<1||!TYPES[b.type]||!Number.isInteger(b.level)||b.level<1||b.level>3||!Number.isFinite(b.progress)||b.progress<0||b.progress>=20||!CELLS.some(c=>c.x===b.x&&c.y===b.y)||ids.has(b.id)||positions.has(`${b.x},${b.y}`))throw new Error('存档建筑异常。');ids.add(b.id);positions.add(`${b.x},${b.y}`);}if(s.buildings.filter(b=>b.type==='hall').length!==1||s.nextId<=Math.max(...ids))throw new Error('存档主殿异常。');const discipleIds=new Set(),jobs=new Set();for(const d of s.disciples){const job=s.buildings.find(b=>b.id===d.job);if(!Number.isInteger(d.id)||discipleIds.has(d.id)||typeof d.name!=='string'||d.name.length>20||typeof d.root!=='string'||d.root.length>20||!Number.isInteger(d.realm)||d.realm<1||d.realm>9||!Number.isFinite(d.xp)||d.xp<0||d.xp>d.realm*100||!Number.isFinite(d.talent)||d.talent<.5||d.talent>2||!Number.isInteger(d.portrait)||d.portrait<0||d.portrait>3||(d.job!==null&&(!job||(job.type!=='hall'&&!TYPES[job.type].work)||(job.type!=='hall'&&jobs.has(d.job)))))throw new Error('存档弟子异常。');discipleIds.add(d.id);if(d.job!==null)jobs.add(d.job);}if(s.disciples.length>capacity(s)||!Number.isInteger(s.stats.built)||s.stats.built<0||!Number.isInteger(s.stats.breakthroughs)||s.stats.breakthroughs<0)throw new Error('存档进度异常。');s.logs=Array.isArray(s.logs)?s.logs.filter(l=>l&&typeof l.text==='string'&&l.text.length<=200&&Number.isFinite(l.time)).slice(0,50):[];return s;}
