import test from 'node:test';
import assert from 'node:assert/strict';
import * as w from '../dist/ea-sim.mjs';
import * as data from '../dist/ea-data.mjs';
import * as old1 from '../dist/model.mjs';
import * as old2 from '../dist/world.mjs';
import * as old3 from '../dist/living-world.mjs';
import * as old4 from '../dist/sect-sim.mjs';
import {buildingAccess,scenicDistance,scenicPoint,geometryRevision} from '../dist/ea-scenic.mjs';
const allResources=(s,n=10000)=>{for(const k of Object.keys(data.RESOURCES))s.resources[k]=n;};
function settled(){const s=w.initial();w.masterAction(s,'heal');w.tick(s,15);w.advanceStory(s);w.advanceStory(s);w.build(s,'farm',4,4);w.build(s,'lumber',1,3);w.advanceStory(s);allResources(s);w.build(s,'library',2,4);w.advanceStory(s);return s;}
const free=(s,type)=>w.CELLS.find(c=>!w.placementLock(s,type,c.x,c.y));

test('EA has independent data, fourteen facilities and twelve real manuals',()=>{assert.equal(Object.keys(w.BUILDINGS).length,14);assert.equal(Object.keys(w.TECHNIQUES).length,12);assert.equal(Object.keys(w.RECIPES).length,4);assert.notEqual(w.BUILDINGS,old4.TYPES);assert.equal(old4.RESOURCE.food,undefined);assert.ok(w.CELLS.length>=100);});
test('new master starts at qi six with finite supplies and full valid state',()=>{const s=w.initial({seed:9421,name:'沈临川'});assert.equal(s.version,5);assert.equal(s.master.realm,6);assert.equal(s.master.name,'沈临川');assert.ok(s.resources.food>0);assert.equal(s.disciples.length,0);assert.deepEqual(w.validateSave(s),s);assert.throws(()=>w.assign(s,1,1),/自行/);assert.throws(()=>w.usePill(s,'qi',1),/自行/);});
test('opening preserves named followers motives and records source books once',()=>{const s=settled();assert.equal(s.story.step,4);assert.equal(s.disciples.length,2);assert.equal(s.disciples[0].name,'陆知微');assert.equal(s.disciples[0].mind.goal,'精研草木');assert.ok(s.disciples[0].mind.memories.some(m=>/亲人/.test(m.text)));assert.ok(s.doctrine.books.includes('spring'));assert.throws(()=>w.advanceStory(s));assert.deepEqual(w.validateSave(s),s);});
test('fixed second simulation and state RNG are identical across frame chunk sizes',()=>{const a=settled(),b=structuredClone(a);w.tick(a,300);for(let i=0;i<1200;i++)w.tick(b,.25);assert.deepEqual(a,b);const c=w.validateSave(a);w.tick(a,240);w.tick(c,240);assert.deepEqual(a,c);});
test('fractional carry and x4 speed survive exact save recovery',()=>{const s=settled();s.speed=4;w.tick(s,.1875);assert.equal(s.sim.carry,.75);const restored=w.validateSave(s);w.tick(s,.375);w.tick(restored,.375);assert.deepEqual(restored,s);assert.equal(s.sim.carry,.25);});
test('pause and pure UI queries never advance time or roll randomness',()=>{const s=settled();s.speed=0;const before=structuredClone(s);w.tick(s,3600);for(let n=0;n<20;n++){w.economySummary(s);w.rates(s);w.buildInfo(s,'house',6,5);w.studyLock(s,s.master,'spring',true);w.teachers(s,'qingyuan');w.campaignSummary(s);}assert.deepEqual(s,before);});
test('no-resource recovery is possible by master forage and automatic main house income',()=>{const s=w.initial();for(const k of Object.keys(s.resources))s.resources[k]=0;s.master.wound=0;w.masterAction(s,'food');w.tick(s,60);assert.ok(s.resources.food>=30);assert.ok(s.resources.jade>=25);w.trade(s,'herb','buy');assert.ok(s.resources.herb>=10);});
test('food demand, upkeep and resource income reconcile with the day ledger',()=>{const s=settled();const food=s.resources.food;for(const d of s.disciples){d.energy=0;d.mind.activity='rest';}w.tick(s,120-s.time%120);assert.ok(s.resources.food<food);assert.ok(s.economy.expense.food>0);assert.equal(s.economy.day,w.day(s));assert.ok(w.economySummary(s).foodDemand>=4);assert.deepEqual(w.validateSave(s),s);});
test('maintenance shortages degrade facilities without trapping personal recovery',()=>{const s=settled();s.disciples=[];s.resources.jade=0;s.resources.wood=0;const b=s.buildings.find(b=>b.type==='farm');s.buildings.find(b=>b.type==='hall').enabled=false;w.tick(s,120-s.time%120);assert.ok(b.condition<100);assert.ok(s.economy.shortages.length);w.masterAction(s,'wood');w.tick(s,20);assert.ok(s.resources.wood>0);});
test('layout, wear, weather and industry input affect actual output',()=>{const s=settled();const farm=s.buildings.find(b=>b.type==='farm'),d=s.disciples[0];const base=w.buildingYield(s,farm,d).herb;const c=w.CELLS.find(c=>Math.abs(c.x-farm.x)+Math.abs(c.y-farm.y)<=2&&!s.buildings.some(b=>b.x===c.x&&b.y===c.y));s.buildings.push({id:s.nextId++,type:'well',x:c.x,y:c.y,level:1,progress:0,condition:100,enabled:true});assert.ok(w.buildingYield(s,farm,d).herb>base);farm.condition=20;assert.ok(w.buildingYield(s,farm,d).herb<base);const workshop={id:900,type:'workshop',x:7,y:3,level:1,progress:0,condition:100,enabled:true};s.resources.wood=0;assert.deepEqual(w.buildingYield(s,workshop,d),{});});
test('build/upgrade/relocate consume resources and preserve accessible entrances',()=>{const s=settled(),c=free(s,'house');const b=w.build(s,'house',c.x,c.y);const before=w.capacity(s);w.upgrade(s,b.id);assert.equal(w.capacity(s),before+4);const dest=free(s,'house');w.relocate(s,b.id,dest.x,dest.y);assert.deepEqual({x:b.x,y:b.y},dest);assert.equal(s.stats.relocated,1);assert.throws(()=>w.build(s,'farm',b.x,b.y),/已有建筑/);assert.match(w.placementLock(s,'farm',10,5),/正式立派/);s.sect.level=2;s.sect.founded=true;assert.equal(w.placementLock(s,'farm',10,5),'');assert.deepEqual(w.validateSave(s),s);});
test('a building footprint covering the real master position is rejected before charging',()=>{const s=w.initial();allResources(s);const c={x:4,y:4};s.master.scenic={...scenicPoint(c.x,c.y),path:[],steps:0,facing:1,back:false};const before=structuredClone(s.resources);assert.throws(()=>w.build(s,'lumber',c.x,c.y),/掌门|通路/);assert.deepEqual(s.resources,before);});
test('walking routes obey land and building occupancy without instant teleporting',()=>{const s=w.initial();assert.ok(w.moveMaster(s,5,4));assert.notDeepEqual(s.master.position,{x:5,y:4});w.tick(s,10);assert.deepEqual(s.master.position,{x:5,y:4});assert.equal(w.moveMaster(s,3,2),false);assert.ok(w.moveMaster(s,10,8));w.tick(s,50);assert.deepEqual(s.master.position,{x:10,y:8});});
test('sources, prior knowledge, compatibility and support slots enforce study limits',()=>{const s=settled();assert.match(w.studyLock(s,s.master,'foundation',true),/尚无/);w.obtainBook(s,'alchemy');assert.match(w.studyLock(s,s.master,'alchemy',true),/春雨/);w.masterStudy(s,'spring');w.tick(s,40);assert.ok(s.master.support.includes('spring'));w.obtainBook(s,'wood');w.masterStudy(s,'wood');w.tick(s,50);assert.ok(s.master.support.includes('wood'));assert.match(w.studyLock(s,s.master,'alchemy',true),/已满/);const prior=s.master.knowledge.wood;w.forgetSupport(s,'wood');assert.equal(s.master.knowledge.wood,prior);w.masterStudy(s,'alchemy');w.tick(s,70);assert.ok(s.master.support.includes('alchemy'));assert.equal(w.compatible({main:'frost',support:[]},'flame'),false);assert.equal(w.compatible({main:'river',support:[]},'flame'),true);});
test('mature teaching is earned by practice and manuals can be deepened',()=>{const s=settled();assert.throws(()=>w.masterTeach(s,'qingyuan'),/理解不足/);w.masterStudy(s,'qingyuan');w.tick(s,40);assert.ok(s.master.knowledge.qingyuan>=60);w.masterTeach(s,'qingyuan');assert.equal(s.master.action,'teach');assert.ok(w.teachers(s,'qingyuan').some(p=>p.id===0));});
test('foundation knowledge and an actual crafted pill gate master qi-to-foundation breakthrough',()=>{const s=settled();s.master.realm=9;s.master.xp=w.xpNeed(9);s.master.energy=100;assert.match(w.breakthroughLock(s,s.master,true),/筑基篇/);s.doctrine.books.push('foundation');s.master.knowledge.foundation=40;s.master.knowledge.alchemy=40;w.build(s,'alchemy',5,2);assert.match(w.breakthroughLock(s,s.master,true),/筑基丹/);w.craft(s,'foundation');const materials=structuredClone(s.resources),restore=w.validateSave(s);w.tick(s,80);w.tick(restore,80);assert.deepEqual(s,restore);assert.equal(s.pills.foundation,1);assert.ok(s.resources.herb<=materials.herb+200);s.master.energy=100;w.masterBreakthrough(s);assert.equal(s.master.realm,10);assert.equal(s.pills.foundation,0);assert.equal(s.master.xp,0);assert.deepEqual(w.validateSave(s),s);});
test('foundation middle and late are reachable with their own costs and cap',()=>{const s=settled();s.master.knowledge.foundation=60;s.master.realm=10;s.master.xp=w.xpNeed(10);s.master.energy=100;w.masterBreakthrough(s);assert.equal(s.master.realm,11);w.tick(s,20);s.master.xp=w.xpNeed(11);s.master.energy=100;w.masterBreakthrough(s);assert.equal(s.master.realm,12);assert.match(w.breakthroughLock(s,s.master,true),/后期/);assert.equal(w.realmName(12),'筑基后期');});
test('commerce validates daily quotations and a completed order cannot pay twice',()=>{const s=settled();const q=w.commissions(s).find(x=>x.cost);w.fulfill(s,q.id);assert.throws(()=>w.fulfill(s,q.id),/已完成/);const d=w.day(s);w.tick(s,120);assert.throws(()=>w.trade(s,'food','buy',d),/换日/);for(let i=0;i<8;i++)w.trade(s,'food','buy');assert.throws(()=>w.trade(s,'food','buy'),/售罄/);assert.deepEqual(w.validateSave(s),s);});
test('legacy v1 through v4 migrate on a copy with assets and rewards preserved',()=>{for(const initial of [old1.initial,old2.initial,old3.initial,old4.initial]){const input=initial(),copy=structuredClone(input),s=w.validateSave(input);assert.deepEqual(input,copy);assert.equal(s.version,5);for(const[k,v]of Object.entries(input.resources))assert.equal(s.resources[k],v);for(const b of input.buildings)assert.deepEqual(Object.fromEntries(Object.keys(b).map(k=>[k,s.buildings.find(n=>n.id===b.id)[k]])),b);assert.deepEqual(s.claimed,input.claimed);assert.equal(s.disciples.length,input.disciples.length);assert.equal(s.migration.from,input.version);assert.deepEqual(w.validateSave(s),s);}});
test('strict v5 validation rejects malformed finite data instead of silently fixing it',()=>{const changes=[s=>s.resources.food=-1,s=>s.resources.herb=NaN,s=>s.master.realm=13,s=>s.master.xp=99999,s=>s.master.main='missing',s=>s.sim.seed=0,s=>s.sim.carry=1,s=>s.master.path=[{x:11,y:8}],s=>s.doctrine.books.push('unknown'),s=>s.pills.foundation=-1,s=>s.stats.consumed=-1,s=>s.economy.previous.income.food=-1,s=>s.buildings.push({...s.buildings[0]}),s=>s.story.step=99];for(const change of changes){const s=w.initial();change(s);assert.throws(()=>w.validateSave(s));}});

test('v4 pending learning keeps earned progress and the original sixty-point target',()=>{const old=old4.initial();allResources(old);old.story.step=2;old.master.wound=0;old4.build(old,'library',2,4);old.doctrine.books.push('spring');old4.masterStudy(old,'spring');old4.tick(old,10);const progress=old.master.learning.progress,s=w.validateSave(old);assert.equal(s.master.learning.progress,progress);assert.equal(s.master.learning.total,60);w.tick(s,Math.ceil((60-progress)/s.master.talent));assert.ok(s.master.support.includes('spring'));assert.equal(s.master.learning,null);assert.deepEqual(w.validateSave(s),s);});
test('legacy forty-second spirit batch migrates unchanged and creates one original pill once',()=>{const old=old2.initial();allResources(old);old.sect.level=2;old2.build(old,'alchemy',2,4);old2.craft(old,'spirit');old2.tick(old,5);const s=w.validateSave(old);assert.equal(s.crafting.total,40);assert.equal(s.crafting.remaining,35);assert.equal(s.crafting.yield,1);const restored=w.validateSave(s);w.tick(s,35);w.tick(restored,35);assert.deepEqual(s,restored);assert.equal(s.pills.spirit,1);assert.equal(s.stats.crafted,1);w.tick(s,60);assert.equal(s.stats.crafted,1);});
test('legacy master journey retains its waiting encounter and pays original rewards once',()=>{const old=old4.initial();old.master.wound=0;old.master.energy=100;old4.startMasterTravel(old,'valley_path');old4.tick(old,20);const s=w.validateSave(old),start=structuredClone(s.resources);w.tick(s,50);assert.equal(s.master.journey.status,'encounter');w.resolveMasterEncounter(s,'careful');w.tick(s,20);assert.equal(s.master.journey,null);assert.equal(s.resources.herb,start.herb+old4.EXPEDITIONS.valley_path.reward.herb);assert.equal(s.stats.expeditions,1);w.tick(s,30);assert.equal(s.stats.expeditions,1);assert.deepEqual(w.validateSave(s),s);});
test('an exhausted master can resume a saved study plan without discarding progress',()=>{const s=settled();s.master.energy=15;w.obtainBook(s,'ember');w.masterStudy(s,'ember');w.tick(s,60);assert.equal(s.master.action,'rest');assert.ok(s.master.learning);const progress=s.master.learning.progress;w.tick(s,30);w.masterStudy(s,'ember');assert.equal(s.master.learning.progress,progress);const restored=w.validateSave(s);w.tick(s,80);w.tick(restored,80);assert.deepEqual(s,restored);assert.equal(s.master.main,'ember');});

test('legacy NPC travel moves into autonomous society with original remaining time and payout',()=>{const old=old2.initial();old2.startExpedition(old,'valley_ruins',1);old2.tick(old,20);const previous=structuredClone(old.expedition),s=w.validateSave(old),d=s.disciples.find(d=>d.id===1);assert.equal(s.expedition,null);assert.equal(d.mind.journey.total,previous.total);assert.equal(d.mind.journey.remaining,previous.remaining);assert.deepEqual(d.mind.journey.snapshotReward,old2.EXPEDITIONS.valley_ruins.reward);const start=s.resources.insight;const restored=w.validateSave(s);w.tick(s,40);w.tick(restored,40);assert.deepEqual(s,restored);assert.equal(d.mind.journey,null);assert.equal(s.stats.expeditions,1);assert.ok(s.resources.insight>=start+old2.EXPEDITIONS.valley_ruins.reward.insight);w.tick(s,40);assert.equal(s.stats.expeditions,1);});
test('published teachers never reveal an undiscovered forbidden manual',()=>{const s=settled(),d=s.disciples[0];d.mind.knowledge.spring=80;d.mind.support.push('spring');d.mind.hiddenKnowledge.spring=1;s.society.nextIncidentId=2;s.society.secrets.push({id:1,discipleId:d.id,kind:'book',subject:'spring',time:s.time,discovered:false,discoveredAt:null,handled:false,outcome:null,evidenceProgress:0,motive:'求知欲与接触机会',restitution:12});assert.ok(!w.teachers(s,'spring').some(p=>p.id===d.id));s.society.secrets[0].discovered=true;assert.ok(w.teachers(s,'spring').some(p=>p.id===d.id));});
test('recruiting after the newest person leaves cannot reuse their historical identity',()=>{const s=settled();const latest=s.disciples.at(-1);s.society.departed.push({id:latest.id,name:latest.name,time:s.time,reason:'主动离山',memories:[]});s.disciples.pop();const d=w.recruit(s);assert.ok(d.id>latest.id);});

test('optional early breakthrough states the full risk and leaves guaranteed full-XP breakthroughs intact',()=>{const s=w.initial();allResources(s);s.master.wound=0;s.master.energy=35;s.master.xp=w.xpNeed(6)*.85;const before=structuredClone(s),info=w.riskBreakthroughInfo(s);assert.equal(info.lock,'');assert.ok(info.chance>=.55&&info.chance<=.85);assert.deepEqual(info.cost,w.breakthroughCost(s.master));assert.deepEqual(info.failure,{xpLossFraction:.15,wound:12,cooldown:60});assert.deepEqual(s,before);s.master.xp=w.xpNeed(6);assert.match(w.riskBreakthroughInfo(s).lock,/稳妥/);const seed=s.sim.seed;w.masterBreakthrough(s);assert.equal(s.master.realm,7);assert.equal(s.sim.seed,seed);});
test('seeded early breakthrough success commits one cost, one roll and a durable outcome',()=>{const s=w.initial({seed:1});allResources(s);s.master.wound=0;s.master.energy=35;s.master.xp=w.xpNeed(6)*.85;const materials=structuredClone(s.resources),info=w.riskBreakthroughInfo(s),result=w.masterRiskBreakthrough(s);assert.equal(result.success,true);assert.equal(s.master.realm,7);assert.equal(s.master.xp,0);assert.equal(s.master.energy,10);for(const[k,v]of Object.entries(info.cost))assert.equal(s.resources[k],materials[k]-v);assert.equal(s.master.breakthroughCooldown,s.time+15);assert.equal(s.master.breakthroughHistory.length,1);assert.equal(s.stats.breakthroughs,1);assert.throws(()=>w.masterRiskBreakthrough(s));assert.deepEqual(w.validateSave(s),s);});
test('failed early breakthrough consumes the foundation pill, preserves realm and can recover normally',()=>{const s=w.initial({seed:12345});allResources(s);s.master.wound=0;s.master.realm=9;s.master.energy=35;s.master.xp=w.xpNeed(9)*.85;s.master.knowledge.foundation=40;s.pills.foundation=1;const xp=s.master.xp,result=w.masterRiskBreakthrough(s);assert.equal(result.success,false);assert.equal(s.master.realm,9);assert.equal(s.master.xp,xp*.85);assert.equal(s.master.wound,12);assert.equal(s.pills.foundation,0);assert.equal(s.master.energy,10);assert.equal(s.master.breakthroughCooldown,s.time+60);assert.equal(s.stats.breakthroughs,0);assert.match(s.master.memories[0].text,/未成/);assert.deepEqual(w.validateSave(s),s);w.masterAction(s,'heal');w.tick(s,6);assert.equal(s.master.wound,0);w.masterAction(s,'rest');w.tick(s,25);w.masterAction(s,'cultivate');w.tick(s,130);assert.equal(s.master.xp,w.xpNeed(9));w.masterAction(s,'rest');w.tick(s,25);assert.match(w.breakthroughLock(s,s.master,true),/筑基丹/);s.pills.foundation=1;w.masterBreakthrough(s);assert.equal(s.master.realm,10);assert.equal(s.master.breakthroughHistory[0].success,false);});
test('risk boundaries reject without cost or RNG and a failed attempt survives exact save recovery',()=>{const s=w.initial({seed:12345});allResources(s);s.master.wound=0;s.master.energy=35;s.master.xp=w.xpNeed(6)*.849;const before=structuredClone(s);assert.throws(()=>w.masterRiskBreakthrough(s),/85%/);assert.deepEqual(s,before);s.master.xp=w.xpNeed(6)*.85;const a=w.validateSave(s),b=w.validateSave(s);const first=w.masterRiskBreakthrough(a),second=w.masterRiskBreakthrough(b);assert.deepEqual(first,second);assert.equal(first.success,false);assert.deepEqual(a,b);const restored=w.validateSave(a);w.masterAction(a,'heal');w.masterAction(restored,'heal');w.tick(a,30);for(let i=0;i<120;i++)w.tick(restored,.25);assert.deepEqual(a,restored);assert.equal(a.master.breakthroughHistory.length,1);const malformed=structuredClone(a);malformed.master.breakthroughHistory[0].success=true;assert.throws(()=>w.validateSave(malformed),/冲关历史/);});
test('living layouts change actual rest and daily food demand rather than only showing a label',()=>{const s=settled(),house=w.build(s,'house',0,5);s.master.scenic={...s.master.scenic,...buildingAccess(s,house)};s.master.energy=30;s.master.action='rest';const base=w.restRecovery(s,s.master);const kitchen={id:s.nextId++,type:'kitchen',x:1,y:5,level:1,progress:0,condition:100,enabled:true};s.buildings.push(kitchen);const near=w.restRecovery(s,s.master);assert.ok(near>base);const before=s.master.energy;w.tick(s,1);assert.ok(Math.abs(s.master.energy-before-near)<1e-9);s.buildings.push({id:s.nextId++,type:'clinic',x:2,y:5,level:1,progress:0,condition:100,enabled:true});assert.ok(w.restRecovery(s,s.master)>near);const quiet=w.restRecovery(s,s.master);const quarry={id:s.nextId++,type:'quarry',x:3,y:4,level:1,progress:0,condition:100,enabled:true};s.buildings.push(quarry);assert.ok(w.restRecovery(s,s.master)<quiet);s.disciples=Array.from({length:24},(_,i)=>({id:i+1}));kitchen.level=3;const noisyFood=w.foodDemand(s);s.buildings=s.buildings.filter(b=>b.id!==quarry.id);assert.ok(w.foodDemand(s)<noisyFood);});

test('autonomous NPC rest consumes the same spatial housing recovery hook as the master',()=>{const base=settled(),house=w.build(base,'house',0,5);const d=base.disciples[0];Object.assign(d.mind.scenic,buildingAccess(base,house),{path:[],goal:buildingAccess(base,house),revision:geometryRevision(base)});d.energy=5;d.job=null;d.mind.activity='rest';d.mind.path=[];d.mind.learning=null;d.mind.lastDecision=base.time;d.mind.commitUntil=base.time+100;const near=structuredClone(base),far=structuredClone(base);for(const [s,p]of [[near,{x:1,y:5}],[far,{x:0,y:6}]])s.buildings.push({id:s.nextId++,type:'kitchen',...p,level:1,progress:0,condition:100,enabled:true});const expected=w.restRecovery(near,near.disciples[0]);w.tick(near,1);w.tick(far,1);assert.ok(near.disciples[0].energy>far.disciples[0].energy);assert.ok(Math.abs(near.disciples[0].energy-5-expected)<1e-9);assert.deepEqual(w.validateSave(near),near);assert.deepEqual(w.validateSave(far),far);});

test('batch trading respects daily stock, actual totals and save continuation',()=>{
 const s=w.initial();s.resources.jade=1000;const jade=s.resources.jade,wood=s.resources.wood;
 w.trade(s,'wood','buy',0,5);
 assert.equal(s.resources.jade,jade-data.GOODS.wood.buy*5);assert.equal(s.resources.wood,wood+50);
 assert.equal(s.community.trades.wood,5);assert.equal(s.stats.trades,5);
 const restored=w.validateSave(s);w.trade(restored,'wood','buy',0,3);
 assert.equal(restored.community.trades.wood,w.MARKET_DAILY_BATCHES);
 const before=structuredClone(restored);assert.throws(()=>w.trade(restored,'wood','buy',0,1),/余货/);assert.deepEqual(restored,before);
 w.trade(restored,'wood','sell',0,5);assert.equal(restored.resources.jade,before.resources.jade+data.GOODS.wood.sell*5);
 assert.deepEqual(w.validateSave(restored),restored);
});
test('invalid quantities and insufficient resources do not partially settle a batch',()=>{
 for(const quantity of [0,-1,1.2,NaN,Infinity,1000,'2']){const s=w.initial(),before=structuredClone(s);assert.throws(()=>w.trade(s,'wood','sell',0,quantity));assert.deepEqual(s,before);}
 const s=w.initial(),before=structuredClone(s);assert.throws(()=>w.trade(s,'wood','sell',0,10));assert.deepEqual(s,before);
 assert.throws(()=>w.trade(s,'wood','buy',0,8));assert.deepEqual(s,before);
 assert.throws(()=>w.trade(s,'wood','buy',1,1),/换日/);assert.deepEqual(s,before);
});
test('market quantities renew on the actual game day without stale quota blocking purchases',()=>{
 const s=w.initial();s.resources.jade=1000;w.trade(s,'food','buy',0,8);w.tick(s,120);
 w.trade(s,'food','buy',1,2);assert.equal(s.community.trades.food,2);assert.equal(s.community.day,1);assert.deepEqual(w.validateSave(s),s);
});
