import test from 'node:test';
import assert from 'node:assert/strict';
import{attachMapInput}from'../dist/map-input.mjs';
class Target{listeners=new Map();addEventListener(n,f){if(!this.listeners.has(n))this.listeners.set(n,new Set());this.listeners.get(n).add(f);}removeEventListener(n,f){this.listeners.get(n)?.delete(f);}emit(n,e={}){for(const f of this.listeners.get(n)||[])f({pointerId:1,button:0,buttons:1,pointerType:'mouse',isPrimary:true,clientX:10,clientY:10,...e});}}
function setup(){const canvas=new Target(),win=new Target(),doc=new Target(),pan={x:0,y:0};let capture=null,clicks=0;canvas.setPointerCapture=id=>capture=id;canvas.hasPointerCapture=id=>capture===id;canvas.releasePointerCapture=()=>capture=null;const stop=attachMapInput(canvas,{pan,onHover(){},onActivate(){clicks++;},windowTarget:win,documentTarget:doc});return{canvas,win,doc,pan,stop,get clicks(){return clicks;},get capture(){return capture;}};}
for(const event of ['pointercancel','lostpointercapture','blur','pagehide','visibilitychange'])test(`${event} releases drag and stops unpressed movement`,()=>{const a=setup();a.canvas.emit('pointerdown');a.canvas.emit('pointermove',{clientX:60,clientY:60});assert.deepEqual(a.pan,{x:50,y:50});if(event==='blur'||event==='pagehide')a.win.emit(event);else if(event==='visibilitychange'){a.doc.hidden=true;a.doc.emit(event);}else a.canvas.emit(event);a.canvas.emit('pointermove',{buttons:0,clientX:110,clientY:110});assert.deepEqual(a.pan,{x:50,y:50});assert.equal(a.capture,null);});
test('lost mouse button stops movement even without pointerup',()=>{const a=setup();a.canvas.emit('pointerdown');a.canvas.emit('pointermove',{buttons:0,clientX:80});assert.deepEqual(a.pan,{x:0,y:0});assert.equal(a.capture,null);});
test('only primary left pointer acts; second pointer cannot terminate first',()=>{const a=setup();a.canvas.emit('pointerdown',{button:2});assert.equal(a.capture,null);a.canvas.emit('pointerdown');a.canvas.emit('pointerup',{pointerId:2});assert.equal(a.capture,1);a.canvas.emit('pointerup');assert.equal(a.clicks,1);assert.equal(a.capture,null);});
test('drag does not activate building; dispose releases capture and listeners',()=>{const a=setup();a.canvas.emit('pointerdown');a.canvas.emit('pointermove',{clientX:60});a.canvas.emit('pointerup');assert.equal(a.clicks,0);a.canvas.emit('pointerdown');a.stop();assert.equal(a.capture,null);a.canvas.emit('pointermove',{clientX:100});assert.equal(a.pan.x,50);});
