import test from 'node:test';
import assert from 'node:assert/strict';
import{attachMapInput}from'../dist/map-input.mjs';
class Target{listeners=new Map();addEventListener(n,f){if(!this.listeners.has(n))this.listeners.set(n,new Set());this.listeners.get(n).add(f);}removeEventListener(n,f){this.listeners.get(n)?.delete(f);}emit(n,e={}){for(const f of this.listeners.get(n)||[])f({pointerId:1,button:0,buttons:1,pointerType:'mouse',isPrimary:true,clientX:10,clientY:10,...e});}}
function setup(){const canvas=new Target(),win=new Target(),doc=new Target(),pan={x:0,y:0},captures=new Set(),pinches=[];let clicks=0;canvas.setPointerCapture=id=>captures.add(id);canvas.hasPointerCapture=id=>captures.has(id);canvas.releasePointerCapture=id=>captures.delete(id);const stop=attachMapInput(canvas,{pan,onHover(){},onActivate(){clicks++;},onPinch:e=>pinches.push(e),windowTarget:win,documentTarget:doc});return{canvas,win,doc,pan,pinches,stop,get clicks(){return clicks;},get capture(){return captures.size?Array.from(captures)[0]:null;},get captures(){return [...captures];}};}
for(const event of ['pointercancel','lostpointercapture','blur','pagehide','visibilitychange'])test(`${event} releases drag and stops unpressed movement`,()=>{const a=setup();a.canvas.emit('pointerdown');a.canvas.emit('pointermove',{clientX:60,clientY:60});assert.deepEqual(a.pan,{x:50,y:50});if(event==='blur'||event==='pagehide')a.win.emit(event);else if(event==='visibilitychange'){a.doc.hidden=true;a.doc.emit(event);}else a.canvas.emit(event);a.canvas.emit('pointermove',{buttons:0,clientX:110,clientY:110});assert.deepEqual(a.pan,{x:50,y:50});assert.equal(a.capture,null);});
test('lost mouse button stops movement even without pointerup',()=>{const a=setup();a.canvas.emit('pointerdown');a.canvas.emit('pointermove',{buttons:0,clientX:80});assert.deepEqual(a.pan,{x:0,y:0});assert.equal(a.capture,null);});
test('only primary left pointer acts; second pointer cannot terminate first',()=>{const a=setup();a.canvas.emit('pointerdown',{button:2});assert.equal(a.capture,null);a.canvas.emit('pointerdown');a.canvas.emit('pointerup',{pointerId:2});assert.equal(a.capture,1);a.canvas.emit('pointerup');assert.equal(a.clicks,1);assert.equal(a.capture,null);});
test('drag does not activate building; dispose releases capture and listeners',()=>{const a=setup();a.canvas.emit('pointerdown');a.canvas.emit('pointermove',{clientX:60});a.canvas.emit('pointerup');assert.equal(a.clicks,0);a.canvas.emit('pointerdown');a.stop();assert.equal(a.capture,null);a.canvas.emit('pointermove',{clientX:100});assert.equal(a.pan.x,50);});
for(const pointerType of ['mouse','touch'])test(`${pointerType} release away from press does not activate when movement events were coalesced`,()=>{const a=setup();a.canvas.emit('pointerdown',{pointerType});a.canvas.emit('pointerup',{pointerType,clientX:80,clientY:30});assert.equal(a.clicks,0);assert.equal(a.capture,null);a.canvas.emit('pointerdown',{pointerType});a.canvas.emit('pointerup',{pointerType,clientX:12,clientY:11});assert.equal(a.clicks,1);});
test('two touches report midpoint zoom and never activate a map target',()=>{const a=setup();a.canvas.emit('pointerdown',{pointerType:'touch',clientX:20,clientY:30});a.canvas.emit('pointerdown',{pointerId:2,pointerType:'touch',isPrimary:false,clientX:60,clientY:30});assert.deepEqual(a.captures,[1,2]);a.canvas.emit('pointermove',{pointerId:2,pointerType:'touch',isPrimary:false,clientX:80,clientY:30});assert.equal(a.pinches.length,1);assert.deepEqual(a.pinches[0],{scale:1.5,clientX:50,clientY:30,dx:10,dy:0});assert.deepEqual(a.pan,{x:0,y:0});a.canvas.emit('pointerup',{pointerId:2,pointerType:'touch',isPrimary:false});a.canvas.emit('pointerup',{pointerType:'touch'});assert.equal(a.clicks,0);assert.deepEqual(a.captures,[]);});
test('pinch cancellation releases both contacts and keeps later taps usable',()=>{const a=setup();a.canvas.emit('pointerdown',{pointerType:'touch'});a.canvas.emit('pointerdown',{pointerId:2,pointerType:'touch',isPrimary:false,clientX:50});a.canvas.emit('pointercancel',{pointerId:2,pointerType:'touch',isPrimary:false});assert.deepEqual(a.captures,[]);a.canvas.emit('pointerup',{pointerType:'touch'});assert.equal(a.clicks,0);a.canvas.emit('pointerdown',{pointerType:'touch'});a.canvas.emit('pointerup',{pointerType:'touch'});assert.equal(a.clicks,1);});
test('drag after a zoom-adjusted pan moves smoothly back toward the boundary',()=>{const a=setup();a.pan.x=760;a.pan.y=540;a.canvas.emit('pointerdown');a.canvas.emit('pointermove',{clientX:0,clientY:0});assert.deepEqual(a.pan,{x:750,y:530});a.canvas.emit('pointerup',{clientX:0,clientY:0});assert.equal(a.clicks,0);});
