import test from 'node:test';
import assert from 'node:assert/strict';
import{createPersistence,SAVE_KEY,BACKUP_KEY}from'../dist/persistence.mjs';
import{initial,validateSave}from'../dist/living-world.mjs';
const memory=()=>{const m=new Map();return{getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};};
test('save and reload retain gameplay and preceding backup',()=>{const storage=memory(),p=createPersistence(()=>storage,validateSave),s=initial();assert.equal(p.load(),null);assert.ok(p.save(s));s.resources.jade=123;assert.ok(p.save(s));assert.equal(JSON.parse(storage.getItem(BACKUP_KEY)).state.resources.jade,260);const next=createPersistence(()=>storage,validateSave);assert.deepEqual(next.load(),s);});
test('corrupted primary restores valid backup without silently overwriting corruption',()=>{const storage=memory(),p=createPersistence(()=>storage,validateSave),s=initial();p.load();p.save(s);s.resources.jade=123;p.save(s);storage.setItem(SAVE_KEY,'broken');const next=createPersistence(()=>storage,validateSave);assert.equal(next.load().resources.jade,260);assert.equal(next.blocked,true);assert.equal(next.save(s),false);assert.equal(storage.getItem(SAVE_KEY),'broken');assert.ok(next.save(s,{replace:true}));});
test('another tab cannot overwrite a newer save',()=>{const storage=memory(),a=createPersistence(()=>storage,validateSave),s=initial();a.load();a.save(s);const b=createPersistence(()=>storage,validateSave);b.load();s.resources.jade=200;a.save(s);const latest=storage.getItem(SAVE_KEY);assert.equal(b.save(initial()),false);assert.equal(storage.getItem(SAVE_KEY),latest);assert.equal(b.blocked,true);});
test('storage unavailable or full returns status without crashing or losing previous save',()=>{const unavailable=createPersistence(()=>{throw Error('blocked');},validateSave);assert.equal(unavailable.load(),null);assert.equal(unavailable.save(initial()),false);const storage=memory(),p=createPersistence(()=>storage,validateSave);p.load();p.save(initial());const old=storage.getItem(SAVE_KEY);storage.setItem=()=>{const e=Error('full');e.name='QuotaExceededError';throw e;};assert.equal(p.save(initial()),false);assert.equal(storage.getItem(SAVE_KEY),old);});
