import test from 'node:test';
import assert from 'node:assert/strict';
import * as w from '../dist/sect-sim.mjs';
import{initial as old}from'../dist/living-world.mjs';
import{createPersistence}from'../dist/persistence.mjs';
function established(){const s=w.initial();w.masterAction(s,'heal');w.tick(s,15);w.advanceStory(s);w.advanceStory(s);w.build(s,'farm',4,4);w.build(s,'lumber',1,3);w.advanceStory(s);return s;}
test('new game is a wounded talented master with inherited basics and no forced followers',()=>{const s=w.initial();assert.equal(s.master.realm,6);assert.ok(s.master.talent>1.6);assert.equal(s.disciples.length,0);assert.deepEqual(s.doctrine.books,['qingyuan']);assert.deepEqual(w.validateSave(s),s);assert.throws(()=>w.build(s,'library',2,4));assert.throws(()=>w.assign(s,1,1));});
test('first chapter is playable through healing, charity, production and manuscripts',()=>{const s=established();assert.equal(s.disciples.length,2);assert.equal(s.story.step,3);w.masterAction(s,'wood');w.tick(s,70);w.build(s,'library',2,4);w.advanceStory(s);assert.equal(s.story.step,4);assert.ok(s.doctrine.books.includes('spring'));assert.ok(s.disciples[0].mind.main);assert.deepEqual(w.validateSave(s),s);});
test('NPC decisions continue identically after save/reload and across tick sizes',()=>{const s=established(),a=structuredClone(s),b=structuredClone(s);w.tick(a,180);for(let i=0;i<720;i++)w.tick(b,.25);assert.deepEqual(a,b);const restored=w.validateSave(a);w.tick(a,120);w.tick(restored,120);assert.deepEqual(a,restored);});
test('pause freezes AI, recovery and master travel',()=>{const s=established();w.startMasterTravel(s,'valley_path');s.speed=0;const before=structuredClone(s);w.tick(s,100);assert.deepEqual(s,before);});
test('master expedition requires their choice and grants rewards once',()=>{const s=established();w.startMasterTravel(s,'valley_path');w.tick(s,20);assert.equal(s.master.journey.status,'encounter');w.tick(s,20);assert.equal(s.master.journey.remaining,20);w.resolveMasterEncounter(s,'bold');w.tick(s,20);assert.equal(s.master.journey,null);assert.equal(s.stats.expeditions,1);w.tick(s,20);assert.equal(s.stats.expeditions,1);assert.deepEqual(w.validateSave(s),s);});
test('walk path stays on available land and stops at destination',()=>{const s=w.initial();assert.ok(w.moveMaster(s,5,4));assert.ok(!s.master.path.some(p=>s.buildings.some(b=>b.x===p.x&&b.y===p.y)));w.tick(s,10);assert.deepEqual(s.master.position,{x:5,y:4});assert.equal(w.moveMaster(s,3,2),false);assert.throws(()=>w.build(s,'farm',5,4));});
test('technique compatibility and learning capacity constrain study',()=>{const s=established();s.resources.jade=1000;s.resources.herb=100;s.resources.crystal=10;s.resources.wood=200;w.build(s,'library',2,4);w.obtainBook(s,'ember');w.obtainBook(s,'frost');w.masterStudy(s,'ember');w.tick(s,40);assert.equal(s.master.main,'ember');assert.match(w.studyLock(s,s.master,'frost',true),/相冲/);assert.equal(w.compatible({main:'ember',support:[]},'spring'),true);assert.equal(w.compatible({main:'frost',support:[]},'flame'),false);});
test('unapproved pill consumption can be discovered and handled only once',()=>{const s=established(),d=s.disciples[1];s.doctrine.pillRule='permission';s.pills.qi=10;d.mind.traits=[20,100,0,50,80];for(let i=0;i<20&&!s.incidents.length;i++)w.tick(s,10);assert.ok(s.incidents.length);const incident=s.incidents[0];assert.equal(incident.discovered,false);assert.throws(()=>w.settleIncident(s,incident.id,'warn'));w.tick(s,30);assert.equal(incident.discovered,true);w.settleIncident(s,incident.id,'warn');assert.equal(d.mind.caution,1);assert.throws(()=>w.settleIncident(s,incident.id,'warn'));assert.deepEqual(w.validateSave(s),s);});
test('v3 migration preserves resources, buildings and active expedition without forced jobs',()=>{const s=old(),copy=structuredClone(s),m=w.validateSave(s);assert.deepEqual(s,copy);assert.deepEqual(m.resources,s.resources);assert.deepEqual(m.buildings,s.buildings);assert.equal(m.version,4);assert.equal(m.story.step,4);assert.ok(m.disciples.every(d=>d.job===null&&d.mind));assert.deepEqual(w.validateSave(m),m);});
test('long session keeps valid saves and singular production assignments',()=>{const s=established();for(let i=0;i<120;i++){w.tick(s,10);w.validateSave(s);const jobs=s.disciples.filter(d=>d.job!==null&&d.job!==1).map(d=>d.job);assert.equal(new Set(jobs).size,jobs.length);}const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)},save=createPersistence(()=>storage,w.validateSave);save.load();assert.ok(save.save(s));const other=createPersistence(()=>storage,w.validateSave);assert.deepEqual(other.load(),s);});
test('malformed v4 data cannot enter autosave',()=>{for(const change of [s=>s.master.energy=-1,s=>s.master.main='missing',s=>s.sim.seed=0,s=>s.doctrine.books=['unknown'],s=>s.master.journey={routeId:'bad'},s=>s.story.step=99]){const s=w.initial();change(s);assert.throws(()=>w.validateSave(s));}});

test('master benefits and fatigue follow the same learned manuals',()=>{const s=w.initial();s.master.wound=0;s.master.energy=50;const normal=structuredClone(s),supported=structuredClone(s);supported.master.support=['spring'];w.tick(normal,5);w.tick(supported,5);assert.ok(supported.master.energy>normal.master.energy);const fire=structuredClone(s),water=structuredClone(s);fire.master.main='ember';water.master.main='frost';w.masterAction(fire,'cultivate');w.masterAction(water,'cultivate');w.tick(fire,5);w.tick(water,5);assert.ok(fire.master.energy<water.master.energy);assert.ok(fire.master.xp>water.master.xp);s.sim.carry=1-Number.EPSILON;assert.deepEqual(w.validateSave(s),s);s.master.main=null;assert.throws(()=>w.validateSave(s));});
