import {point,findPath,sweep,distance,canStand} from './navigation.mjs?v=courtyard-1.3';
export const SAVE_KEY='xianfu-yunxiu-courtyard-v1';
export const BUILDINGS={main:{level:1,wood:30,stone:20},meditation:{level:1,wood:20,stone:15},workshop:{level:1,wood:24,stone:18},works:{level:1,wood:20,stone:30},herbs:{level:1,wood:18,stone:12},kitchen:{level:1,wood:22,stone:16},gate:{level:1,wood:35,stone:30}};
const identities=[['master','沈砚',0,'掌门','centre'],['luzhiwei','陆知微',1,'药圃照料','herbsMiddle'],['songyan','宋砚',2,'守院弟子','mainCourt'],['linbo','林伯',3,'百工匠人','workshop'],['wenling','温苓',4,'静修弟子','meditation'],['qinghe','青禾',5,'膳房照料','kitchen']];
export function createState(saved){const state={resources:{jade:286,wood:84,stone:52,herb:36,grain:72},buildings:structuredClone(BUILDINGS),day:12,elapsed:0,production:0,speed:1,paused:false,quest:false,learned:false,selected:'herbs',logs:[],actors:identities.map(([id,name,variant,role,node])=>({id,name,variant,role,...point(node),home:node,path:[],goal:null,moving:false,facing:1,follow:false,wait:2+variant,steps:0})),metrics:{routes:0,blocked:0,invalid:0}};if(saved?.version===1){for(const k of ['resources','day','elapsed','production','quest','learned','selected','logs','paused','speed'])if(saved[k]!=null)state[k]=saved[k];for(const k in state.buildings)if(Number.isInteger(saved.buildings?.[k]?.level)&&saved.buildings[k].level>0)state.buildings[k].level=Math.min(5,saved.buildings[k].level);for(const a of state.actors){const old=saved.actors?.find(x=>x.id===a.id);if(old&&canStand(old)){a.x=old.x;a.y=old.y;a.follow=!!old.follow;}}}return state;}
export function saveData(s){return{version:1,resources:s.resources,buildings:s.buildings,day:s.day,elapsed:s.elapsed,production:s.production,paused:s.paused,speed:s.speed,quest:s.quest,learned:s.learned,selected:s.selected,logs:s.logs.slice(-50),actors:s.actors.map(({id,x,y,follow})=>({id,x,y,follow}))};}
export function walk(s,a,goal){const path=findPath(a,goal);if(!path)return false;a.path=path;a.goal=path.at(-1);s.metrics.routes++;return true;}
export function upgrade(s,id){const b=s.buildings[id];if(!b||b.level>=5)return{ok:false,text:'此处已修缮至五级。'};const wood=b.wood*b.level,stone=b.stone*b.level;if(s.resources.wood<wood||s.resources.stone<stone)return{ok:false,text:`修缮需木材 ${wood}、石料 ${stone}。`};s.resources.wood-=wood;s.resources.stone-=stone;b.level++;return{ok:true,text:`修缮完成 · ${b.level} 级`};}
const patrol={songyan:['mainCourt','eastCourt','stairsUpper'],linbo:['workshop','workshopGate','worksLane'],wenling:['meditation','bambooSteps','bambooLane']};
export function update(s,dt,onEvent){if(s.paused)return;dt=Math.min(dt,.25)*s.speed;s.elapsed+=dt;s.production+=dt;if(s.elapsed>=180){s.elapsed-=180;s.day++;onEvent('日出竹林，又是新的一日。');}if(s.production>=18){s.production-=18;s.resources.herb+=3*s.buildings.herbs.level;s.resources.wood+=2*s.buildings.workshop.level;s.resources.stone+=s.buildings.works.level;s.resources.grain+=2*s.buildings.kitchen.level;onEvent(`门人完成照料，灵草 +${3*s.buildings.herbs.level}。`);}
 const master=s.actors[0];for(const a of s.actors){a.moving=false;if(a.follow&&a.id!=='master'){a.wait-=dt;if(a.wait<=0){a.wait=.8;const gap=distance(a,master);if(gap>42)walk(s,a,master);else if(!master.path.length&&gap<18)a.path=[];}}else if(patrol[a.id]&&!a.path.length){a.wait-=dt;if(a.wait<0){const choices=patrol[a.id];a.patrol=(a.patrol??0)+1;walk(s,a,point(choices[a.patrol%choices.length]));a.wait=10+a.variant*3;}}
 let budget=46*dt;while(a.path.length&&budget>0){const goal=a.path[0],d=distance(a,goal);if(d<.001){a.path.shift();continue;}const step=Math.min(budget,d),next={x:a.x+(goal.x-a.x)*step/d,y:a.y+(goal.y-a.y)*step/d};if(a.id!=='master'&&s.actors.some(other=>other!==a&&s.actors.indexOf(other)<s.actors.indexOf(a)&&distance(next,other)<12)){a.wait=Math.max(a.wait,.3);break;}const result=sweep(a,next);if(result.blocked){s.metrics.blocked++;a.path=[];onEvent(`${a.name}停在道路边缘。`);break;}a.facing=goal.x>=a.x?1:-1;a.back=goal.y<a.y-1;a.x=result.x;a.y=result.y;a.steps+=step;a.moving=true;budget-=step;if(step>=d-.01)a.path.shift();}if(!canStand(a)){s.metrics.invalid++;a.path=[];} }
}
